using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjectManagement.Features.MediaLibrary.Data.Migrations;

[DbContext(typeof(MediaLibraryDbContext))]
[Migration("20260818170000_AddOrganisationalMediaAlbums")]
public sealed class AddOrganisationalMediaAlbums : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
ALTER TABLE "MediaAssets"
    ADD COLUMN IF NOT EXISTS "EditorialCaption" varchar(1024) NULL;
ALTER TABLE "MediaAssets"
    ADD COLUMN IF NOT EXISTS "EditorialCaptionUpdatedByUserId" varchar(450) NULL;
ALTER TABLE "MediaAssets"
    ADD COLUMN IF NOT EXISTS "EditorialCaptionUpdatedAtUtc" timestamptz NULL;
ALTER TABLE "MediaAssets"
    ADD COLUMN IF NOT EXISTS "EditorialConcurrencyToken" uuid NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "MediaAssets"
    ALTER COLUMN "EditorialConcurrencyToken" DROP DEFAULT;

CREATE TABLE IF NOT EXISTS "MediaAlbums" (
    "Id" uuid NOT NULL,
    "Name" varchar(160) NOT NULL,
    "Description" varchar(1024) NULL,
    "CreatedByUserId" varchar(450) NOT NULL,
    "CreatedAtUtc" timestamptz NOT NULL,
    "UpdatedByUserId" varchar(450) NOT NULL,
    "UpdatedAtUtc" timestamptz NOT NULL,
    "IsArchived" boolean NOT NULL,
    "ArchivedByUserId" varchar(450) NULL,
    "ArchivedAtUtc" timestamptz NULL,
    "CoverMediaAssetId" bigint NULL,
    "ConcurrencyToken" uuid NOT NULL,
    CONSTRAINT "PK_MediaAlbums" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaAlbums_MediaAssets_CoverMediaAssetId"
        FOREIGN KEY ("CoverMediaAssetId") REFERENCES "MediaAssets"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "MediaAlbumItems" (
    "MediaAlbumId" uuid NOT NULL,
    "MediaAssetId" bigint NOT NULL,
    "SortOrder" bigint NOT NULL,
    "AddedByUserId" varchar(450) NOT NULL,
    "AddedAtUtc" timestamptz NOT NULL,
    CONSTRAINT "PK_MediaAlbumItems" PRIMARY KEY ("MediaAlbumId", "MediaAssetId"),
    CONSTRAINT "FK_MediaAlbumItems_MediaAlbums_MediaAlbumId"
        FOREIGN KEY ("MediaAlbumId") REFERENCES "MediaAlbums"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MediaAlbumItems_MediaAssets_MediaAssetId"
        FOREIGN KEY ("MediaAssetId") REFERENCES "MediaAssets"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "MediaCurationAudits" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Action" varchar(64) NOT NULL,
    "MediaAlbumId" uuid NULL,
    "MediaAssetId" bigint NULL,
    "PerformedByUserId" varchar(450) NOT NULL,
    "PerformedAtUtc" timestamptz NOT NULL,
    "MetadataJson" jsonb NULL,
    CONSTRAINT "PK_MediaCurationAudits" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MediaCurationAudits_MediaAlbums_MediaAlbumId"
        FOREIGN KEY ("MediaAlbumId") REFERENCES "MediaAlbums"("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_MediaCurationAudits_MediaAssets_MediaAssetId"
        FOREIGN KEY ("MediaAssetId") REFERENCES "MediaAssets"("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_MediaAlbums_ActiveName_CI"
ON "MediaAlbums" (lower("Name"))
WHERE "IsArchived" = FALSE;

CREATE INDEX IF NOT EXISTS "IX_MediaAlbums_IsArchived_UpdatedAtUtc"
ON "MediaAlbums" ("IsArchived", "UpdatedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_MediaAlbums_CreatedByUserId"
ON "MediaAlbums" ("CreatedByUserId");
CREATE INDEX IF NOT EXISTS "IX_MediaAlbums_CoverMediaAssetId"
ON "MediaAlbums" ("CoverMediaAssetId");
CREATE INDEX IF NOT EXISTS "IX_MediaAlbumItems_MediaAlbumId_SortOrder"
ON "MediaAlbumItems" ("MediaAlbumId", "SortOrder");
CREATE INDEX IF NOT EXISTS "IX_MediaAlbumItems_MediaAssetId"
ON "MediaAlbumItems" ("MediaAssetId");
CREATE INDEX IF NOT EXISTS "IX_MediaCurationAudits_MediaAlbumId_PerformedAtUtc"
ON "MediaCurationAudits" ("MediaAlbumId", "PerformedAtUtc");
CREATE INDEX IF NOT EXISTS "IX_MediaCurationAudits_MediaAssetId_PerformedAtUtc"
ON "MediaCurationAudits" ("MediaAssetId", "PerformedAtUtc");
""");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
DROP TABLE IF EXISTS "MediaCurationAudits";
DROP TABLE IF EXISTS "MediaAlbumItems";
DROP TABLE IF EXISTS "MediaAlbums";
ALTER TABLE "MediaAssets" DROP COLUMN IF EXISTS "EditorialConcurrencyToken";
ALTER TABLE "MediaAssets" DROP COLUMN IF EXISTS "EditorialCaptionUpdatedAtUtc";
ALTER TABLE "MediaAssets" DROP COLUMN IF EXISTS "EditorialCaptionUpdatedByUserId";
ALTER TABLE "MediaAssets" DROP COLUMN IF EXISTS "EditorialCaption";
""");
    }
}
