using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using W = DocumentFormat.OpenXml.Wordprocessing;
using ProjectManagement.Utilities;

namespace ProjectManagement.Services.Ffc.Exports;

public sealed class FfcDetailedWordDocumentBuilder
{
    private const string BodyFont = "Arial";
    private const string Navy = "17365D";
    private const string DarkText = "172033";
    private const string MutedText = "526174";
    private const string HeaderFill = "DCE6F1";
    private const string GroupFill = "EEF3F8";
    private const string LabelFill = "F5F7FA";
    private const string BorderColor = "AAB7C6";
    private const string White = "FFFFFF";

    private static readonly int[] DetailColumnWidths = [650, 3000, 1250, 900, 1500, 4200, 4200];
    private static readonly int DetailTableWidth = DetailColumnWidths.Sum();

    public byte[] Build(FfcDetailedTableExportContext context)
    {
        ArgumentNullException.ThrowIfNull(context);

        using var stream = new MemoryStream();
        using (var document = WordprocessingDocument.Create(stream, WordprocessingDocumentType.Document, autoSave: true))
        {
            SetPackageProperties(document, context);

            var mainPart = document.AddMainDocumentPart();
            mainPart.Document = new W.Document(new W.Body());
            AddStyles(mainPart);
            AddDocumentSettings(mainPart);

            var footerPart = mainPart.AddNewPart<FooterPart>();
            footerPart.Footer = BuildFooter(context.HandlingMarking);
            footerPart.Footer.Save();

            HeaderPart? headerPart = null;
            if (!string.IsNullOrWhiteSpace(context.HandlingMarking))
            {
                headerPart = mainPart.AddNewPart<HeaderPart>();
                headerPart.Header = BuildHeader(context.HandlingMarking!);
                headerPart.Header.Save();
            }

            var body = mainPart.Document.Body!;
            AppendReportHeading(body, context);
            AppendPortfolioSummary(body, context.Summary);
            body.Append(CreateSectionHeading("Project-wise update"));
            body.Append(BuildDetailedTable(context.Groups));
            body.Append(BuildSectionProperties(mainPart, headerPart, footerPart));

            mainPart.Document.Save();
        }

        return stream.ToArray();
    }

    private static void SetPackageProperties(WordprocessingDocument document, FfcDetailedTableExportContext context)
    {
        document.PackageProperties.Title = context.Title;
        document.PackageProperties.Subject = context.ScopeLabel;
        document.PackageProperties.Creator = "PRISM ERP";
        document.PackageProperties.LastModifiedBy = "PRISM ERP";
        document.PackageProperties.Created = context.GeneratedAtUtc.UtcDateTime;
        document.PackageProperties.Modified = context.GeneratedAtUtc.UtcDateTime;
        document.PackageProperties.Description = "Editable FFC project portfolio update generated by PRISM ERP.";
    }

    private static void AddStyles(MainDocumentPart mainPart)
    {
        var stylesPart = mainPart.AddNewPart<StyleDefinitionsPart>();
        stylesPart.Styles = new W.Styles(
            CreateParagraphStyle("Normal", "Normal", 18, DarkText, isDefault: true),
            CreateParagraphStyle("FfcTitle", "FFC report title", 32, Navy, bold: true, spaceAfter: 80),
            CreateParagraphStyle("FfcMeta", "FFC report metadata", 18, MutedText, spaceAfter: 25),
            CreateParagraphStyle("FfcSection", "FFC section heading", 21, Navy, bold: true, spaceBefore: 100, spaceAfter: 55));
        stylesPart.Styles.Save();
    }

    private static W.Style CreateParagraphStyle(
        string styleId,
        string name,
        int fontSizeHalfPoints,
        string color,
        bool bold = false,
        bool isDefault = false,
        int spaceBefore = 0,
        int spaceAfter = 0)
    {
        var style = new W.Style
        {
            Type = W.StyleValues.Paragraph,
            StyleId = styleId,
            Default = isDefault
        };

        style.Append(new W.StyleName { Val = name });
        style.Append(new W.StyleParagraphProperties(
            new W.SpacingBetweenLines
            {
                Before = spaceBefore.ToString(CultureInfo.InvariantCulture),
                After = spaceAfter.ToString(CultureInfo.InvariantCulture),
                Line = "240",
                LineRule = W.LineSpacingRuleValues.Auto
            }));

        var runProperties = new W.StyleRunProperties(
            new W.RunFonts { Ascii = BodyFont, HighAnsi = BodyFont, EastAsia = BodyFont, ComplexScript = BodyFont },
            new W.Color { Val = color },
            new W.FontSize { Val = fontSizeHalfPoints.ToString(CultureInfo.InvariantCulture) },
            new W.FontSizeComplexScript { Val = fontSizeHalfPoints.ToString(CultureInfo.InvariantCulture) });

        if (bold)
        {
            runProperties.Append(new W.Bold(), new W.BoldComplexScript());
        }

        style.Append(runProperties);
        return style;
    }

    private static void AddDocumentSettings(MainDocumentPart mainPart)
    {
        var settingsPart = mainPart.AddNewPart<DocumentSettingsPart>();
        settingsPart.Settings = new W.Settings(
            new W.UpdateFieldsOnOpen { Val = true });
        settingsPart.Settings.Save();
    }

    private static void AppendReportHeading(W.Body body, FfcDetailedTableExportContext context)
    {
        var generatedAtIst = TimeZoneInfo.ConvertTime(context.GeneratedAtUtc, TimeZoneHelper.GetIst());

        body.Append(CreateStyledParagraph(context.Title, "FfcTitle"));
        body.Append(CreateStyledParagraph($"Scope: {context.ScopeLabel}", "FfcMeta"));
        body.Append(CreateStyledParagraph(
            $"Position as at {generatedAtIst:dd MMM yyyy, HH:mm} IST",
            "FfcMeta"));

        if (!string.IsNullOrWhiteSpace(context.HandlingMarking))
        {
            body.Append(CreateParagraph(
                context.HandlingMarking!,
                18,
                bold: true,
                color: "9C1C1C",
                alignment: W.JustificationValues.Center,
                spaceAfter: 80));
        }
    }

    private static void AppendPortfolioSummary(W.Body body, FfcDetailedTableExportSummary summary)
    {
        body.Append(CreateSectionHeading("Portfolio summary"));

        var rows = new[]
        {
            ("Countries", summary.CountryCount.ToString("N0", CultureInfo.InvariantCulture),
                "Country–year records", summary.RecordCount.ToString("N0", CultureInfo.InvariantCulture)),
            ("Projects", summary.ProjectCount.ToString("N0", CultureInfo.InvariantCulture),
                "Total quantity", summary.TotalQuantity.ToString("N0", CultureInfo.InvariantCulture)),
            ("Installed", summary.InstalledQuantity.ToString("N0", CultureInfo.InvariantCulture),
                "Delivered, awaiting installation", summary.DeliveredNotInstalledQuantity.ToString("N0", CultureInfo.InvariantCulture)),
            ("Planned", summary.PlannedQuantity.ToString("N0", CultureInfo.InvariantCulture),
                "Available project cost (₹ lakh)", summary.AvailableCostInLakh.ToString("N2", CultureInfo.InvariantCulture)),
            ("Cost coverage", summary.CostCoverageLabel,
                "Cost note", "The cost total includes only projects with a resolved project cost.")
        };

        var table = new W.Table(
            new W.TableProperties(
                new W.TableWidth { Width = DetailTableWidth.ToString(CultureInfo.InvariantCulture), Type = W.TableWidthUnitValues.Dxa },
                new W.TableLayout { Type = W.TableLayoutValues.Fixed },
                CreateTableBorders(BorderColor, 4)));

        table.Append(new W.TableGrid(
            new W.GridColumn { Width = "2600" },
            new W.GridColumn { Width = "1900" },
            new W.GridColumn { Width = "3450" },
            new W.GridColumn { Width = "7750" }));

        foreach (var row in rows)
        {
            table.Append(new W.TableRow(
                new W.TableRowProperties(new W.CantSplit()),
                CreateCell(row.Item1, 2600, bold: true, fill: LabelFill),
                CreateCell(row.Item2, 1900, alignment: W.JustificationValues.Right),
                CreateCell(row.Item3, 3450, bold: true, fill: LabelFill),
                CreateCell(row.Item4, 7750)));
        }

        body.Append(table);
        body.Append(CreateSpacerParagraph(70));
    }

    private static W.Paragraph CreateSectionHeading(string text)
        => CreateStyledParagraph(text, "FfcSection", keepWithNext: true);

    private static W.Table BuildDetailedTable(IReadOnlyList<FfcDetailedGroupVm> groups)
    {
        var table = new W.Table(
            new W.TableProperties(
                new W.TableWidth { Width = DetailTableWidth.ToString(CultureInfo.InvariantCulture), Type = W.TableWidthUnitValues.Dxa },
                new W.TableLayout { Type = W.TableLayoutValues.Fixed },
                CreateTableBorders(BorderColor, 5)));

        table.Append(new W.TableGrid(
            DetailColumnWidths.Select(width => new W.GridColumn
            {
                Width = width.ToString(CultureInfo.InvariantCulture)
            })));

        table.Append(BuildHeaderRow());

        foreach (var group in (groups ?? Array.Empty<FfcDetailedGroupVm>())
                     .Where(group => group.Rows is { Count: > 0 }))
        {
            table.Append(BuildGroupSeparatorRow(group));

            for (var index = 0; index < group.Rows.Count; index++)
            {
                var row = group.Rows[index];
                var rowProperties = new W.TableRowProperties(new W.CantSplit());
                var tableRow = new W.TableRow(rowProperties);

                tableRow.Append(
                    CreateCell(row.Serial.ToString(CultureInfo.InvariantCulture), DetailColumnWidths[0], alignment: W.JustificationValues.Center),
                    CreateCell(row.ProjectName, DetailColumnWidths[1], bold: true),
                    CreateCell(
                        row.CostInCr.HasValue
                            ? (row.CostInCr.Value * 100m).ToString("N2", CultureInfo.InvariantCulture)
                            : "—",
                        DetailColumnWidths[2],
                        alignment: W.JustificationValues.Right),
                    CreateCell(row.Quantity.ToString("N0", CultureInfo.InvariantCulture), DetailColumnWidths[3], alignment: W.JustificationValues.Right),
                    CreateCell(row.Status, DetailColumnWidths[4]),
                    CreateCell(
                        string.IsNullOrWhiteSpace(row.ProgressText) ? "No progress recorded." : row.ProgressText!,
                        DetailColumnWidths[5],
                        italic: string.IsNullOrWhiteSpace(row.ProgressText)));

                tableRow.Append(CreateOverallStatusCell(
                    index == 0
                        ? (string.IsNullOrWhiteSpace(group.OverallRemarks) ? "No overall status recorded." : group.OverallRemarks!)
                        : string.Empty,
                    mergeRows: group.Rows.Count > 1,
                    restart: index == 0,
                    italic: index == 0 && string.IsNullOrWhiteSpace(group.OverallRemarks)));

                table.Append(tableRow);
            }
        }

        return table;
    }

    private static W.TableRow BuildHeaderRow()
    {
        var row = new W.TableRow(
            new W.TableRowProperties(
                new W.TableHeader(),
                new W.CantSplit()));

        var headings = new[]
        {
            "S. No.",
            "Project",
            "Cost (₹ lakh)",
            "Quantity",
            "Status",
            "Current progress",
            "Overall status"
        };

        for (var index = 0; index < headings.Length; index++)
        {
            var alignment = index is 0 ? W.JustificationValues.Center
                : index is 2 or 3 ? W.JustificationValues.Right
                : W.JustificationValues.Left;

            row.Append(CreateCell(
                headings[index],
                DetailColumnWidths[index],
                bold: true,
                fill: HeaderFill,
                alignment: alignment,
                color: Navy));
        }

        return row;
    }

    private static W.TableRow BuildGroupSeparatorRow(FfcDetailedGroupVm group)
    {
        var paragraphProperties = new W.ParagraphProperties(
            new W.KeepNext(),
            new W.SpacingBetweenLines { Before = "20", After = "20" },
            new W.Tabs(new W.TabStop
            {
                Val = W.TabStopValues.Right,
                Position = DetailTableWidth - 220
            }));

        var paragraph = new W.Paragraph(paragraphProperties);
        paragraph.Append(CreateRun($"{group.CountryName} – {group.Year}", 18, bold: true, color: Navy));
        paragraph.Append(new W.Run(new W.TabChar()));
        paragraph.Append(CreateRun(group.CountryCode, 17, bold: true, color: MutedText));

        var cell = new W.TableCell(
            new W.TableCellProperties(
                new W.GridSpan { Val = 7 },
                new W.TableCellWidth { Width = DetailTableWidth.ToString(CultureInfo.InvariantCulture), Type = W.TableWidthUnitValues.Dxa },
                new W.Shading { Fill = GroupFill, Val = W.ShadingPatternValues.Clear },
                new W.TableCellVerticalAlignment { Val = W.TableVerticalAlignmentValues.Center }),
            paragraph);

        return new W.TableRow(
            new W.TableRowProperties(new W.CantSplit()),
            cell);
    }

    private static W.TableCell CreateOverallStatusCell(
        string text,
        bool mergeRows,
        bool restart,
        bool italic)
    {
        var properties = new W.TableCellProperties(
            new W.TableCellWidth
            {
                Width = DetailColumnWidths[6].ToString(CultureInfo.InvariantCulture),
                Type = W.TableWidthUnitValues.Dxa
            },
            new W.TableCellVerticalAlignment { Val = W.TableVerticalAlignmentValues.Top });

        if (mergeRows)
        {
            properties.Append(new W.VerticalMerge
            {
                Val = restart ? W.MergedCellValues.Restart : W.MergedCellValues.Continue
            });
        }

        return new W.TableCell(
            properties,
            restart
                ? CreateParagraph(text, 17, italic: italic, color: italic ? MutedText : DarkText, spaceAfter: 0)
                : new W.Paragraph());
    }

    private static W.TableCell CreateCell(
        string? text,
        int width,
        bool bold = false,
        bool italic = false,
        string? fill = null,
        W.JustificationValues? alignment = null,
        string color = DarkText)
    {
        var properties = new W.TableCellProperties(
            new W.TableCellWidth
            {
                Width = width.ToString(CultureInfo.InvariantCulture),
                Type = W.TableWidthUnitValues.Dxa
            },
            new W.TableCellVerticalAlignment { Val = W.TableVerticalAlignmentValues.Top });

        if (!string.IsNullOrWhiteSpace(fill))
        {
            properties.Append(new W.Shading { Fill = fill, Val = W.ShadingPatternValues.Clear });
        }

        return new W.TableCell(
            properties,
            CreateParagraph(text ?? string.Empty, 17, bold, italic, color, alignment, 0));
    }

    private static W.Paragraph CreateStyledParagraph(string text, string styleId, bool keepWithNext = false)
    {
        var properties = new W.ParagraphProperties(new W.ParagraphStyleId { Val = styleId });
        if (keepWithNext)
        {
            properties.Append(new W.KeepNext());
        }

        var paragraph = new W.Paragraph(properties);
        var run = new W.Run();
        AppendTextWithBreaks(run, text);
        paragraph.Append(run);
        return paragraph;
    }

    private static W.Paragraph CreateParagraph(
        string text,
        int fontSizeHalfPoints,
        bool bold = false,
        bool italic = false,
        string color = DarkText,
        W.JustificationValues? alignment = null,
        int spaceAfter = 20)
    {
        var resolvedAlignment = alignment ?? W.JustificationValues.Left;

        var properties = new W.ParagraphProperties(
            new W.Justification { Val = resolvedAlignment },
            new W.SpacingBetweenLines
            {
                Before = "0",
                After = spaceAfter.ToString(CultureInfo.InvariantCulture),
                Line = "220",
                LineRule = W.LineSpacingRuleValues.Auto
            });

        return new W.Paragraph(properties, CreateRun(text, fontSizeHalfPoints, bold, italic, color));
    }

    private static W.Run CreateRun(
        string? text,
        int fontSizeHalfPoints,
        bool bold = false,
        bool italic = false,
        string color = DarkText)
    {
        var properties = new W.RunProperties(
            new W.RunFonts { Ascii = BodyFont, HighAnsi = BodyFont, EastAsia = BodyFont, ComplexScript = BodyFont },
            new W.Color { Val = color },
            new W.FontSize { Val = fontSizeHalfPoints.ToString(CultureInfo.InvariantCulture) },
            new W.FontSizeComplexScript { Val = fontSizeHalfPoints.ToString(CultureInfo.InvariantCulture) });

        if (bold)
        {
            properties.Append(new W.Bold(), new W.BoldComplexScript());
        }

        if (italic)
        {
            properties.Append(new W.Italic(), new W.ItalicComplexScript());
        }

        var run = new W.Run(properties);
        AppendTextWithBreaks(run, text);
        return run;
    }

    private static void AppendTextWithBreaks(W.Run run, string? value)
    {
        var normalized = (value ?? string.Empty)
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Replace("\r", "\n", StringComparison.Ordinal);
        var lines = normalized.Split('\n');

        for (var index = 0; index < lines.Length; index++)
        {
            if (index > 0)
            {
                run.Append(new W.Break());
            }

            run.Append(new W.Text(lines[index]) { Space = SpaceProcessingModeValues.Preserve });
        }
    }

    private static W.Paragraph CreateSpacerParagraph(int after)
        => new(
            new W.ParagraphProperties(
                new W.SpacingBetweenLines
                {
                    Before = "0",
                    After = after.ToString(CultureInfo.InvariantCulture)
                }));

    private static W.TableBorders CreateTableBorders(string color, uint size)
        => new(
            new W.TopBorder { Val = W.BorderValues.Single, Color = color, Size = size },
            new W.LeftBorder { Val = W.BorderValues.Single, Color = color, Size = size },
            new W.BottomBorder { Val = W.BorderValues.Single, Color = color, Size = size },
            new W.RightBorder { Val = W.BorderValues.Single, Color = color, Size = size },
            new W.InsideHorizontalBorder { Val = W.BorderValues.Single, Color = color, Size = size },
            new W.InsideVerticalBorder { Val = W.BorderValues.Single, Color = color, Size = size });

    private static W.Header BuildHeader(string handlingMarking)
    {
        var paragraph = CreateParagraph(
            handlingMarking,
            17,
            bold: true,
            color: "9C1C1C",
            alignment: W.JustificationValues.Center,
            spaceAfter: 0);

        return new W.Header(paragraph);
    }

    private static W.Footer BuildFooter(string? handlingMarking)
    {
        var table = new W.Table(
            new W.TableProperties(
                new W.TableWidth { Width = DetailTableWidth.ToString(CultureInfo.InvariantCulture), Type = W.TableWidthUnitValues.Dxa },
                new W.TableLayout { Type = W.TableLayoutValues.Fixed },
                new W.TableBorders(
                    new W.TopBorder { Val = W.BorderValues.Single, Color = BorderColor, Size = 5 },
                    new W.LeftBorder { Val = W.BorderValues.Nil },
                    new W.BottomBorder { Val = W.BorderValues.Nil },
                    new W.RightBorder { Val = W.BorderValues.Nil },
                    new W.InsideHorizontalBorder { Val = W.BorderValues.Nil },
                    new W.InsideVerticalBorder { Val = W.BorderValues.Nil })));

        table.Append(new W.TableGrid(
            new W.GridColumn { Width = "6500" },
            new W.GridColumn { Width = "4500" },
            new W.GridColumn { Width = "4700" }));

        var left = CreateCell("PRISM ERP · Simulator Development Division", 6500, color: MutedText);
        var centre = CreateCell(
            handlingMarking ?? string.Empty,
            4500,
            bold: !string.IsNullOrWhiteSpace(handlingMarking),
            alignment: W.JustificationValues.Center,
            color: string.IsNullOrWhiteSpace(handlingMarking) ? MutedText : "9C1C1C");

        var pageParagraph = new W.Paragraph(
            new W.ParagraphProperties(
                new W.Justification { Val = W.JustificationValues.Right },
                new W.SpacingBetweenLines { Before = "0", After = "0" }));
        pageParagraph.Append(CreateRun("Page ", 16, color: MutedText));
        pageParagraph.Append(CreatePageField("PAGE"));
        pageParagraph.Append(CreateRun(" of ", 16, color: MutedText));
        pageParagraph.Append(CreatePageField("NUMPAGES"));

        var right = new W.TableCell(
            new W.TableCellProperties(
                new W.TableCellWidth { Width = "4700", Type = W.TableWidthUnitValues.Dxa },
                new W.TableCellVerticalAlignment { Val = W.TableVerticalAlignmentValues.Center }),
            pageParagraph);

        table.Append(new W.TableRow(left, centre, right));
        return new W.Footer(table);
    }

    private static W.SimpleField CreatePageField(string instruction)
    {
        var field = new W.SimpleField { Instruction = instruction };
        field.Append(CreateRun("1", 16, color: MutedText));
        return field;
    }

    private static W.SectionProperties BuildSectionProperties(
        MainDocumentPart mainPart,
        HeaderPart? headerPart,
        FooterPart footerPart)
    {
        var section = new W.SectionProperties();

        if (headerPart is not null)
        {
            section.Append(new W.HeaderReference
            {
                Type = W.HeaderFooterValues.Default,
                Id = mainPart.GetIdOfPart(headerPart)
            });
        }

        section.Append(new W.FooterReference
        {
            Type = W.HeaderFooterValues.Default,
            Id = mainPart.GetIdOfPart(footerPart)
        });

        section.Append(
            new W.PageSize
            {
                Width = 16838U,
                Height = 11906U,
                Orient = W.PageOrientationValues.Landscape
            },
            new W.PageMargin
            {
                Top = 567,
                Right = 567U,
                Bottom = 567,
                Left = 567U,
                Header = 300U,
                Footer = 300U,
                Gutter = 0U
            },
            new W.Columns { Space = "360" },
            new W.DocGrid { LinePitch = 360 });

        return section;
    }
}
