using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Presentation;
using Microsoft.AspNetCore.Hosting;

namespace ProjectManagement.Services.Ffc.Presentation;

public sealed class FfcSlideComposer : IFfcSlideComposer
{
    private const double SlideWidth = 13.333333;
    private const double SlideHeight = 7.5;

    private const string Navy = "12223A";
    private const string Blue = "3367E8";
    private const string Green = "2E8B57";
    private const string DeliveredBlue = "4D78E8";
    private const string PlannedGray = "B7C0CC";
    private const string LightBackground = "F4F7FB";
    private const string CardBackground = "FFFFFF";
    private const string Text = "111827";
    private const string Muted = "667085";
    private const string Border = "D8E0EA";
    private const string Amber = "D97706";
    private const string Red = "C83B3B";

    private readonly IFfcPresentationMapRenderer _mapRenderer;
    private readonly string _templatePath;
    private readonly string? _logoPath;

    public FfcSlideComposer(
        IFfcPresentationMapRenderer mapRenderer,
        IWebHostEnvironment environment)
    {
        _mapRenderer = mapRenderer ?? throw new ArgumentNullException(nameof(mapRenderer));
        ArgumentNullException.ThrowIfNull(environment);

        _templatePath = Path.Combine(
            environment.ContentRootPath,
            "Resources",
            "FfcPresentation",
            "FfcPortfolioTemplate.pptx");

        var logoCandidate = Path.Combine(environment.WebRootPath, "img", "logos", "sdd.png");
        _logoPath = File.Exists(logoCandidate) ? logoCandidate : null;
    }

    public (byte[] Content, int SlideCount) Compose(FfcPresentationData data)
    {
        ArgumentNullException.ThrowIfNull(data);
        if (!File.Exists(_templatePath))
        {
            throw new FileNotFoundException("FFC presentation template was not found.", _templatePath);
        }

        var plans = BuildPlans(data);
        var templateBytes = File.ReadAllBytes(_templatePath);
        using var stream = new MemoryStream(templateBytes.Length + 2_000_000);
        stream.Write(templateBytes, 0, templateBytes.Length);
        stream.Position = 0;

        using (var document = PresentationDocument.Open(stream, true))
        {
            var presentationPart = document.PresentationPart
                ?? throw new InvalidOperationException("The PowerPoint template has no presentation part.");
            var layoutPart = FindBlankLayout(presentationPart)
                ?? throw new InvalidOperationException("The PowerPoint template has no slide layout.");

            RemoveTemplateSlides(presentationPart);
            var slideIdList = presentationPart.Presentation.SlideIdList;
            if (slideIdList is null)
            {
                slideIdList = new SlideIdList();
                presentationPart.Presentation.Append(slideIdList);
            }
            uint nextSlideId = 256;
            var logo = _logoPath is null ? null : File.ReadAllBytes(_logoPath);
            var mapImage = _mapRenderer.Render(data.Countries);

            for (var index = 0; index < plans.Count; index++)
            {
                var slidePart = presentationPart.AddNewPart<SlidePart>();
                slidePart.AddPart(layoutPart);
                var canvas = new SlideCanvas(slidePart);
                plans[index].Render(canvas, mapImage, logo);
                AddStandardFooter(canvas, data, index + 1, plans.Count, plans[index].IsCover);
                canvas.Commit();

                var relationshipId = presentationPart.GetIdOfPart(slidePart);
                slideIdList.Append(new SlideId
                {
                    Id = nextSlideId++,
                    RelationshipId = relationshipId
                });
            }

            presentationPart.Presentation.Save();
            document.PackageProperties.Title = data.Title;
            document.PackageProperties.Subject = "FFC portfolio briefing generated by PRISM ERP";
            document.PackageProperties.Creator = "Simulator Development Division";
            document.PackageProperties.LastModifiedBy = "PRISM ERP";
            document.PackageProperties.Modified = DateTime.UtcNow;
        }

        return (stream.ToArray(), plans.Count);
    }

    private List<SlidePlan> BuildPlans(FfcPresentationData data)
    {
        var plans = new List<SlidePlan>
        {
            new(true, (canvas, _, logo) => RenderCover(canvas, data, logo)),
            new(false, (canvas, _, _) => RenderAtAGlance(canvas, data)),
            new(false, (canvas, map, _) => RenderGlobalFootprint(canvas, data, map))
        };

        AddCountryUnitPositionSlides(plans, data);
        AddMilestoneSlides(plans, data);
        plans.Add(new SlidePlan(false, (canvas, _, _) => RenderOperationalFocus(canvas, data)));

        if (data.PresentationType == FfcPresentationType.FullPortfolio)
        {
            foreach (var country in data.Countries)
            {
                var capturedCountry = country;
                plans.Add(new SlidePlan(false, (canvas, _, _) => RenderCountrySummary(canvas, data, capturedCountry)));

                if (data.IncludeProjects)
                {
                    AddProjectSlides(plans, data, capturedCountry);
                }

                if (data.IncludeAttachmentRegister && capturedCountry.Records.Any(record => record.Attachments.Count > 0))
                {
                    AddAttachmentSlides(plans, data, capturedCountry);
                }
            }

            AddAppendixSlides(plans, data);
        }

        return plans;
    }

    private static void RenderCover(SlideCanvas canvas, FfcPresentationData data, byte[]? logo)
    {
        canvas.AddRect(0, 0, SlideWidth, SlideHeight, Navy);
        canvas.AddRect(0, 0, .18, SlideHeight, Blue);
        canvas.AddRect(8.75, 0, 4.58, SlideHeight, "172D4B");
        canvas.AddRect(9.25, .6, 3.35, .12, Blue);
        canvas.AddRect(9.25, .88, 2.55, .12, Green);
        canvas.AddRect(9.25, 1.16, 1.65, .12, DeliveredBlue);

        if (logo is not null)
        {
            canvas.AddImage(logo, .62, .55, .64, .64, "SDD logo");
        }
        canvas.AddText(1.42, .58, 5.9, .35, "SIMULATOR DEVELOPMENT DIVISION", 15, "DCE7FF", true, "l");
        canvas.AddText(
            .68,
            2.0,
            7.55,
            1.45,
            data.Title.ToUpperInvariant(),
            CoverTitleFontSize(data.Title),
            "FFFFFF",
            true,
            "l");
        canvas.AddText(.7, 3.55, 7.15, .78, data.Subtitle, 20, "C7D5E7", false, "l");
        canvas.AddText(.7, 5.55, 6.8, .4, "FRIENDLY FOREIGN COUNTRIES · SIMULATOR PROJECTS", 13, "9FB4CD", true, "l");
        canvas.AddText(.7, 6.05, 6.8, .34, $"Generated {DateTimeOffset.Now:dd MMM yyyy HH:mm}", 11, "91A6BF", false, "l");

        canvas.AddText(9.25, 2.25, 3.25, .5, data.Summary.CountryCount.ToString(CultureInfo.InvariantCulture), 28, "FFFFFF", true, "l");
        canvas.AddText(9.25, 2.78, 3.25, .35, "COUNTRIES", 12, "AFC0D3", true, "l");
        canvas.AddText(9.25, 3.45, 3.25, .5, data.Summary.ProjectCount.ToString(CultureInfo.InvariantCulture), 28, "FFFFFF", true, "l");
        canvas.AddText(9.25, 3.98, 3.25, .35, "PROJECTS", 12, "AFC0D3", true, "l");
        canvas.AddText(9.25, 4.65, 3.25, .5, data.Summary.TotalUnits.ToString(CultureInfo.InvariantCulture), 28, "FFFFFF", true, "l");
        canvas.AddText(9.25, 5.18, 3.25, .35, "TOTAL QUANTITY", 12, "AFC0D3", true, "l");
    }

    private static void RenderAtAGlance(SlideCanvas canvas, FfcPresentationData data)
    {
        AddSlideTitle(canvas, "Portfolio at a glance", "Current FFC portfolio scale and quantity status");
        var summary = data.Summary;
        var cards = new[]
        {
            ("COUNTRIES", summary.CountryCount),
            ("COUNTRY-YEAR RECORDS", summary.RecordCount),
            ("PROJECTS", summary.ProjectCount),
            ("TOTAL QUANTITY", summary.TotalUnits)
        };

        for (var index = 0; index < cards.Length; index++)
        {
            var x = .65 + (index * 3.08);
            canvas.AddRoundedRect(x, 1.35, 2.72, 1.45, CardBackground, Border, .09);
            canvas.AddText(x + .22, 1.68, 2.25, .52, cards[index].Item2.ToString(CultureInfo.InvariantCulture), 28, Text, true, "l");
            canvas.AddText(x + .22, 2.27, 2.25, .3, cards[index].Item1, 11, Muted, true, "l");
        }

        canvas.AddText(.7, 3.28, 5.2, .36, "QUANTITY STATUS", 12, Muted, true, "l");
        AddSegmentedBar(canvas, .7, 3.82, 11.95, .34, summary.InstalledUnits, summary.DeliveredNotInstalledUnits, summary.PlannedUnits);

        AddMetricLegend(canvas, .75, 4.38, "Installed", summary.InstalledUnits, Green);
        AddMetricLegend(canvas, 4.45, 4.38, "Delivered, awaiting installation", summary.DeliveredNotInstalledUnits, DeliveredBlue);
        AddMetricLegend(canvas, 9.2, 4.38, "Planned", summary.PlannedUnits, PlannedGray);

        var deliveredPercent = summary.TotalUnits == 0 ? 0 : summary.DeliveredUnits * 100d / summary.TotalUnits;
        var installedPercent = summary.TotalUnits == 0 ? 0 : summary.InstalledUnits * 100d / summary.TotalUnits;
        canvas.AddRoundedRect(.7, 5.2, 5.65, 1.12, "EFF4FF", "D8E7FF", .08);
        canvas.AddText(.95, 5.45, 1.2, .48, $"{deliveredPercent:0}%", 27, Blue, true, "l");
        canvas.AddText(2.15, 5.48, 3.85, .4, "of total quantity delivered", 15, Text, true, "l");
        canvas.AddRoundedRect(6.58, 5.2, 5.65, 1.12, "ECF8F0", "D1EEDD", .08);
        canvas.AddText(6.83, 5.45, 1.2, .48, $"{installedPercent:0}%", 27, Green, true, "l");
        canvas.AddText(8.03, 5.48, 3.85, .4, "of total quantity installed", 15, Text, true, "l");
    }

    private static void RenderGlobalFootprint(SlideCanvas canvas, FfcPresentationData data, byte[] mapImage)
    {
        AddSlideTitle(canvas, "Global footprint", "Country distribution by total quantity");
        canvas.AddImage(mapImage, .55, 1.28, 8.55, 5.62, "FFC global footprint map");
        canvas.AddRoundedRect(9.3, 1.28, 3.42, 5.62, CardBackground, Border, .08);
        canvas.AddText(9.58, 1.58, 2.8, .32, "COUNTRY / QTY", 12, Muted, true, "l");

        var rows = data.Countries.Take(9).ToArray();
        var y = 2.05;
        for (var index = 0; index < rows.Length; index++)
        {
            var country = rows[index];
            canvas.AddText(9.58, y, 2.12, .28, country.CountryName, 13, Text, true, "l");
            canvas.AddText(11.78, y, .52, .28, country.TotalUnits.ToString(CultureInfo.InvariantCulture), 13, Text, true, "r");
            canvas.AddText(12.18, y, .32, .28, "Qty", 8, Muted, false, "l");
            if (index < rows.Length - 1)
            {
                canvas.AddLine(9.58, y + .39, 12.46, y + .39, Border, .6);
            }
            y += .48;
        }

        if (data.Countries.Count > rows.Length)
        {
            canvas.AddText(9.58, 6.48, 2.8, .25, $"+ {data.Countries.Count - rows.Length} more countr{(data.Countries.Count - rows.Length == 1 ? "y" : "ies")}", 10, Muted, false, "l");
        }
    }

    private static void AddCountryUnitPositionSlides(
        List<SlidePlan> plans,
        FfcPresentationData data)
    {
        const int rowsPerSlide = 12;
        var countries = data.Countries.ToArray();
        if (countries.Length == 0)
        {
            plans.Add(new SlidePlan(false, (canvas, _, _) =>
            {
                AddSlideTitle(canvas, "Country-wise quantity status", "Installed, delivered and planned quantities by country");
                AddEmptyMessage(canvas, "No country data is available for this export scope.");
            }));
            return;
        }

        var pageCount = (int)Math.Ceiling(countries.Length / (double)rowsPerSlide);
        for (var page = 0; page < pageCount; page++)
        {
            var rows = countries.Skip(page * rowsPerSlide).Take(rowsPerSlide).ToArray();
            var capturedPage = page;
            plans.Add(new SlidePlan(false, (canvas, _, _) =>
                RenderCountryUnitPosition(canvas, data, rows, capturedPage + 1, pageCount)));
        }
    }

    private static void RenderCountryUnitPosition(
        SlideCanvas canvas,
        FfcPresentationData data,
        IReadOnlyList<FfcPresentationCountry> countries,
        int page,
        int totalPages)
    {
        AddSlideTitle(
            canvas,
            "Country-wise quantity status",
            totalPages > 1
                ? $"Installed, delivered and planned quantities by country · {page} of {totalPages}"
                : "Installed, delivered and planned quantities by country");
        if (countries.Count == 0)
        {
            AddEmptyMessage(canvas, "No country data is available for this export scope.");
            return;
        }

        var maximum = Math.Max(1, data.Countries.Max(country => country.TotalUnits));
        var y = 1.35;
        foreach (var country in countries)
        {
            canvas.AddText(.65, y, 2.4, .27, country.CountryName, 12, Text, true, "l");
            canvas.AddText(2.65, y, .36, .27, country.TotalUnits.ToString(CultureInfo.InvariantCulture), 11, Muted, true, "r");
            var barX = 3.2;
            var barWidth = 8.75;
            var activeWidth = country.TotalUnits / (double)maximum * barWidth;
            var installedWidth = country.TotalUnits == 0 ? 0 : activeWidth * country.InstalledUnits / country.TotalUnits;
            var deliveredWidth = country.TotalUnits == 0 ? 0 : activeWidth * country.DeliveredNotInstalledUnits / country.TotalUnits;
            var plannedWidth = Math.Max(0, activeWidth - installedWidth - deliveredWidth);
            canvas.AddRoundedRect(barX, y + .04, barWidth, .22, "E5EAF0", "E5EAF0", .03);
            if (installedWidth > 0) canvas.AddRect(barX, y + .04, installedWidth, .22, Green);
            if (deliveredWidth > 0) canvas.AddRect(barX + installedWidth, y + .04, deliveredWidth, .22, DeliveredBlue);
            if (plannedWidth > 0) canvas.AddRect(barX + installedWidth + deliveredWidth, y + .04, plannedWidth, .22, PlannedGray);
            canvas.AddText(12.08, y, .56, .27, $"{country.InstalledUnits}/{country.DeliveredNotInstalledUnits}/{country.PlannedUnits}", 9, Muted, false, "r");
            y += .43;
        }

        AddMetricLegend(canvas, .7, 6.65, "Installed", data.Summary.InstalledUnits, Green);
        AddMetricLegend(canvas, 4.4, 6.65, "Delivered", data.Summary.DeliveredNotInstalledUnits, DeliveredBlue);
        AddMetricLegend(canvas, 8.1, 6.65, "Planned", data.Summary.PlannedUnits, PlannedGray);
    }

    private static void AddMilestoneSlides(List<SlidePlan> plans, FfcPresentationData data)
    {
        var records = data.Countries
            .SelectMany(country => country.Records.Select(record => (Country: country, Record: record)))
            .OrderByDescending(item => item.Record.Year)
            .ThenBy(item => item.Country.CountryName, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        const int rowsPerSlide = 12;
        if (records.Length == 0)
        {
            plans.Add(new SlidePlan(false, (canvas, _, _) =>
            {
                AddSlideTitle(canvas, "IPA and GSL status", "Milestone status across country-year records");
                AddEmptyMessage(canvas, "No country-year records are available for this export scope.");
            }));
            return;
        }

        var pageCount = (int)Math.Ceiling(records.Length / (double)rowsPerSlide);
        for (var page = 0; page < pageCount; page++)
        {
            var pageRows = records.Skip(page * rowsPerSlide).Take(rowsPerSlide).ToArray();
            var capturedPage = page;
            plans.Add(new SlidePlan(false, (canvas, _, _) =>
                RenderMilestoneTable(canvas, data, pageRows, capturedPage + 1, pageCount)));
        }
    }

    private static void RenderMilestoneTable(
        SlideCanvas canvas,
        FfcPresentationData data,
        IReadOnlyList<(FfcPresentationCountry Country, FfcPresentationRecord Record)> rows,
        int page,
        int totalPages)
    {
        AddSlideTitle(
            canvas,
            "IPA and GSL status",
            totalPages > 1
                ? $"Milestone status across country-year records · {page} of {totalPages}"
                : "Milestone status across country-year records");

        var widths = new[] { 2.8, .75, 2.35, 2.35, .8, 3.25 };
        var tableRows = new List<IReadOnlyList<NativeTableCell>>
        {
            HeaderRow("COUNTRY", "YEAR", "IPA", "GSL", "QTY", "OVERALL STATUS")
        };
        var heights = new List<double> { .42 };

        for (var rowIndex = 0; rowIndex < rows.Count; rowIndex++)
        {
            var item = rows[rowIndex];
            var fill = rowIndex % 2 == 0 ? "FFFFFF" : "F7F9FC";
            tableRows.Add(new[]
            {
                Cell(item.Country.CountryName, 10, Text, true, "l", fill),
                Cell(item.Record.Year.ToString(CultureInfo.InvariantCulture), 10, Text, false, "ctr", fill),
                Cell(MilestoneShort(item.Record.IpaCompleted, item.Record.IpaDate), 9, MilestoneColor(item.Record.IpaCompleted, item.Record.IpaDate), true, "l", fill),
                Cell(MilestoneShort(item.Record.GslCompleted, item.Record.GslDate), 9, MilestoneColor(item.Record.GslCompleted, item.Record.GslDate), true, "l", fill),
                Cell(item.Record.TotalUnits.ToString(CultureInfo.InvariantCulture), 10, Text, true, "r", fill),
                Cell(Truncate(item.Record.OverallPosition, 58) ?? "—", 9, Muted, false, "l", fill)
            });
            heights.Add(.43);
        }

        canvas.AddNativeTable(.65, 1.25, widths, heights, tableRows, "IPA and GSL status table");

        if (data.IncludeMilestoneRemarks)
        {
            var remarks = rows
                .SelectMany(item => new[]
                {
                    string.IsNullOrWhiteSpace(item.Record.IpaRemarks) ? null : $"{item.Country.CountryName} {item.Record.Year} IPA: {item.Record.IpaRemarks}",
                    string.IsNullOrWhiteSpace(item.Record.GslRemarks) ? null : $"{item.Country.CountryName} {item.Record.Year} GSL: {item.Record.GslRemarks}"
                })
                .Where(value => value is not null)
                .Take(3)
                .ToArray();
            if (remarks.Length > 0)
            {
                canvas.AddText(.72, 6.72, 11.9, .34, string.Join("  ·  ", remarks.Select(remark => Truncate(remark, 115))), 8, Muted, false, "l");
            }
        }
    }

    private static void RenderOperationalFocus(SlideCanvas canvas, FfcPresentationData data)
    {
        AddSlideTitle(canvas, "Operational focus", "Portfolio areas requiring monitoring or follow-up");

        var planned = data.Countries
            .Where(country => country.PlannedUnits > 0)
            .OrderByDescending(country => country.PlannedUnits)
            .Take(5)
            .ToArray();
        var pendingMilestones = data.Countries
            .SelectMany(country => country.Records.Select(record => (Country: country, Record: record)))
            .Where(item => !item.Record.IpaCompleted || !item.Record.GslCompleted)
            .OrderByDescending(item => item.Record.TotalUnits)
            .Take(5)
            .ToArray();
        var partial = data.Countries
            .Where(country => country.DeliveredNotInstalledUnits > 0)
            .OrderByDescending(country => country.DeliveredNotInstalledUnits)
            .Take(5)
            .ToArray();

        AddFocusColumn(canvas, .65, 1.35, 3.9, 4.95, "PLANNED PIPELINE", Blue,
            planned.Select(country => $"{country.CountryName} · {country.PlannedUnits} planned").ToArray(),
            "No planned quantity in scope.");
        AddFocusColumn(canvas, 4.72, 1.35, 3.9, 4.95, "MILESTONE ATTENTION", Amber,
            pendingMilestones.Select(item =>
            {
                var pending = new List<string>();
                if (!item.Record.IpaCompleted) pending.Add("IPA");
                if (!item.Record.GslCompleted) pending.Add("GSL");
                return $"{item.Country.CountryName} {item.Record.Year} · {string.Join(" + ", pending)} pending";
            }).ToArray(),
            "No pending IPA/GSL milestones in scope.");
        AddFocusColumn(canvas, 8.79, 1.35, 3.9, 4.95, "AWAITING INSTALLATION", DeliveredBlue,
            partial.Select(country => $"{country.CountryName} · {country.DeliveredNotInstalledUnits} awaiting installation").ToArray(),
            "No delivered quantity awaiting installation.");
    }

    private static void RenderCountrySummary(
        SlideCanvas canvas,
        FfcPresentationData data,
        FfcPresentationCountry country)
    {
        AddSlideTitle(canvas, country.CountryName.ToUpperInvariant(), $"{country.IsoCode} · {country.RecordCount} record{Plural(country.RecordCount)} · {country.ProjectCount} project{Plural(country.ProjectCount)}");
        canvas.AddText(.68, 1.32, 2.0, .6, country.TotalUnits.ToString(CultureInfo.InvariantCulture), 32, Text, true, "l");
        canvas.AddText(1.98, 1.52, 1.25, .3, "TOTAL QUANTITY", 11, Muted, true, "l");
        AddSegmentedBar(canvas, 3.4, 1.48, 8.9, .33, country.InstalledUnits, country.DeliveredNotInstalledUnits, country.PlannedUnits);
        AddMetricLegend(canvas, 3.45, 1.95, "Installed", country.InstalledUnits, Green);
        AddMetricLegend(canvas, 6.75, 1.95, "Delivered", country.DeliveredNotInstalledUnits, DeliveredBlue);
        AddMetricLegend(canvas, 9.9, 1.95, "Planned", country.PlannedUnits, PlannedGray);

        var records = country.Records.Take(4).ToArray();
        var cardWidth = records.Length <= 2 ? 5.85 : 2.82;
        for (var index = 0; index < records.Length; index++)
        {
            var record = records[index];
            var x = .65 + index * (cardWidth + .2);
            canvas.AddRoundedRect(x, 2.65, cardWidth, 3.58, CardBackground, Border, .08);
            canvas.AddText(x + .22, 2.91, 1.2, .36, record.Year.ToString(CultureInfo.InvariantCulture), 22, Navy, true, "l");
            canvas.AddText(x + .22, 3.38, cardWidth - .44, .28, $"{record.ProjectCount} projects · Qty {record.TotalUnits}", 11, Muted, false, "l");
            AddMilestoneMini(canvas, x + .22, 3.9, "IPA", record.IpaCompleted, record.IpaDate);
            AddMilestoneMini(canvas, x + .22, 4.36, "GSL", record.GslCompleted, record.GslDate);
            canvas.AddText(x + .22, 4.95, cardWidth - .44, .26, "OVERALL STATUS", 9, Muted, true, "l");
            canvas.AddText(x + .22, 5.26, cardWidth - .44, .7, Truncate(record.OverallPosition, cardWidth > 4 ? 150 : 72) ?? "No overall status recorded.", 10, Text, false, "l");
        }

        if (country.Records.Count > records.Length)
        {
            canvas.AddText(.7, 6.5, 11.8, .25, $"{country.Records.Count - records.Length} earlier record{Plural(country.Records.Count - records.Length)} included in the appendix.", 9, Muted, false, "l");
        }
    }

    private static void AddProjectSlides(
        List<SlidePlan> plans,
        FfcPresentationData data,
        FfcPresentationCountry country)
    {
        var projects = country.Records
            .SelectMany(record => record.Projects.Select(project => (Record: record, Project: project)))
            .ToArray();
        if (projects.Length == 0)
        {
            return;
        }

        const int rowsPerSlide = 6;
        var pages = (int)Math.Ceiling(projects.Length / (double)rowsPerSlide);
        for (var page = 0; page < pages; page++)
        {
            var pageRows = projects.Skip(page * rowsPerSlide).Take(rowsPerSlide).ToArray();
            var capturedPage = page;
            plans.Add(new SlidePlan(false, (canvas, _, _) =>
                RenderProjectDetails(canvas, data, country, pageRows, capturedPage + 1, pages)));
        }
    }

    private static void RenderProjectDetails(
        SlideCanvas canvas,
        FfcPresentationData data,
        FfcPresentationCountry country,
        IReadOnlyList<(FfcPresentationRecord Record, FfcPresentationProject Project)> rows,
        int page,
        int pages)
    {
        AddSlideTitle(
            canvas,
            $"{country.CountryName} · project status",
            pages > 1 ? $"Project-level quantity and progress · {page} of {pages}" : "Project-level quantity and progress");

        var widths = data.IncludeProgress
            ? new[] { .8, 3.55, .65, 1.25, 5.68 }
            : new[] { .8, 5.2, .75, 1.45, 3.73 };
        var headers = new[] { "YEAR", "PROJECT", "QTY", "STATUS", data.IncludeProgress ? "CURRENT PROGRESS" : "CURRENT STAGE" };
        var tableRows = new List<IReadOnlyList<NativeTableCell>> { HeaderRow(headers) };
        var heights = new List<double> { .42 };

        foreach (var row in rows)
        {
            var narrative = data.IncludeProgress
                ? row.Project.CurrentProgress ?? row.Project.StageSummary
                : row.Project.StageSummary;

            tableRows.Add(new[]
            {
                Cell(row.Record.Year.ToString(CultureInfo.InvariantCulture), 10),
                Cell(Truncate(row.Project.Name, 66) ?? "FFC project", 11, Text, true),
                Cell(row.Project.Quantity.ToString(CultureInfo.InvariantCulture), 11, Text, true, "r"),
                Cell(PositionLabel(row.Project.Position), 10, PositionColor(row.Project.Position), true),
                Cell(Truncate(narrative, 150) ?? "No current progress recorded.", 10, Muted)
            });
            heights.Add(.82);
        }

        canvas.AddNativeTable(.65, 1.25, widths, heights, tableRows, $"{country.CountryName} project status table");
    }

    private static void AddAttachmentSlides(
        List<SlidePlan> plans,
        FfcPresentationData data,
        FfcPresentationCountry country)
    {
        var attachments = country.Records
            .SelectMany(record => record.Attachments.Select(attachment => (Record: record, Attachment: attachment)))
            .ToArray();
        const int rowsPerSlide = 10;
        var pages = (int)Math.Ceiling(attachments.Length / (double)rowsPerSlide);
        for (var page = 0; page < pages; page++)
        {
            var rows = attachments.Skip(page * rowsPerSlide).Take(rowsPerSlide).ToArray();
            var capturedPage = page;
            plans.Add(new SlidePlan(false, (canvas, _, _) =>
                RenderAttachmentRegister(canvas, country, rows, capturedPage + 1, pages)));
        }
    }

    private static void RenderAttachmentRegister(
        SlideCanvas canvas,
        FfcPresentationCountry country,
        IReadOnlyList<(FfcPresentationRecord Record, FfcPresentationAttachment Attachment)> rows,
        int page,
        int pages)
    {
        AddSlideTitle(canvas, $"{country.CountryName} · attachment register", pages > 1 ? $"Supporting files · {page} of {pages}" : "Supporting files");
        var widths = new[] { .8, 5.1, 1.15, 1.15, 2.3, 1.5 };
        var tableRows = new List<IReadOnlyList<NativeTableCell>>
        {
            HeaderRow("YEAR", "FILE / CAPTION", "KIND", "SIZE", "UPLOADED", "STATUS")
        };
        var heights = new List<double> { .42 };

        for (var rowIndex = 0; rowIndex < rows.Count; rowIndex++)
        {
            var row = rows[rowIndex];
            var fill = rowIndex % 2 == 0 ? "FFFFFF" : "F7F9FC";
            tableRows.Add(new[]
            {
                Cell(row.Record.Year.ToString(CultureInfo.InvariantCulture), 9, Text, false, "l", fill),
                Cell(Truncate(row.Attachment.DisplayName, 75) ?? "Supporting file", 9, Text, true, "l", fill),
                Cell(row.Attachment.Kind, 9, Muted, false, "l", fill),
                Cell(FormatBytes(row.Attachment.SizeBytes), 9, Muted, false, "l", fill),
                Cell(row.Attachment.UploadedAt.ToString("dd MMM yyyy", CultureInfo.InvariantCulture), 9, Muted, false, "l", fill),
                Cell("Available in PRISM", 8, Green, true, "l", fill)
            });
            heights.Add(.48);
        }

        canvas.AddNativeTable(.65, 1.25, widths, heights, tableRows, $"{country.CountryName} attachment register table");
    }

    private static void AddAppendixSlides(List<SlidePlan> plans, FfcPresentationData data)
    {
        var records = data.Countries
            .SelectMany(country => country.Records.Select(record => (Country: country, Record: record)))
            .OrderByDescending(item => item.Record.Year)
            .ThenBy(item => item.Country.CountryName, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        const int rowsPerSlide = 14;
        var pages = Math.Max(1, (int)Math.Ceiling(records.Length / (double)rowsPerSlide));
        for (var page = 0; page < pages; page++)
        {
            var rows = records.Skip(page * rowsPerSlide).Take(rowsPerSlide).ToArray();
            var capturedPage = page;
            plans.Add(new SlidePlan(false, (canvas, _, _) =>
                RenderAppendix(canvas, rows, capturedPage + 1, pages)));
        }
    }

    private static void RenderAppendix(
        SlideCanvas canvas,
        IReadOnlyList<(FfcPresentationCountry Country, FfcPresentationRecord Record)> rows,
        int page,
        int pages)
    {
        AddSlideTitle(canvas, "Appendix · consolidated record summary", pages > 1 ? $"Country-year reference · {page} of {pages}" : "Country-year reference");
        var widths = new[] { 2.65, .7, .8, .85, .85, .85, 1.35, 1.35, 3.05 };
        var tableRows = new List<IReadOnlyList<NativeTableCell>>
        {
            HeaderRow("COUNTRY", "YEAR", "PROJ", "INST", "DEL", "PLAN", "IPA", "GSL", "STATUS")
        };
        var heights = new List<double> { .4 };

        for (var rowIndex = 0; rowIndex < rows.Count; rowIndex++)
        {
            var item = rows[rowIndex];
            var fill = rowIndex % 2 == 0 ? "FFFFFF" : "F7F9FC";
            tableRows.Add(new[]
            {
                Cell(item.Country.CountryName, 8, Text, true, "l", fill),
                Cell(item.Record.Year.ToString(CultureInfo.InvariantCulture), 8, Muted, false, "l", fill),
                Cell(item.Record.ProjectCount.ToString(CultureInfo.InvariantCulture), 8, Muted, false, "r", fill),
                Cell(item.Record.InstalledUnits.ToString(CultureInfo.InvariantCulture), 8, Muted, false, "r", fill),
                Cell(item.Record.DeliveredNotInstalledUnits.ToString(CultureInfo.InvariantCulture), 8, Muted, false, "r", fill),
                Cell(item.Record.PlannedUnits.ToString(CultureInfo.InvariantCulture), 8, Muted, false, "r", fill),
                Cell(MilestoneShort(item.Record.IpaCompleted, item.Record.IpaDate), 8, Muted, false, "l", fill),
                Cell(MilestoneShort(item.Record.GslCompleted, item.Record.GslDate), 8, Muted, false, "l", fill),
                Cell(Truncate(item.Record.OverallPosition, 45) ?? "—", 8, Muted, false, "l", fill)
            });
            heights.Add(.39);
        }

        canvas.AddNativeTable(.65, 1.25, widths, heights, tableRows, "Consolidated country-year record summary table");
    }

    private static void AddStandardFooter(
        SlideCanvas canvas,
        FfcPresentationData data,
        int slideNumber,
        int slideCount,
        bool isCover)
    {
        if (!string.IsNullOrWhiteSpace(data.HandlingMarking))
        {
            canvas.AddText(
                .65,
                isCover ? .17 : .12,
                12.0,
                .24,
                data.HandlingMarking!.ToUpperInvariant(),
                9,
                isCover ? "FFD4D4" : Red,
                true,
                "ctr");
        }

        if (isCover)
        {
            return;
        }

        canvas.AddLine(.62, 7.08, 12.7, 7.08, Border, .6);
        canvas.AddText(.68, 7.15, 4.4, .18, "SIMULATOR DEVELOPMENT DIVISION · PRISM ERP", 7, Muted, true, "l");
        canvas.AddText(5.4, 7.15, 2.55, .18, data.PositionDate.ToString("dd MMM yyyy", CultureInfo.InvariantCulture), 7, Muted, false, "ctr");
        canvas.AddText(11.65, 7.15, .95, .18, $"{slideNumber} / {slideCount}", 7, Muted, false, "r");
    }

    private static void AddSlideTitle(SlideCanvas canvas, string title, string subtitle)
    {
        canvas.AddRect(0, 0, SlideWidth, SlideHeight, LightBackground);
        canvas.AddRect(0, 0, .12, SlideHeight, Blue);
        canvas.AddText(.65, .52, 11.5, .52, title, 25, Navy, true, "l");
        canvas.AddText(.67, 1.02, 11.4, .26, subtitle, 11, Muted, false, "l");
    }

    private static void AddSegmentedBar(
        SlideCanvas canvas,
        double x,
        double y,
        double width,
        double height,
        int installed,
        int delivered,
        int planned)
    {
        var total = installed + delivered + planned;
        canvas.AddRoundedRect(x, y, width, height, "E3E8EF", "E3E8EF", .05);
        if (total <= 0)
        {
            return;
        }
        var installedWidth = width * installed / total;
        var deliveredWidth = width * delivered / total;
        var plannedWidth = Math.Max(0, width - installedWidth - deliveredWidth);
        if (installedWidth > 0) canvas.AddRect(x, y, installedWidth, height, Green);
        if (deliveredWidth > 0) canvas.AddRect(x + installedWidth, y, deliveredWidth, height, DeliveredBlue);
        if (plannedWidth > 0) canvas.AddRect(x + installedWidth + deliveredWidth, y, plannedWidth, height, PlannedGray);
    }

    private static void AddMetricLegend(
        SlideCanvas canvas,
        double x,
        double y,
        string label,
        int value,
        string color)
    {
        canvas.AddRoundedRect(x, y + .04, .15, .15, color, color, .03);
        canvas.AddText(x + .25, y, 2.6, .25, $"{label}  {value}", 10, Text, true, "l");
    }

    private static void AddMilestoneCell(
        SlideCanvas canvas,
        double x,
        double y,
        double width,
        bool completed,
        DateOnly? date)
    {
        var label = MilestoneShort(completed, date);
        var color = !completed ? Muted : date.HasValue ? Green : Amber;
        canvas.AddText(x + .08, y + .09, width - .16, .23, label, 9, color, true, "l");
    }

    private static void AddMilestoneMini(
        SlideCanvas canvas,
        double x,
        double y,
        string label,
        bool completed,
        DateOnly? date)
    {
        canvas.AddText(x, y, .45, .25, label, 9, Muted, true, "l");
        canvas.AddText(x + .52, y, 2.0, .25, MilestoneShort(completed, date), 9, !completed ? Muted : date.HasValue ? Green : Amber, true, "l");
    }

    private static void AddFocusColumn(
        SlideCanvas canvas,
        double x,
        double y,
        double width,
        double height,
        string title,
        string accent,
        IReadOnlyList<string> items,
        string emptyText)
    {
        canvas.AddRoundedRect(x, y, width, height, CardBackground, Border, .08);
        canvas.AddRect(x, y, width, .12, accent);
        canvas.AddText(x + .25, y + .35, width - .5, .3, title, 11, accent, true, "l");
        var lines = items.Count == 0 ? new[] { emptyText } : items.Take(6).ToArray();
        var currentY = y + .92;
        foreach (var item in lines)
        {
            canvas.AddRoundedRect(x + .25, currentY + .04, .13, .13, accent, accent, .03);
            canvas.AddText(x + .5, currentY, width - .75, .5, Truncate(item, 72) ?? string.Empty, 11, Text, true, "l");
            currentY += .62;
        }
    }

    private static void AddEmptyMessage(SlideCanvas canvas, string message)
    {
        canvas.AddRoundedRect(1.15, 2.25, 11.0, 2.2, CardBackground, Border, .08);
        canvas.AddText(1.55, 3.0, 10.2, .6, message, 18, Muted, false, "ctr");
    }

    private static IReadOnlyList<NativeTableCell> HeaderRow(params string[] values)
        => values.Select(value => Cell(value, 8.5, "FFFFFF", true, IsNumericHeader(value) ? "r" : "l", Navy)).ToArray();

    private static bool IsNumericHeader(string value)
        => string.Equals(value, "QTY", StringComparison.OrdinalIgnoreCase)
           || string.Equals(value, "PROJ", StringComparison.OrdinalIgnoreCase)
           || string.Equals(value, "INST", StringComparison.OrdinalIgnoreCase)
           || string.Equals(value, "DEL", StringComparison.OrdinalIgnoreCase)
           || string.Equals(value, "PLAN", StringComparison.OrdinalIgnoreCase);

    private static NativeTableCell Cell(
        string? value,
        double fontSize = 9,
        string color = Text,
        bool bold = false,
        string align = "l",
        string fill = "FFFFFF")
        => new(value ?? string.Empty, fontSize, color, bold, align, fill);

    private static string MilestoneColor(bool completed, DateOnly? date)
        => !completed ? Muted : date.HasValue ? Green : Amber;

    private static string MilestoneShort(bool completed, DateOnly? date)
        => !completed
            ? "Pending"
            : date.HasValue
                ? $"Completed · {date.Value.ToString("dd MMM yyyy", CultureInfo.InvariantCulture)}"
                : "Completed · date missing";

    private static string PositionLabel(FfcUnitPosition position) => position switch
    {
        FfcUnitPosition.Installed => "Installed",
        FfcUnitPosition.DeliveredAwaitingInstallation => "Delivered",
        _ => "Planned"
    };

    private static string PositionColor(FfcUnitPosition position) => position switch
    {
        FfcUnitPosition.Installed => Green,
        FfcUnitPosition.DeliveredAwaitingInstallation => DeliveredBlue,
        _ => Muted
    };

    private static string FormatBytes(long bytes)
    {
        if (bytes < 1024) return $"{bytes} B";
        if (bytes < 1024 * 1024) return $"{bytes / 1024d:0.#} KB";
        return $"{bytes / (1024d * 1024d):0.#} MB";
    }

    private static double CoverTitleFontSize(string title)
        => title.Length switch
        {
            <= 42 => 34,
            <= 68 => 29,
            <= 92 => 25,
            _ => 22
        };

    private static string Plural(int count) => count == 1 ? string.Empty : "s";

    private static string? Truncate(string? value, int maximum)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var normalized = string.Join(" ", value.Split(' ', StringSplitOptions.RemoveEmptyEntries));
        return normalized.Length <= maximum ? normalized : normalized[..Math.Max(1, maximum - 1)] + "…";
    }

    private static SlideLayoutPart? FindBlankLayout(PresentationPart presentationPart)
        => presentationPart.SlideMasterParts
               .SelectMany(master => master.SlideLayoutParts)
               .FirstOrDefault(layout =>
                   string.Equals(layout.SlideLayout?.CommonSlideData?.Name?.Value, "Blank", StringComparison.OrdinalIgnoreCase))
           ?? presentationPart.SlideMasterParts.SelectMany(master => master.SlideLayoutParts).FirstOrDefault();

    private static void RemoveTemplateSlides(PresentationPart presentationPart)
    {
        var slideIdList = presentationPart.Presentation.SlideIdList;
        if (slideIdList is null)
        {
            return;
        }

        foreach (var slideId in slideIdList.Elements<SlideId>().ToList())
        {
            var relationshipId = slideId.RelationshipId?.Value;
            if (!string.IsNullOrWhiteSpace(relationshipId) && presentationPart.GetPartById(relationshipId) is SlidePart slidePart)
            {
                presentationPart.DeletePart(slidePart);
            }
            slideId.Remove();
        }
    }

    private sealed record NativeTableCell(
        string Value,
        double FontSize,
        string Color,
        bool Bold,
        string Align,
        string Fill);

    private sealed record SlidePlan(
        bool IsCover,
        Action<SlideCanvas, byte[], byte[]?> Render);

    private sealed class SlideCanvas
    {
        private readonly SlidePart _slidePart;
        private readonly List<string> _elements = new();
        private int _nextShapeId = 2;

        public SlideCanvas(SlidePart slidePart)
        {
            _slidePart = slidePart;
        }

        public void AddRect(
            double x,
            double y,
            double width,
            double height,
            string fill,
            string? line = null,
            double lineWidth = .75)
            => AddShape(x, y, width, height, fill, line, lineWidth, "rect", null, 0, Text, false, "l");

        public void AddRoundedRect(
            double x,
            double y,
            double width,
            double height,
            string fill,
            string? line,
            double radius)
            => AddShape(x, y, width, height, fill, line, .75, "roundRect", null, 0, Text, false, "l");

        public void AddLine(
            double x1,
            double y1,
            double x2,
            double y2,
            string color,
            double width)
        {
            var id = _nextShapeId++;
            _elements.Add($"""
<p:cxnSp>
  <p:nvCxnSpPr><p:cNvPr id="{id}" name="Line {id}"/><p:cNvCxnSpPr/><p:nvPr/></p:nvCxnSpPr>
  <p:spPr>
    <a:xfrm><a:off x="{Emu(x1)}" y="{Emu(y1)}"/><a:ext cx="{Emu(x2 - x1)}" cy="{Emu(y2 - y1)}"/></a:xfrm>
    <a:prstGeom prst="line"><a:avLst/></a:prstGeom>
    <a:ln w="{LineWidth(width)}"><a:solidFill><a:srgbClr val="{CleanColor(color)}"/></a:solidFill></a:ln>
  </p:spPr>
</p:cxnSp>
""");
        }

        public void AddText(
            double x,
            double y,
            double width,
            double height,
            string text,
            double fontSize,
            string color,
            bool bold,
            string align)
            => AddShape(x, y, width, height, null, null, 0, "rect", text, fontSize, color, bold, align);

        public void AddNativeTable(
            double x,
            double y,
            IReadOnlyList<double> widths,
            IReadOnlyList<double> heights,
            IReadOnlyList<IReadOnlyList<NativeTableCell>> rows,
            string name)
        {
            if (widths.Count == 0 || rows.Count == 0)
            {
                return;
            }

            if (heights.Count != rows.Count)
            {
                throw new ArgumentException("A native PowerPoint table requires one row height per row.", nameof(heights));
            }

            if (rows.Any(row => row.Count != widths.Count))
            {
                throw new ArgumentException("Every native PowerPoint table row must contain one cell per column.", nameof(rows));
            }

            var id = _nextShapeId++;
            var tableWidth = widths.Sum();
            var tableHeight = heights.Sum();
            var columnXml = string.Join(string.Empty, widths.Select(width => $"<a:gridCol w=\"{Emu(width)}\"/>"));
            var rowXml = new StringBuilder();

            for (var rowIndex = 0; rowIndex < rows.Count; rowIndex++)
            {
                rowXml.Append($"<a:tr h=\"{Emu(heights[rowIndex])}\">");
                foreach (var cell in rows[rowIndex])
                {
                    rowXml.Append($"""
<a:tc>
  {BuildTableTextBody(cell)}
  <a:tcPr marL="45720" marR="45720" marT="22860" marB="22860" anchor="ctr">
    <a:solidFill><a:srgbClr val="{CleanColor(cell.Fill)}"/></a:solidFill>
    {TableBorders()}
  </a:tcPr>
</a:tc>
""");
                }
                rowXml.Append("</a:tr>");
            }

            _elements.Add($"""
<p:graphicFrame>
  <p:nvGraphicFramePr><p:cNvPr id="{id}" name="{Escape(name)}"/><p:cNvGraphicFramePr><a:graphicFrameLocks noGrp="1"/></p:cNvGraphicFramePr><p:nvPr/></p:nvGraphicFramePr>
  <p:xfrm><a:off x="{Emu(x)}" y="{Emu(y)}"/><a:ext cx="{Emu(tableWidth)}" cy="{Emu(tableHeight)}"/></p:xfrm>
  <a:graphic>
    <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/table">
      <a:tbl>
        <a:tblPr firstRow="1" bandRow="1"/>
        <a:tblGrid>{columnXml}</a:tblGrid>
        {rowXml}
      </a:tbl>
    </a:graphicData>
  </a:graphic>
</p:graphicFrame>
""");
        }

        public void AddImage(
            byte[] content,
            double x,
            double y,
            double width,
            double height,
            string name)
        {
            var imagePart = _slidePart.AddImagePart(ImagePartType.Png);
            using (var imageStream = new MemoryStream(content, writable: false))
            {
                imagePart.FeedData(imageStream);
            }
            var relationshipId = _slidePart.GetIdOfPart(imagePart);
            var id = _nextShapeId++;
            _elements.Add($"""
<p:pic>
  <p:nvPicPr><p:cNvPr id="{id}" name="{Escape(name)}"/><p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr><p:nvPr/></p:nvPicPr>
  <p:blipFill><a:blip r:embed="{relationshipId}"/><a:stretch><a:fillRect/></a:stretch></p:blipFill>
  <p:spPr><a:xfrm><a:off x="{Emu(x)}" y="{Emu(y)}"/><a:ext cx="{Emu(width)}" cy="{Emu(height)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:ln><a:noFill/></a:ln></p:spPr>
</p:pic>
""");
        }

        public void Commit()
        {
            var xml = $"""
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      {string.Join(Environment.NewLine, _elements)}
    </p:spTree>
  </p:cSld>
  <p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>
""";
            using var stream = new MemoryStream(Encoding.UTF8.GetBytes(xml));
            _slidePart.FeedData(stream);
        }

        private void AddShape(
            double x,
            double y,
            double width,
            double height,
            string? fill,
            string? line,
            double lineWidth,
            string geometry,
            string? text,
            double fontSize,
            string color,
            bool bold,
            string align)
        {
            var id = _nextShapeId++;
            var fillXml = string.IsNullOrWhiteSpace(fill)
                ? "<a:noFill/>"
                : $"<a:solidFill><a:srgbClr val=\"{CleanColor(fill)}\"/></a:solidFill>";
            var lineXml = string.IsNullOrWhiteSpace(line)
                ? "<a:ln><a:noFill/></a:ln>"
                : $"<a:ln w=\"{LineWidth(lineWidth)}\"><a:solidFill><a:srgbClr val=\"{CleanColor(line)}\"/></a:solidFill></a:ln>";
            var textXml = text is null
                ? string.Empty
                : BuildTextBody(text, fontSize, color, bold, align);

            _elements.Add($"""
<p:sp>
  <p:nvSpPr><p:cNvPr id="{id}" name="Shape {id}"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr>
  <p:spPr>
    <a:xfrm><a:off x="{Emu(x)}" y="{Emu(y)}"/><a:ext cx="{Emu(width)}" cy="{Emu(height)}"/></a:xfrm>
    <a:prstGeom prst="{geometry}"><a:avLst/></a:prstGeom>
    {fillXml}{lineXml}
  </p:spPr>
  {textXml}
</p:sp>
""");
        }

        private static string BuildTableTextBody(NativeTableCell cell)
        {
            var alignment = cell.Align switch
            {
                "ctr" => "ctr",
                "r" => "r",
                _ => "l"
            };

            var paragraphs = cell.Value
                .Replace("\r", string.Empty, StringComparison.Ordinal)
                .Split('\n')
                .Select(line => $"""
<a:p><a:pPr algn="{alignment}"/><a:r><a:rPr lang="en-US" sz="{FontSize(cell.FontSize)}" b="{(cell.Bold ? 1 : 0)}"><a:solidFill><a:srgbClr val="{CleanColor(cell.Color)}"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t xml:space="preserve">{Escape(line)}</a:t></a:r><a:endParaRPr lang="en-US" sz="{FontSize(cell.FontSize)}"/></a:p>
""");

            return $"""
<a:txBody><a:bodyPr wrap="square" lIns="0" rIns="0" tIns="0" bIns="0" anchor="ctr"/><a:lstStyle/>{string.Join(string.Empty, paragraphs)}</a:txBody>
""";
        }

        private static string TableBorders()
        {
            var line = $"<a:solidFill><a:srgbClr val=\"{Border}\"/></a:solidFill><a:prstDash val=\"solid\"/>";
            return $"""
<a:lnL w="6350">{line}</a:lnL>
<a:lnR w="6350">{line}</a:lnR>
<a:lnT w="6350">{line}</a:lnT>
<a:lnB w="6350">{line}</a:lnB>
""";
        }

        private static string BuildTextBody(
            string text,
            double fontSize,
            string color,
            bool bold,
            string align)
        {
            var alignment = align switch
            {
                "ctr" => "ctr",
                "r" => "r",
                _ => "l"
            };
            var paragraphs = text
                .Replace("\r", string.Empty, StringComparison.Ordinal)
                .Split('\n')
                .Select(line => $"""
<a:p><a:pPr algn="{alignment}"/><a:r><a:rPr lang="en-US" sz="{FontSize(fontSize)}" b="{(bold ? 1 : 0)}"><a:solidFill><a:srgbClr val="{CleanColor(color)}"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t xml:space="preserve">{Escape(line)}</a:t></a:r><a:endParaRPr lang="en-US" sz="{FontSize(fontSize)}"/></a:p>
""");
            return $"""
<p:txBody><a:bodyPr wrap="square" lIns="45720" rIns="45720" tIns="22860" bIns="22860" anchor="ctr"/><a:lstStyle/>{string.Join(string.Empty, paragraphs)}</p:txBody>
""";
        }

        private static long Emu(double inches) => (long)Math.Round(inches * 914400d);
        private static long LineWidth(double points) => (long)Math.Round(points * 12700d);
        private static int FontSize(double points) => (int)Math.Round(points * 100d);
        private static string Escape(string value) => SecurityElement.Escape(value) ?? string.Empty;
        private static string CleanColor(string value) => value.Trim().TrimStart('#').ToUpperInvariant();
    }
}
