// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251004120000_AddNotificationDispatches")]
    partial class AddNotificationDispatches
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new ApplicationDbContextModelSnapshot().BuildModelSnapshot(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
