// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250914000000_NormalizeEventCategories")]
    partial class NormalizeEventCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // No model changes; existing snapshot remains valid.
        }
    }
}
