// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223120000_AddFfcSimulators")]
    partial class AddFfcSimulators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new Snapshot().PopulateModel(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class Snapshot : ApplicationDbContextModelSnapshot
        {
            protected override void BuildModel(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);

            public void PopulateModel(ModelBuilder modelBuilder) => BuildModel(modelBuilder);
        }
    }
}
