// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251101000000_ProjectLegacyImport")]
    partial class ProjectLegacyImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new Snapshot().Build(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class Snapshot : ApplicationDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder) => BuildModel(modelBuilder);
        }
    }
}
