using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ProjectManagement.Migrations
{
    /// <inheritdoc />
    public partial class DocRepo_All : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "DocumentCategories" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" character varying(120) NOT NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "SortOrder" integer NOT NULL DEFAULT 100
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "OfficeCategories" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" character varying(120) NOT NULL,
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "SortOrder" integer NOT NULL DEFAULT 100
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Tags" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" character varying(64) NOT NULL,
                    "NormalizedName" character varying(64) NOT NULL
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Documents" (
                    "Id" uuid PRIMARY KEY,
                    "Subject" character varying(256) NOT NULL,
                    "ReceivedFrom" character varying(256),
                    "DocumentDate" date,
                    "OfficeCategoryId" integer NOT NULL,
                    "DocumentCategoryId" integer NOT NULL,
                    "OriginalFileName" character varying(260) NOT NULL,
                    "FileSizeBytes" bigint NOT NULL,
                    "Sha256" character varying(64) NOT NULL,
                    "StoragePath" character varying(260) NOT NULL,
                    "MimeType" character varying(64) NOT NULL DEFAULT 'application/pdf',
                    "IsActive" boolean NOT NULL DEFAULT TRUE,
                    "OcrStatus" integer NOT NULL DEFAULT 0,
                    "OcrFailureReason" character varying(512),
                    "OcrLastTriedUtc" timestamp with time zone,
                    "ExtractedText" text,
                    "CreatedByUserId" character varying(64) NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedByUserId" character varying(64),
                    "UpdatedAtUtc" timestamp with time zone,
                    CONSTRAINT "FK_Documents_DocumentCategories_DocumentCategoryId" FOREIGN KEY ("DocumentCategoryId") REFERENCES "DocumentCategories" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_Documents_OfficeCategories_OfficeCategoryId" FOREIGN KEY ("OfficeCategoryId") REFERENCES "OfficeCategories" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "DocumentDeleteRequests" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "DocumentId" uuid NOT NULL,
                    "RequestedByUserId" character varying(450) NOT NULL,
                    "RequestedAtUtc" timestamp with time zone NOT NULL,
                    "Reason" character varying(512) NOT NULL,
                    "ApprovedByUserId" character varying(450),
                    "ApprovedAtUtc" timestamp with time zone,
                    CONSTRAINT "FK_DocumentDeleteRequests_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "DocumentTags" (
                    "DocumentId" uuid NOT NULL,
                    "TagId" integer NOT NULL,
                    CONSTRAINT "PK_DocumentTags" PRIMARY KEY ("DocumentId", "TagId"),
                    CONSTRAINT "FK_DocumentTags_Documents_DocumentId" FOREIGN KEY ("DocumentId") REFERENCES "Documents" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_DocumentTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "DocRepoAudits" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "DocumentId" uuid,
                    "EventType" character varying(64) NOT NULL,
                    "ActorUserId" character varying(450) NOT NULL,
                    "OccurredAtUtc" timestamp with time zone NOT NULL,
                    "DetailsJson" jsonb NOT NULL
                );
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DocumentCategories_Name" ON "DocumentCategories" ("Name");
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_OfficeCategories_Name" ON "OfficeCategories" ("Name");
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tags_Name" ON "Tags" ("Name");
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Tags_NormalizedName" ON "Tags" ("NormalizedName");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_Documents_DocumentCategoryId" ON "Documents" ("DocumentCategoryId");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_Documents_DocumentDate" ON "Documents" ("DocumentDate");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_Documents_OfficeCategoryId" ON "Documents" ("OfficeCategoryId");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_Documents_OfficeCategoryId_DocumentCategoryId" ON "Documents" ("OfficeCategoryId", "DocumentCategoryId");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_Documents_ReceivedFrom" ON "Documents" ("ReceivedFrom");
                """);

            migrationBuilder.Sql(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Documents_Sha256" ON "Documents" ("Sha256");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_Documents_Subject" ON "Documents" ("Subject");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_DocumentTags_TagId" ON "DocumentTags" ("TagId");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_DocumentTags_TagId_DocumentId" ON "DocumentTags" ("TagId", "DocumentId");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_DeleteReq_Doc_PendingFirst" ON "DocumentDeleteRequests" ("DocumentId", "ApprovedAtUtc");
                """);

            migrationBuilder.Sql(
                """
                CREATE INDEX IF NOT EXISTS "IX_DocRepoAudits_Doc_Occurred" ON "DocRepoAudits" ("DocumentId", "OccurredAtUtc");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"DocRepoAudits\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"DocumentDeleteRequests\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"DocumentTags\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Documents\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Tags\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"DocumentCategories\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"OfficeCategories\";");
        }
    }
}
