// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915110000_AddUserDefaultRole")]
    partial class AddUserDefaultRole
    {
        // SECTION: Model snapshot bridge
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new SnapshotInvoker().Build(modelBuilder);
        }

        // SECTION: Snapshot invoker helper
        private sealed class SnapshotInvoker : ApplicationDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
#pragma warning disable 612, 618
                BuildModel(modelBuilder);
#pragma warning restore 612, 618
            }
        }
    }
}
