// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718123000_AddProjectDocumentDocRepoLink")]
    partial class AddProjectDocumentDocRepoLink
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new SnapshotInvoker().Build(modelBuilder);
        }

        private sealed class SnapshotInvoker : ApplicationDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                BuildModel(modelBuilder);
            }
        }
    }
}
