using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261125140000_AddActionTasks")]
    public class AddActionTasks : Migration
    {
        // SECTION: Apply Action Tracker schema
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // SECTION: PostgreSQL idempotent schema apply (supports partially bootstrapped databases)
            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTasks" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "Title" character varying(200) NOT NULL,
                        "Description" character varying(4000) NOT NULL,
                        "CreatedByUserId" character varying(450) NOT NULL,
                        "AssignedToUserId" character varying(450) NOT NULL,
                        "CreatedByRole" character varying(64) NOT NULL,
                        "AssignedToRole" character varying(64) NOT NULL,
                        "AssignedOn" timestamp with time zone NOT NULL,
                        "DueDate" date NOT NULL,
                        "Priority" character varying(24) NOT NULL,
                        "Status" character varying(32) NOT NULL,
                        "SubmittedOn" timestamp with time zone NULL,
                        "ClosedOn" timestamp with time zone NULL,
                        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                        CONSTRAINT "PK_ActionTasks" PRIMARY KEY ("Id")
                    );
                    """);

                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTaskAuditLogs" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "TaskId" integer NOT NULL,
                        "ActionType" character varying(64) NOT NULL,
                        "PerformedByUserId" character varying(450) NOT NULL,
                        "PerformedByRole" character varying(64) NOT NULL,
                        "PerformedAt" timestamp with time zone NOT NULL,
                        "OldValue" text NULL,
                        "NewValue" text NULL,
                        "Remarks" character varying(2000) NULL,
                        CONSTRAINT "PK_ActionTaskAuditLogs" PRIMARY KEY ("Id")
                    );
                    """);

                migrationBuilder.Sql(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'FK_ActionTaskAuditLogs_ActionTasks_TaskId'
                        ) THEN
                            ALTER TABLE "ActionTaskAuditLogs"
                            ADD CONSTRAINT "FK_ActionTaskAuditLogs_ActionTasks_TaskId"
                            FOREIGN KEY ("TaskId")
                            REFERENCES "ActionTasks" ("Id")
                            ON DELETE CASCADE;
                        END IF;
                    END $$;
                    """);

                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAuditLogs_PerformedByUserId" ON "ActionTaskAuditLogs" ("PerformedByUserId");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAuditLogs_TaskId_PerformedAt" ON "ActionTaskAuditLogs" ("TaskId", "PerformedAt");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_AssignedToUserId_Status" ON "ActionTasks" ("AssignedToUserId", "Status");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_DueDate_Status" ON "ActionTasks" ("DueDate", "Status");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_IsDeleted" ON "ActionTasks" ("IsDeleted");""");
                return;
            }

            migrationBuilder.CreateTable(
                name: "ActionTasks",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: false),
                    CreatedByUserId = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false),
                    AssignedToUserId = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false),
                    CreatedByRole = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    AssignedToRole = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    AssignedOn = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    DueDate = table.Column<DateTime>(type: "date", nullable: false),
                    Priority = table.Column<string>(type: "character varying(24)", maxLength: 24, nullable: false),
                    Status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    SubmittedOn = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    ClosedOn = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ActionTasks", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ActionTaskAuditLogs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    TaskId = table.Column<int>(type: "integer", nullable: false),
                    ActionType = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    PerformedByUserId = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false),
                    PerformedByRole = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    PerformedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    OldValue = table.Column<string>(type: "text", nullable: true),
                    NewValue = table.Column<string>(type: "text", nullable: true),
                    Remarks = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ActionTaskAuditLogs", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ActionTaskAuditLogs_ActionTasks_TaskId",
                        column: x => x.TaskId,
                        principalTable: "ActionTasks",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ActionTaskAuditLogs_PerformedByUserId",
                table: "ActionTaskAuditLogs",
                column: "PerformedByUserId");

            migrationBuilder.CreateIndex(
                name: "IX_ActionTaskAuditLogs_TaskId_PerformedAt",
                table: "ActionTaskAuditLogs",
                columns: new[] { "TaskId", "PerformedAt" });

            migrationBuilder.CreateIndex(
                name: "IX_ActionTasks_AssignedToUserId_Status",
                table: "ActionTasks",
                columns: new[] { "AssignedToUserId", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_ActionTasks_DueDate_Status",
                table: "ActionTasks",
                columns: new[] { "DueDate", "Status" });

            migrationBuilder.CreateIndex(
                name: "IX_ActionTasks_IsDeleted",
                table: "ActionTasks",
                column: "IsDeleted");
        }

        // SECTION: Revert Action Tracker schema
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // SECTION: PostgreSQL idempotent schema revert
            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql("""DROP TABLE IF EXISTS "ActionTaskAuditLogs";""");
                migrationBuilder.Sql("""DROP TABLE IF EXISTS "ActionTasks";""");
                return;
            }

            migrationBuilder.DropTable(name: "ActionTaskAuditLogs");
            migrationBuilder.DropTable(name: "ActionTasks");
        }
    }
}
