using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430160000_ActionTrackerMigrationOrderRepair")]
    public class ActionTrackerMigrationOrderRepairBootstrap : Migration
    {
        // SECTION: Action Tracker dependency bootstrap strategy
        // Action Tracker collaboration and concurrency migrations were timestamped before the
        // original ActionTasks table migration. This idempotent bootstrap creates only the
        // prerequisite table so fresh databases and older databases can converge safely.

        // SECTION: Create prerequisite ActionTasks table before dependent migrations
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // SECTION: PostgreSQL idempotent prerequisite creation
            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTasks" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "Title" character varying(200) NOT NULL,
                        "Description" character varying(4000) NOT NULL,
                        "CreatedByUserId" character varying(450) NOT NULL,
                        "AssignedToUserId" character varying(450) NOT NULL,
                        "CreatedByRole" character varying(64) NOT NULL,
                        "AssignedToRole" character varying(64) NOT NULL,
                        "AssignedOn" timestamp with time zone NOT NULL,
                        "DueDate" date NOT NULL,
                        "Priority" character varying(24) NOT NULL,
                        "Status" character varying(32) NOT NULL,
                        "SubmittedOn" timestamp with time zone NULL,
                        "ClosedOn" timestamp with time zone NULL,
                        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                        CONSTRAINT "PK_ActionTasks" PRIMARY KEY ("Id")
                    );
                    """);

                return;
            }

            // SECTION: Provider-neutral prerequisite creation
            migrationBuilder.CreateTable(
                name: "ActionTasks",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: false),
                    CreatedByUserId = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false),
                    AssignedToUserId = table.Column<string>(type: "character varying(450)", maxLength: 450, nullable: false),
                    CreatedByRole = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    AssignedToRole = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    AssignedOn = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    DueDate = table.Column<DateTime>(type: "date", nullable: false),
                    Priority = table.Column<string>(type: "character varying(24)", maxLength: 24, nullable: false),
                    Status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    SubmittedOn = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    ClosedOn = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    IsDeleted = table.Column<bool>(type: "boolean", nullable: false, defaultValue: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ActionTasks", x => x.Id);
                });
        }

        // SECTION: Remove prerequisite table after dependent migrations roll back
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // SECTION: PostgreSQL idempotent prerequisite removal
            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql("""DROP TABLE IF EXISTS "ActionTasks";""");
                return;
            }

            // SECTION: Provider-neutral prerequisite removal
            migrationBuilder.DropTable(name: "ActionTasks");
        }
    }
}
