using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20261216200000_AddSearchV2Foundation")]
public sealed class AddSearchV2Foundation : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        if (!string.Equals(ActiveProvider, "Npgsql.EntityFrameworkCore.PostgreSQL", StringComparison.Ordinal))
        {
            throw new NotSupportedException("Search V2 requires PostgreSQL.");
        }

        migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS pg_trgm;");
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "SearchEntries" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Generation" bigint NOT NULL,
                "EntityType" varchar(64) NOT NULL,
                "EntityKey" varchar(128) NOT NULL,
                "CanonicalEntityType" varchar(64) NOT NULL,
                "CanonicalEntityKey" varchar(128) NOT NULL,
                "ParentProjectId" integer NULL,
                "SourceModule" varchar(96) NOT NULL,
                "ResultCategory" varchar(48) NOT NULL,
                "Title" text NOT NULL,
                "NormalizedTitle" text NOT NULL,
                "Subtitle" text NULL,
                "CanonicalUrl" text NOT NULL,
                "IdentifierText" text NULL,
                "AliasText" text NULL,
                "StructuredText" text NULL,
                "NarrativeText" text NULL,
                "FuzzyText" text NOT NULL,
                "SearchVectorSimple" tsvector NULL,
                "SearchVectorEnglish" tsvector NULL,
                "Status" varchar(96) NULL,
                "FileType" varchar(32) NULL,
                "EventDateUtc" timestamptz NULL,
                "UpdatedAtUtc" timestamptz NOT NULL,
                "VisibilityMode" smallint NOT NULL DEFAULT 0,
                "RequiredPolicy" varchar(160) NULL,
                "OwnerUserId" varchar(450) NULL,
                "IndexVersion" integer NOT NULL,
                "IndexedAtUtc" timestamptz NOT NULL DEFAULT NOW(),
                "MetadataJson" jsonb NOT NULL DEFAULT '{}'::jsonb,
                CONSTRAINT "UQ_SearchEntries_Generation_Entity" UNIQUE ("Generation", "EntityType", "EntityKey")
            );

            CREATE TABLE IF NOT EXISTS "SearchEntryTerms" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SearchEntryId" bigint NOT NULL REFERENCES "SearchEntries"("Id") ON DELETE CASCADE,
                "Term" text NOT NULL,
                "NormalizedTerm" text NOT NULL,
                "TermType" varchar(24) NOT NULL,
                CONSTRAINT "UQ_SearchEntryTerms" UNIQUE ("SearchEntryId", "TermType", "NormalizedTerm")
            );

            CREATE TABLE IF NOT EXISTS "SearchEntryPrincipals" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SearchEntryId" bigint NOT NULL REFERENCES "SearchEntries"("Id") ON DELETE CASCADE,
                "PrincipalType" varchar(16) NOT NULL,
                "PrincipalValue" varchar(450) NOT NULL,
                CONSTRAINT "UQ_SearchEntryPrincipals" UNIQUE ("SearchEntryId", "PrincipalType", "PrincipalValue")
            );

            CREATE TABLE IF NOT EXISTS "SearchAliases" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Alias" varchar(160) NOT NULL,
                "NormalizedAlias" varchar(160) NOT NULL,
                "Expansion" varchar(300) NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT TRUE,
                CONSTRAINT "UQ_SearchAliases_Alias_Expansion" UNIQUE ("NormalizedAlias", "Expansion")
            );

            CREATE TABLE IF NOT EXISTS "SearchIndexWorkItems" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "EntityType" varchar(64) NOT NULL,
                "EntityKey" varchar(128) NOT NULL,
                "RequestedAtUtc" timestamptz NOT NULL DEFAULT NOW(),
                "StartedAtUtc" timestamptz NULL,
                "NextAttemptAtUtc" timestamptz NOT NULL DEFAULT NOW(),
                "Status" smallint NOT NULL DEFAULT 0,
                "RetryCount" integer NOT NULL DEFAULT 0,
                "LastError" varchar(4000) NULL,
                CONSTRAINT "UQ_SearchIndexWorkItems_Entity" UNIQUE ("EntityType", "EntityKey")
            );

            CREATE TABLE IF NOT EXISTS "SearchIndexState" (
                "Id" integer PRIMARY KEY,
                "ActiveGeneration" bigint NOT NULL DEFAULT 0,
                "IndexVersion" integer NOT NULL DEFAULT 0,
                "LastFullRebuildUtc" timestamptz NULL,
                "LastReconciliationUtc" timestamptz NULL,
                "LastError" varchar(4000) NULL
            );

            INSERT INTO "SearchIndexState" ("Id", "ActiveGeneration", "IndexVersion")
            VALUES (1, 0, 0)
            ON CONFLICT ("Id") DO NOTHING;

            CREATE TABLE IF NOT EXISTS "SearchQueryLogs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Query" text NOT NULL,
                "SearchedAtUtc" timestamptz NOT NULL,
                "UserContextCategory" varchar(1000) NULL,
                "ResultCount" bigint NOT NULL,
                "LatencyMs" bigint NOT NULL,
                "Engine" varchar(32) NOT NULL,
                "ZeroResult" boolean NOT NULL,
                "CorrectionOffered" text NULL
            );

            CREATE TABLE IF NOT EXISTS "SearchClickLogs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Query" text NOT NULL,
                "ClickedAtUtc" timestamptz NOT NULL,
                "EntityType" varchar(64) NOT NULL,
                "EntityKey" varchar(128) NOT NULL,
                "SelectedRank" integer NOT NULL,
                "SourceModule" varchar(96) NOT NULL
            );

            CREATE TABLE IF NOT EXISTS "SearchShadowComparisons" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Query" text NOT NULL,
                "ComparedAtUtc" timestamptz NOT NULL,
                "LegacyTopJson" jsonb NOT NULL,
                "V2TopJson" jsonb NOT NULL
            );

            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_Generation" ON "SearchEntries" ("Generation");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_Canonical" ON "SearchEntries" ("Generation", "CanonicalEntityType", "CanonicalEntityKey");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_ParentProjectId" ON "SearchEntries" ("Generation", "ParentProjectId");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_SourceModule" ON "SearchEntries" ("Generation", "SourceModule");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_ResultCategory" ON "SearchEntries" ("Generation", "ResultCategory");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_RequiredPolicy" ON "SearchEntries" ("Generation", "RequiredPolicy");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_IndexVersion" ON "SearchEntries" ("IndexVersion", "Generation");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_SearchVectorSimple" ON "SearchEntries" USING GIN ("SearchVectorSimple");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_SearchVectorEnglish" ON "SearchEntries" USING GIN ("SearchVectorEnglish");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_NormalizedTitleTrgm" ON "SearchEntries" USING GIN ("NormalizedTitle" gin_trgm_ops);
            CREATE INDEX IF NOT EXISTS "IX_SearchEntries_FuzzyTextTrgm" ON "SearchEntries" USING GIN ("FuzzyText" gin_trgm_ops);
            CREATE INDEX IF NOT EXISTS "IX_SearchEntryTerms_Normalized" ON "SearchEntryTerms" ("TermType", "NormalizedTerm", "SearchEntryId");
            CREATE INDEX IF NOT EXISTS "IX_SearchEntryPrincipals_Value" ON "SearchEntryPrincipals" ("PrincipalType", "PrincipalValue", "SearchEntryId");
            CREATE INDEX IF NOT EXISTS "IX_SearchIndexWorkItems_Pending" ON "SearchIndexWorkItems" ("Status", "NextAttemptAtUtc", "RequestedAtUtc");
            CREATE INDEX IF NOT EXISTS "IX_SearchQueryLogs_Date" ON "SearchQueryLogs" ("SearchedAtUtc");
            CREATE INDEX IF NOT EXISTS "IX_SearchClickLogs_Date" ON "SearchClickLogs" ("ClickedAtUtc");
            CREATE INDEX IF NOT EXISTS "IX_SearchShadowComparisons_Date" ON "SearchShadowComparisons" ("ComparedAtUtc");
            """);

        migrationBuilder.Sql("""
            CREATE OR REPLACE FUNCTION search_v2_refresh_vectors()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            BEGIN
                NEW."SearchVectorSimple" :=
                    setweight(to_tsvector('simple', COALESCE(NEW."Title", '')), 'A') ||
                    setweight(to_tsvector('simple', COALESCE(NEW."IdentifierText", '')), 'A') ||
                    setweight(to_tsvector('simple', COALESCE(NEW."AliasText", '')), 'B') ||
                    setweight(to_tsvector('simple', COALESCE(NEW."StructuredText", '')), 'B') ||
                    setweight(to_tsvector('simple', COALESCE(NEW."Subtitle", '')), 'C');

                NEW."SearchVectorEnglish" :=
                    setweight(to_tsvector('english', COALESCE(NEW."Title", '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW."StructuredText", '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW."NarrativeText", '')), 'C');
                RETURN NEW;
            END;
            $$;

            DROP TRIGGER IF EXISTS "TR_SearchEntries_RefreshVectors" ON "SearchEntries";
            CREATE TRIGGER "TR_SearchEntries_RefreshVectors"
            BEFORE INSERT OR UPDATE OF "Title", "IdentifierText", "AliasText", "StructuredText", "NarrativeText", "Subtitle"
            ON "SearchEntries"
            FOR EACH ROW EXECUTE FUNCTION search_v2_refresh_vectors();
            """);

        migrationBuilder.Sql("""
            INSERT INTO "SearchAliases" ("Alias", "NormalizedAlias", "Expansion") VALUES
                ('Trg', 'trg', 'Training'),
                ('ToT', 'tot', 'Transfer of Technology'),
                ('AoN', 'aon', 'Approval of Necessity'),
                ('IPR', 'ipr', 'Intellectual Property'),
                ('ARPP', 'arpp', 'Annual Rolled-on Procurement Plan'),
                ('high-tech', 'high tech', 'hightech')
            ON CONFLICT DO NOTHING;
            """);

        migrationBuilder.Sql("""
            CREATE OR REPLACE FUNCTION search_v2_enqueue(entity_type text, entity_key text)
            RETURNS void
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF entity_key IS NULL OR btrim(entity_key) = '' THEN
                    RETURN;
                END IF;

                INSERT INTO "SearchIndexWorkItems" ("EntityType", "EntityKey", "RequestedAtUtc", "Status", "RetryCount", "NextAttemptAtUtc")
                VALUES (entity_type, entity_key, NOW(), 0, 0, NOW())
                ON CONFLICT ("EntityType", "EntityKey") DO UPDATE SET
                    "RequestedAtUtc" = NOW(),
                    "Status" = 0,
                    "RetryCount" = 0,
                    "LastError" = NULL,
                    "NextAttemptAtUtc" = NOW();
            END;
            $$;

            CREATE OR REPLACE FUNCTION search_v2_enqueue_row()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $$
            DECLARE
                new_key text;
                old_key text;
            BEGIN
                IF TG_OP <> 'DELETE' THEN
                    new_key := to_jsonb(NEW) ->> TG_ARGV[1];
                    PERFORM search_v2_enqueue(TG_ARGV[0], new_key);
                END IF;

                IF TG_OP <> 'INSERT' THEN
                    old_key := to_jsonb(OLD) ->> TG_ARGV[1];
                    IF old_key IS DISTINCT FROM new_key THEN
                        PERFORM search_v2_enqueue(TG_ARGV[0], old_key);
                    END IF;
                END IF;

                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$;

            CREATE OR REPLACE FUNCTION search_v2_install_trigger(
                table_name text,
                trigger_name text,
                entity_type text,
                key_column text)
            RETURNS void
            LANGUAGE plpgsql
            AS $$
            BEGIN
                IF to_regclass(format('%I', table_name)) IS NULL THEN
                    RETURN;
                END IF;

                EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', trigger_name, table_name);
                EXECUTE format(
                    'CREATE TRIGGER %I AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION search_v2_enqueue_row(%L, %L)',
                    trigger_name, table_name, entity_type, key_column);
            END;
            $$;

            SELECT search_v2_install_trigger('Projects', 'TR_SearchV2_Projects', 'Project', 'Id');
            SELECT search_v2_install_trigger('ProjectCapabilityStatements', 'TR_SearchV2_ProjectCapabilities', 'Project', 'ProjectId');
            SELECT search_v2_install_trigger('ProjectTechnicalSpecificationItems', 'TR_SearchV2_ProjectSpecifications', 'Project', 'ProjectId');
            SELECT search_v2_install_trigger('ProjectStages', 'TR_SearchV2_ProjectStages', 'Project', 'ProjectId');
            SELECT search_v2_install_trigger('ProjectDocuments', 'TR_SearchV2_ProjectDocuments', 'ProjectDocument', 'Id');
            SELECT search_v2_install_trigger('ProjectDocumentTexts', 'TR_SearchV2_ProjectDocumentTexts', 'ProjectDocument', 'ProjectDocumentId');
            SELECT search_v2_install_trigger('Documents', 'TR_SearchV2_DocRepoDocuments', 'DocRepoDocument', 'Id');
            SELECT search_v2_install_trigger('DocRepoDocumentTexts', 'TR_SearchV2_DocumentTexts', 'DocRepoDocument', 'DocumentId');
            SELECT search_v2_install_trigger('FfcRecords', 'TR_SearchV2_FfcRecords', 'FfcRecord', 'Id');
            SELECT search_v2_install_trigger('FfcProjects', 'TR_SearchV2_FfcProjects', 'FfcRecord', 'FfcRecordId');
            SELECT search_v2_install_trigger('FfcAttachments', 'TR_SearchV2_FfcAttachments', 'FfcRecord', 'FfcRecordId');
            SELECT search_v2_install_trigger('IprRecords', 'TR_SearchV2_IprRecords', 'IprRecord', 'Id');
            SELECT search_v2_install_trigger('IprAttachments', 'TR_SearchV2_IprAttachments', 'IprRecord', 'IprRecordId');
            SELECT search_v2_install_trigger('Activities', 'TR_SearchV2_Activities', 'Activity', 'Id');
            SELECT search_v2_install_trigger('Visits', 'TR_SearchV2_Visits', 'Visit', 'Id');
            SELECT search_v2_install_trigger('SocialMediaEvents', 'TR_SearchV2_SocialMediaEvents', 'SocialMediaEvent', 'Id');
            SELECT search_v2_install_trigger('Trainings', 'TR_SearchV2_Trainings', 'Training', 'Id');
            SELECT search_v2_install_trigger('TrainingProjects', 'TR_SearchV2_TrainingProjects', 'Training', 'TrainingId');
            SELECT search_v2_install_trigger('TrainingTrainees', 'TR_SearchV2_TrainingTrainees', 'Training', 'TrainingId');
            SELECT search_v2_install_trigger('ProjectTots', 'TR_SearchV2_ProjectTots', 'ProjectTot', 'ProjectId');
            SELECT search_v2_install_trigger('ProliferationGranular', 'TR_SearchV2_Proliferation', 'ProliferationGranular', 'Id');
            SELECT search_v2_install_trigger('ArppIssues', 'TR_SearchV2_ArppIssues', 'ArppIssue', 'Id');
            SELECT search_v2_install_trigger('ArppEntries', 'TR_SearchV2_ArppEntries', 'ArppIssue', 'ArppIssueId');

            DROP FUNCTION search_v2_install_trigger(text, text, text, text);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        if (!string.Equals(ActiveProvider, "Npgsql.EntityFrameworkCore.PostgreSQL", StringComparison.Ordinal))
        {
            throw new NotSupportedException("Search V2 requires PostgreSQL.");
        }

        migrationBuilder.Sql("DROP FUNCTION IF EXISTS search_v2_enqueue_row() CASCADE;");
        migrationBuilder.Sql("DROP FUNCTION IF EXISTS search_v2_enqueue(text, text) CASCADE;");
        migrationBuilder.Sql("DROP FUNCTION IF EXISTS search_v2_refresh_vectors() CASCADE;");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchShadowComparisons\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchClickLogs\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchQueryLogs\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchIndexWorkItems\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchAliases\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchEntryPrincipals\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchEntryTerms\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchEntries\";");
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"SearchIndexState\";");
    }
}
