using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261125150000_ActionTrackerMigrationOrderRepair")]
    public class ActionTrackerMigrationOrderRepair : Migration
    {
        // SECTION: Action Tracker migration order repair strategy
        // Action Tracker migration order repair:
        // We are using a forward-only corrective migration (not history rebuild) because existing
        // environments may already depend on current migration IDs and ordering.

        // SECTION: Apply repair to normalize Action Tracker tables and FKs
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // SECTION: PostgreSQL idempotent schema repair
            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTasks" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "Title" character varying(200) NOT NULL,
                        "Description" character varying(4000) NOT NULL,
                        "CreatedByUserId" character varying(450) NOT NULL,
                        "AssignedToUserId" character varying(450) NOT NULL,
                        "CreatedByRole" character varying(64) NOT NULL,
                        "AssignedToRole" character varying(64) NOT NULL,
                        "AssignedOn" timestamp with time zone NOT NULL,
                        "DueDate" date NOT NULL,
                        "Priority" character varying(24) NOT NULL,
                        "Status" character varying(32) NOT NULL,
                        "SubmittedOn" timestamp with time zone NULL,
                        "ClosedOn" timestamp with time zone NULL,
                        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                        CONSTRAINT "PK_ActionTasks" PRIMARY KEY ("Id")
                    );
                    """);

                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTaskAuditLogs" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "TaskId" integer NOT NULL,
                        "ActionType" character varying(64) NOT NULL,
                        "PerformedByUserId" character varying(450) NOT NULL,
                        "PerformedByRole" character varying(64) NOT NULL,
                        "PerformedAt" timestamp with time zone NOT NULL,
                        "OldValue" text NULL,
                        "NewValue" text NULL,
                        "Remarks" character varying(2000) NULL,
                        CONSTRAINT "PK_ActionTaskAuditLogs" PRIMARY KEY ("Id")
                    );
                    """);

                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTaskUpdates" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "TaskId" integer NOT NULL,
                        "CreatedByUserId" character varying(450) NOT NULL,
                        "CreatedAtUtc" timestamp with time zone NOT NULL,
                        "UpdateType" character varying(32) NOT NULL,
                        "Body" character varying(4000) NOT NULL,
                        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                        CONSTRAINT "PK_ActionTaskUpdates" PRIMARY KEY ("Id")
                    );
                    """);

                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTaskAttachments" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "TaskId" integer NOT NULL,
                        "UpdateId" integer NULL,
                        "UploadedByUserId" character varying(450) NOT NULL,
                        "UploadedAtUtc" timestamp with time zone NOT NULL,
                        "OriginalFileName" character varying(260) NOT NULL,
                        "StorageKey" character varying(1024) NOT NULL,
                        "ContentType" character varying(200) NOT NULL,
                        "FileSize" bigint NOT NULL,
                        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                        CONSTRAINT "PK_ActionTaskAttachments" PRIMARY KEY ("Id")
                    );
                    """);

                // SECTION: Ensure required foreign keys exist
                migrationBuilder.Sql(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ActionTaskAuditLogs_ActionTasks_TaskId') THEN
                            ALTER TABLE "ActionTaskAuditLogs"
                                ADD CONSTRAINT "FK_ActionTaskAuditLogs_ActionTasks_TaskId"
                                FOREIGN KEY ("TaskId") REFERENCES "ActionTasks" ("Id") ON DELETE CASCADE;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ActionTaskUpdates_ActionTasks_TaskId') THEN
                            ALTER TABLE "ActionTaskUpdates"
                                ADD CONSTRAINT "FK_ActionTaskUpdates_ActionTasks_TaskId"
                                FOREIGN KEY ("TaskId") REFERENCES "ActionTasks" ("Id") ON DELETE CASCADE;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ActionTaskAttachments_ActionTasks_TaskId') THEN
                            ALTER TABLE "ActionTaskAttachments"
                                ADD CONSTRAINT "FK_ActionTaskAttachments_ActionTasks_TaskId"
                                FOREIGN KEY ("TaskId") REFERENCES "ActionTasks" ("Id") ON DELETE CASCADE;
                        END IF;

                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ActionTaskAttachments_ActionTaskUpdates_UpdateId') THEN
                            ALTER TABLE "ActionTaskAttachments"
                                ADD CONSTRAINT "FK_ActionTaskAttachments_ActionTaskUpdates_UpdateId"
                                FOREIGN KEY ("UpdateId") REFERENCES "ActionTaskUpdates" ("Id") ON DELETE RESTRICT;
                        END IF;
                    END $$;
                    """);

                // SECTION: Ensure key indexes exist
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAuditLogs_PerformedByUserId" ON "ActionTaskAuditLogs" ("PerformedByUserId");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAuditLogs_TaskId_PerformedAt" ON "ActionTaskAuditLogs" ("TaskId", "PerformedAt");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_AssignedToUserId_Status" ON "ActionTasks" ("AssignedToUserId", "Status");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_DueDate_Status" ON "ActionTasks" ("DueDate", "Status");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_IsDeleted" ON "ActionTasks" ("IsDeleted");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskUpdates_TaskId_CreatedAtUtc" ON "ActionTaskUpdates" ("TaskId", "CreatedAtUtc");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAttachments_TaskId" ON "ActionTaskAttachments" ("TaskId");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAttachments_UpdateId" ON "ActionTaskAttachments" ("UpdateId");""");
            }
        }

        // SECTION: Keep repair migration non-destructive on rollback
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Action Tracker migration order repair: no-op by design to avoid destructive drops.
        }
    }
}
