using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjectManagement.Data;

#nullable disable

namespace ProjectManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260430160000_ActionTrackerMigrationOrderRepair")]
    public class ActionTrackerMigrationOrderRepair : Migration
    {
        // SECTION: Action Tracker migration order repair strategy
        // Action Tracker migration order repair:
        // This migration intentionally runs before AddActionTaskCollaboration so the ActionTasks
        // principal table exists before that migration adds child tables with required FKs.
        // It only creates the parent Action Tracker tables that later migrations can tolerate
        // via CREATE TABLE IF NOT EXISTS, avoiding duplicate child table creation on fresh applies.

        // SECTION: Apply repair to normalize Action Tracker tables and FKs
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // SECTION: PostgreSQL idempotent schema repair
            if (ActiveProvider.Contains("Npgsql", StringComparison.OrdinalIgnoreCase))
            {
                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTasks" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "Title" character varying(200) NOT NULL,
                        "Description" character varying(4000) NOT NULL,
                        "CreatedByUserId" character varying(450) NOT NULL,
                        "AssignedToUserId" character varying(450) NOT NULL,
                        "CreatedByRole" character varying(64) NOT NULL,
                        "AssignedToRole" character varying(64) NOT NULL,
                        "AssignedOn" timestamp with time zone NOT NULL,
                        "DueDate" date NOT NULL,
                        "Priority" character varying(24) NOT NULL,
                        "Status" character varying(32) NOT NULL,
                        "SubmittedOn" timestamp with time zone NULL,
                        "ClosedOn" timestamp with time zone NULL,
                        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
                        CONSTRAINT "PK_ActionTasks" PRIMARY KEY ("Id")
                    );
                    """);

                migrationBuilder.Sql(
                    """
                    CREATE TABLE IF NOT EXISTS "ActionTaskAuditLogs" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                        "TaskId" integer NOT NULL,
                        "ActionType" character varying(64) NOT NULL,
                        "PerformedByUserId" character varying(450) NOT NULL,
                        "PerformedByRole" character varying(64) NOT NULL,
                        "PerformedAt" timestamp with time zone NOT NULL,
                        "OldValue" text NULL,
                        "NewValue" text NULL,
                        "Remarks" character varying(2000) NULL,
                        CONSTRAINT "PK_ActionTaskAuditLogs" PRIMARY KEY ("Id")
                    );
                    """);

                // SECTION: Ensure required foreign keys exist for the parent tables
                migrationBuilder.Sql(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ActionTaskAuditLogs_ActionTasks_TaskId') THEN
                            ALTER TABLE "ActionTaskAuditLogs"
                                ADD CONSTRAINT "FK_ActionTaskAuditLogs_ActionTasks_TaskId"
                                FOREIGN KEY ("TaskId") REFERENCES "ActionTasks" ("Id") ON DELETE CASCADE;
                        END IF;
                    END $$;
                    """);

                // SECTION: Ensure key indexes exist for the parent tables
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAuditLogs_PerformedByUserId" ON "ActionTaskAuditLogs" ("PerformedByUserId");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTaskAuditLogs_TaskId_PerformedAt" ON "ActionTaskAuditLogs" ("TaskId", "PerformedAt");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_AssignedToUserId_Status" ON "ActionTasks" ("AssignedToUserId", "Status");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_DueDate_Status" ON "ActionTasks" ("DueDate", "Status");""");
                migrationBuilder.Sql("""CREATE INDEX IF NOT EXISTS "IX_ActionTasks_IsDeleted" ON "ActionTasks" ("IsDeleted");""");
            }
        }

        // SECTION: Keep repair migration non-destructive on rollback
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Action Tracker migration order repair: no-op by design to avoid destructive drops.
        }
    }
}
