using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using ClosedXML.Excel;
using ProjectManagement.Areas.ProjectOfficeReports.Application;
using ProjectManagement.Areas.ProjectOfficeReports.Application.Training.Dtos;
using ProjectManagement.Areas.ProjectOfficeReports.Domain;
using ProjectManagement.Utilities;

namespace ProjectManagement.Utilities.Reporting;

public interface ITrainingExcelWorkbookBuilder
{
    byte[] Build(TrainingExcelWorkbookContext context);
}

public sealed record TrainingExcelWorkbookContext(
    TrainingExportDataset Dataset,
    TrainingKpiDto Kpis,
    DateTimeOffset GeneratedAtUtc,
    string RequestedByDisplayName,
    string ApplicationBaseUrl,
    DateOnly? From,
    DateOnly? To,
    string? Search,
    bool IncludeRoster,
    TrainingRosterScope RosterScope,
    string? TrainingTypeName,
    string? CategoryName,
    string? ProjectName,
    string? ProjectTechnicalCategoryName);

public sealed class TrainingExcelWorkbookBuilder : ITrainingExcelWorkbookBuilder
{
    private const string Navy = "#17365D";
    private const string Blue = "#2F75B5";
    private const string PaleBlue = "#D9EAF7";
    private const string PaleGreen = "#E2F0D9";
    private const string PaleAmber = "#FFF2CC";
    private const string LightGray = "#F2F2F2";
    private const string AlternateGroupFill = "#F4F8FC";
    private const string BorderGray = "#D9E1F2";

    public byte[] Build(TrainingExcelWorkbookContext context)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(context.Dataset);
        ArgumentNullException.ThrowIfNull(context.Kpis);

        using var workbook = new XLWorkbook();
        workbook.Properties.Title = "PRISM ERP Training Tracker Export";
        workbook.Properties.Subject = "Filtered training tracker report";
        workbook.Properties.Author = string.IsNullOrWhiteSpace(context.RequestedByDisplayName)
            ? "PRISM ERP"
            : context.RequestedByDisplayName;
        workbook.Properties.Company = "Simulator Development Division";

        WriteSummaryWorksheet(workbook.Worksheets.Add("Summary"), context);
        WriteTrainingsWorksheet(workbook.Worksheets.Add("Trainings"), context);
        WriteTrainingProjectsWorksheet(workbook.Worksheets.Add("Training Projects"), context);

        if (context.IncludeRoster)
        {
            WriteRosterWorksheet(workbook.Worksheets.Add("Roster"), context);
        }

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    private static void WriteSummaryWorksheet(IXLWorksheet worksheet, TrainingExcelWorkbookContext context)
    {
        worksheet.Range("A1:H1").Merge();
        worksheet.Cell("A1").Value = "TRAINING TRACKER";
        worksheet.Cell("A1").Style.Font.Bold = true;
        worksheet.Cell("A1").Style.Font.FontSize = 20;
        worksheet.Cell("A1").Style.Font.FontColor = XLColor.White;
        worksheet.Cell("A1").Style.Fill.BackgroundColor = XLColor.FromHtml(Navy);
        worksheet.Cell("A1").Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        worksheet.Row(1).Height = 32;

        worksheet.Range("A2:H2").Merge();
        worksheet.Cell("A2").Value = "Filtered training position and supporting detail";
        worksheet.Cell("A2").Style.Font.FontColor = XLColor.FromHtml("#5B6573");
        worksheet.Cell("A2").Style.Font.Italic = true;
        worksheet.Row(2).Height = 22;

        var generatedAtIst = TimeZoneInfo.ConvertTime(context.GeneratedAtUtc, TimeZoneHelper.GetIst());
        worksheet.Cell("A4").Value = "Generated on";
        worksheet.Cell("B4").Value = generatedAtIst.DateTime;
        worksheet.Cell("B4").Style.DateFormat.Format = "dd-mmm-yyyy hh:mm AM/PM \"IST\"";
        worksheet.Cell("E4").Value = "Generated by";
        worksheet.Cell("F4").Value = DisplayOrAll(context.RequestedByDisplayName, "PRISM user");
        worksheet.Range("F4:H4").Merge();
        StyleMetadataLabel(worksheet.Cell("A4"));
        StyleMetadataLabel(worksheet.Cell("E4"));

        worksheet.Range("A6:H6").Merge();
        worksheet.Cell("A6").Value = "APPLIED FILTERS";
        StyleSectionHeading(worksheet.Cell("A6"));

        WriteFilter(worksheet, 7, "Training type", DisplayOrAll(context.TrainingTypeName, "All training types"), "Project", DisplayOrAll(context.ProjectName, "All projects"));
        WriteFilter(worksheet, 8, "Technical category", DisplayOrAll(context.ProjectTechnicalCategoryName, "All technical categories"), "Training includes", DisplayOrAll(context.CategoryName, "All trainee categories"));
        WriteFilter(worksheet, 9, "From", context.From?.ToString("dd MMM yyyy", CultureInfo.InvariantCulture) ?? "All dates", "To", context.To?.ToString("dd MMM yyyy", CultureInfo.InvariantCulture) ?? "All dates");
        WriteFilter(worksheet, 10, "Search", DisplayOrAll(context.Search, "No search term"), "Roster", FormatRosterScope(context));

        worksheet.Range("A12:H12").Merge();
        worksheet.Cell("A12").Value = "CURRENT POSITION";
        StyleSectionHeading(worksheet.Cell("A12"));

        var trainings = context.Dataset.Trainings;
        var officers = trainings.Sum(row => row.Summary.Officers);
        var jcos = trainings.Sum(row => row.Summary.JuniorCommissionedOfficers);
        var ors = trainings.Sum(row => row.Summary.OtherRanks);
        var totalTrainees = trainings.Sum(row => row.Summary.Total);

        WriteKpiCard(worksheet, "A14:B16", "TOTAL TRAININGS", trainings.Count, PaleBlue);
        WriteKpiCard(worksheet, "C14:D16", "TOTAL TRAINEES", totalTrainees, PaleGreen);
        WriteKpiCard(worksheet, "E14:F16", "OFFICERS · JCOS · ORS", $"{officers:N0} · {jcos:N0} · {ors:N0}", PaleAmber);
        WriteKpiCard(
            worksheet,
            "G14:H16",
            "ROSTER ROWS",
            context.IncludeRoster ? context.Dataset.RosterRowCount : "Not included",
            LightGray);

        const int byTypeStart = 19;
        worksheet.Range(byTypeStart, 1, byTypeStart, 4).Merge();
        worksheet.Cell(byTypeStart, 1).Value = "TRAINING TYPE SUMMARY";
        StyleSectionHeading(worksheet.Cell(byTypeStart, 1));
        WriteSimpleHeader(worksheet, byTypeStart + 1, 1, new[] { "Training type", "Trainings", "Trainees", "Strength (O-JCO-OR)" });

        var row = byTypeStart + 2;
        foreach (var item in context.Kpis.ByType.OrderByDescending(item => item.Trainees).ThenBy(item => item.TypeName))
        {
            worksheet.Cell(row, 1).Value = item.TypeName;
            worksheet.Cell(row, 2).Value = item.Trainings;
            worksheet.Cell(row, 3).Value = item.Trainees;
            worksheet.Cell(row, 4).Value = $"{item.Officers:N0}-{item.Jcos:N0}-{item.Ors:N0}";
            row++;
        }

        if (row == byTypeStart + 2)
        {
            worksheet.Cell(row, 1).Value = "No matching data";
            worksheet.Range(row, 1, row, 4).Merge();
            row++;
        }

        const int yearStart = 19;
        worksheet.Range(yearStart, 5, yearStart, 8).Merge();
        worksheet.Cell(yearStart, 5).Value = "TRAINING YEAR TREND (APR–MAR)";
        StyleSectionHeading(worksheet.Cell(yearStart, 5));
        WriteSimpleHeader(worksheet, yearStart + 1, 5, new[] { "Training year", "Trainings", "Simulator trainees", "Drone trainees" });

        var yearRow = yearStart + 2;
        foreach (var item in context.Kpis.ByTrainingYear.OrderBy(item => item.TrainingYearLabel))
        {
            worksheet.Cell(yearRow, 5).Value = item.TrainingYearLabel;
            worksheet.Cell(yearRow, 6).Value = item.TotalTrainings;
            worksheet.Cell(yearRow, 7).Value = item.SimulatorTrainings;
            worksheet.Cell(yearRow, 8).Value = item.DroneTrainings;
            yearRow++;
        }

        if (yearRow == yearStart + 2)
        {
            worksheet.Cell(yearRow, 5).Value = "No matching data";
            worksheet.Range(yearRow, 5, yearRow, 8).Merge();
            yearRow++;
        }

        var technicalStart = Math.Max(row, yearRow) + 2;
        worksheet.Range(technicalStart, 1, technicalStart, 8).Merge();
        worksheet.Cell(technicalStart, 1).Value = "PROJECT TECHNICAL CATEGORY SUMMARY";
        StyleSectionHeading(worksheet.Cell(technicalStart, 1));
        WriteSimpleHeader(worksheet, technicalStart + 1, 1, new[] { "Technical category", "Trainings", "Trainees", "Officers", "JCOs", "ORs" });

        var technicalRow = technicalStart + 2;
        foreach (var item in context.Kpis.ByTechnicalCategory
                     .OrderByDescending(item => item.Trainees)
                     .ThenBy(item => item.TechnicalCategoryName))
        {
            worksheet.Cell(technicalRow, 1).Value = item.TechnicalCategoryName;
            worksheet.Cell(technicalRow, 2).Value = item.Trainings;
            worksheet.Cell(technicalRow, 3).Value = item.Trainees;
            worksheet.Cell(technicalRow, 4).Value = item.Officers;
            worksheet.Cell(technicalRow, 5).Value = item.Jcos;
            worksheet.Cell(technicalRow, 6).Value = item.Ors;
            technicalRow++;
        }

        if (technicalRow == technicalStart + 2)
        {
            worksheet.Cell(technicalRow, 1).Value = "No matching data";
            worksheet.Range(technicalRow, 1, technicalRow, 6).Merge();
            technicalRow++;
        }

        var categoryNoteRow = technicalRow + 1;
        worksheet.Range(categoryNoteRow, 1, categoryNoteRow + 1, 8).Merge();
        worksheet.Cell(categoryNoteRow, 1).Value =
            "Note: A training linked to projects in more than one technical category is counted under each applicable category. Category rows are therefore not additive.";
        worksheet.Cell(categoryNoteRow, 1).Style.Font.Italic = true;
        worksheet.Cell(categoryNoteRow, 1).Style.Font.FontColor = XLColor.FromHtml("#5B6573");
        worksheet.Cell(categoryNoteRow, 1).Style.Fill.BackgroundColor = XLColor.FromHtml("#F8FAFC");
        worksheet.Cell(categoryNoteRow, 1).Style.Alignment.WrapText = true;
        worksheet.Cell(categoryNoteRow, 1).Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        worksheet.Range(categoryNoteRow, 1, categoryNoteRow + 1, 8).Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
        worksheet.Range(categoryNoteRow, 1, categoryNoteRow + 1, 8).Style.Border.OutsideBorderColor = XLColor.FromHtml(BorderGray);

        if (context.IncludeRoster)
        {
            var noticeRow = categoryNoteRow + 3;
            worksheet.Range(noticeRow, 1, noticeRow + 1, 8).Merge();
            worksheet.Cell(noticeRow, 1).Value =
                "Handling note: The Roster sheet contains personnel details. Handle and share this workbook in accordance with organisational policy.";
            worksheet.Cell(noticeRow, 1).Style.Fill.BackgroundColor = XLColor.FromHtml(PaleAmber);
            worksheet.Cell(noticeRow, 1).Style.Font.Bold = true;
            worksheet.Cell(noticeRow, 1).Style.Alignment.WrapText = true;
            worksheet.Cell(noticeRow, 1).Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
            worksheet.Range(noticeRow, 1, noticeRow + 1, 8).Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
            worksheet.Range(noticeRow, 1, noticeRow + 1, 8).Style.Border.OutsideBorderColor = XLColor.FromHtml(BorderGray);
        }

        worksheet.Column(1).Width = 24;
        worksheet.Column(2).Width = 16;
        worksheet.Column(3).Width = 19;
        worksheet.Column(4).Width = 20;
        worksheet.Column(5).Width = 24;
        worksheet.Column(6).Width = 16;
        worksheet.Column(7).Width = 18;
        worksheet.Column(8).Width = 18;
        var usedRange = worksheet.RangeUsed();
        if (usedRange is not null)
        {
            usedRange.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        }
        ConfigurePrint(worksheet, repeatHeaderRow: null, landscape: true);
    }

    private static void WriteTrainingsWorksheet(IXLWorksheet worksheet, TrainingExcelWorkbookContext context)
    {
        var normalizedNotes = context.Dataset.Trainings
            .ToDictionary(item => item.Summary.Id, item => NormalizeReportNote(item.Summary.Notes));
        var includeNotes = normalizedNotes.Values.Any(value => !string.IsNullOrWhiteSpace(value));

        var headers = new List<string>
        {
            "S.No.", "Training type", "Start date", "End date", "Recorded period",
            "Duration (days)", "Training year", "Officers", "JCOs", "ORs", "Total trainees",
            "Source", "Project count", "Projects"
        };
        if (includeNotes)
        {
            headers.Add("Notes");
        }

        WriteTableHeader(worksheet, headers);
        var rowNumber = 2;
        var serial = 1;

        foreach (var detail in context.Dataset.Trainings)
        {
            var row = detail.Summary;
            worksheet.Cell(rowNumber, 1).Value = serial++;
            worksheet.Cell(rowNumber, 2).Value = row.TrainingTypeName;
            WriteDate(worksheet.Cell(rowNumber, 3), row.StartDate);
            WriteDate(worksheet.Cell(rowNumber, 4), row.EndDate);
            worksheet.Cell(rowNumber, 5).Value = row.Period;
            if (row.DurationDays.HasValue) worksheet.Cell(rowNumber, 6).Value = row.DurationDays.Value;
            worksheet.Cell(rowNumber, 7).Value = row.TrainingYearLabel;
            worksheet.Cell(rowNumber, 8).Value = row.Officers;
            worksheet.Cell(rowNumber, 9).Value = row.JuniorCommissionedOfficers;
            worksheet.Cell(rowNumber, 10).Value = row.OtherRanks;
            worksheet.Cell(rowNumber, 11).Value = row.Total;
            worksheet.Cell(rowNumber, 12).Value = FormatSource(row.Source);
            worksheet.Cell(rowNumber, 13).Value = row.Projects?.Count ?? 0;
            worksheet.Cell(rowNumber, 14).Value = row.Projects is { Count: > 0 }
                ? string.Join("; ", row.Projects)
                : string.Empty;
            if (includeNotes)
            {
                worksheet.Cell(rowNumber, 15).Value = normalizedNotes[row.Id] ?? string.Empty;
            }
            rowNumber++;
        }

        CreateTableIfPopulated(worksheet, "TrainingsTable", headers.Count, rowNumber - 1);
        worksheet.SheetView.FreezeRows(1);
        worksheet.SheetView.FreezeColumns(2);

        var widths = new Dictionary<int, double>
        {
            [1] = 8, [2] = 24, [3] = 14, [4] = 14, [5] = 28, [6] = 14,
            [7] = 14, [8] = 11, [9] = 11, [10] = 11, [11] = 14, [12] = 14,
            [13] = 13, [14] = 42
        };
        if (includeNotes) widths[15] = 48;
        SetWidths(worksheet, widths);
        worksheet.Column(14).Style.Alignment.WrapText = true;
        if (includeNotes) worksheet.Column(15).Style.Alignment.WrapText = true;
        worksheet.Column(1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        worksheet.Columns(6, 13).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;

        var usedRange = worksheet.RangeUsed();
        if (usedRange is not null)
        {
            usedRange.Style.Alignment.Vertical = XLAlignmentVerticalValues.Top;
        }
        ConfigurePrint(worksheet, repeatHeaderRow: 1, landscape: true);
    }

    private static void WriteTrainingProjectsWorksheet(IXLWorksheet worksheet, TrainingExcelWorkbookContext context)
    {
        var headers = new[]
        {
            "Training S.No.", "Training type", "Project name", "Technical category", "Project status"
        };

        WriteTableHeader(worksheet, headers);
        var trainingSerials = BuildTrainingSerialLookup(context.Dataset.Trainings);
        var summaries = context.Dataset.Trainings.ToDictionary(item => item.Summary.Id, item => item.Summary);
        var rowNumber = 2;

        foreach (var project in context.Dataset.ProjectLinks
                     .Where(item => trainingSerials.ContainsKey(item.TrainingId))
                     .OrderBy(item => trainingSerials[item.TrainingId])
                     .ThenBy(item => item.ProjectName, StringComparer.OrdinalIgnoreCase))
        {
            summaries.TryGetValue(project.TrainingId, out var training);
            worksheet.Cell(rowNumber, 1).Value = trainingSerials[project.TrainingId];
            worksheet.Cell(rowNumber, 2).Value = training?.TrainingTypeName ?? string.Empty;
            worksheet.Cell(rowNumber, 3).Value = project.ProjectName;
            worksheet.Cell(rowNumber, 4).Value = project.TechnicalCategoryName;
            worksheet.Cell(rowNumber, 5).Value = project.ProjectStatus;
            rowNumber++;
        }

        CreateTableIfPopulated(worksheet, "TrainingProjectsTable", headers.Length, rowNumber - 1);
        ApplyTrainingGroupFormatting(worksheet, 2, rowNumber - 1, headers.Length, serialColumn: 1);
        worksheet.SheetView.FreezeRows(1);
        worksheet.SheetView.FreezeColumns(2);
        SetWidths(worksheet, new Dictionary<int, double>
        {
            [1] = 15, [2] = 24, [3] = 46, [4] = 27, [5] = 18
        });
        worksheet.Columns(2, 4).Style.Alignment.WrapText = true;
        worksheet.Column(1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        ConfigurePrint(worksheet, repeatHeaderRow: 1, landscape: true);
    }

    private static void WriteRosterWorksheet(IXLWorksheet worksheet, TrainingExcelWorkbookContext context)
    {
        var headers = new[]
        {
            "S.No.", "Training S.No.", "Training type", "Start date", "End date", "Army number",
            "Rank", "Name", "Unit", "Trainee category"
        };

        WriteTableHeader(worksheet, headers);
        var trainingSerials = BuildTrainingSerialLookup(context.Dataset.Trainings);
        var rowNumber = 2;
        var rosterSerial = 1;

        foreach (var training in context.Dataset.Trainings)
        {
            var trainingSerial = trainingSerials[training.Summary.Id];
            foreach (var trainee in training.Roster)
            {
                worksheet.Cell(rowNumber, 1).Value = rosterSerial++;
                worksheet.Cell(rowNumber, 2).Value = trainingSerial;
                worksheet.Cell(rowNumber, 3).Value = training.Summary.TrainingTypeName;
                WriteDate(worksheet.Cell(rowNumber, 4), training.Summary.StartDate);
                WriteDate(worksheet.Cell(rowNumber, 5), training.Summary.EndDate);
                worksheet.Cell(rowNumber, 6).Value = trainee.ArmyNumber ?? string.Empty;
                worksheet.Cell(rowNumber, 7).Value = trainee.Rank;
                worksheet.Cell(rowNumber, 8).Value = trainee.Name;
                worksheet.Cell(rowNumber, 9).Value = trainee.UnitName;
                worksheet.Cell(rowNumber, 10).Value = FormatRosterCategory(trainee.Category);
                rowNumber++;
            }
        }

        CreateTableIfPopulated(worksheet, "RosterTable", headers.Length, rowNumber - 1);
        ApplyTrainingGroupFormatting(worksheet, 2, rowNumber - 1, headers.Length, serialColumn: 2);
        worksheet.SheetView.FreezeRows(1);
        worksheet.SheetView.FreezeColumns(3);
        SetWidths(worksheet, new Dictionary<int, double>
        {
            [1] = 8, [2] = 15, [3] = 24, [4] = 14, [5] = 14, [6] = 18,
            [7] = 12, [8] = 24, [9] = 30, [10] = 28
        });
        worksheet.Columns(8, 10).Style.Alignment.WrapText = true;
        worksheet.Columns(1, 2).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        ConfigurePrint(worksheet, repeatHeaderRow: 1, landscape: true);
    }

    private static IReadOnlyDictionary<Guid, int> BuildTrainingSerialLookup(
        IReadOnlyList<TrainingExportDetail> trainings)
        => trainings
            .Select((training, index) => new { training.Summary.Id, Serial = index + 1 })
            .ToDictionary(item => item.Id, item => item.Serial);

    private static void ApplyTrainingGroupFormatting(
        IXLWorksheet worksheet,
        int firstRow,
        int lastRow,
        int lastColumn,
        int serialColumn)
    {
        if (lastRow < firstRow)
        {
            return;
        }

        int? previousSerial = null;
        var groupIndex = -1;

        for (var row = firstRow; row <= lastRow; row++)
        {
            var serial = worksheet.Cell(row, serialColumn).GetValue<int>();
            if (previousSerial != serial)
            {
                groupIndex++;
                var topBorder = worksheet.Range(row, 1, row, lastColumn).Style.Border;
                topBorder.TopBorder = XLBorderStyleValues.Medium;
                topBorder.TopBorderColor = XLColor.FromHtml(Blue);
                previousSerial = serial;
            }

            var rowRange = worksheet.Range(row, 1, row, lastColumn);
            rowRange.Style.Fill.BackgroundColor = groupIndex % 2 == 0
                ? XLColor.White
                : XLColor.FromHtml(AlternateGroupFill);
            rowRange.Style.Alignment.Vertical = XLAlignmentVerticalValues.Top;
        }
    }

    private static string? NormalizeReportNote(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var normalized = value.Trim();
        return normalized.Any(char.IsLetter) ? normalized : null;
    }

    private static void WriteFilter(
        IXLWorksheet worksheet,
        int row,
        string leftLabel,
        string leftValue,
        string rightLabel,
        string rightValue)
    {
        worksheet.Cell(row, 1).Value = leftLabel;
        worksheet.Cell(row, 2).Value = leftValue;
        worksheet.Range(row, 2, row, 4).Merge();
        worksheet.Cell(row, 5).Value = rightLabel;
        worksheet.Cell(row, 6).Value = rightValue;
        worksheet.Range(row, 6, row, 8).Merge();
        StyleMetadataLabel(worksheet.Cell(row, 1));
        StyleMetadataLabel(worksheet.Cell(row, 5));
        worksheet.Range(row, 2, row, 4).Style.Fill.BackgroundColor = XLColor.FromHtml("#F8FAFC");
        worksheet.Range(row, 6, row, 8).Style.Fill.BackgroundColor = XLColor.FromHtml("#F8FAFC");
    }

    private static void WriteKpiCard(
        IXLWorksheet worksheet,
        string rangeAddress,
        string label,
        object value,
        string fillColor)
    {
        var range = worksheet.Range(rangeAddress);
        range.Merge();
        var cell = range.FirstCell();
        cell.Value = $"{label}\n{value}";
        cell.Style.Alignment.WrapText = true;
        cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        cell.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Left;
        cell.Style.Font.Bold = true;
        cell.Style.Font.FontSize = 13;
        cell.Style.Fill.BackgroundColor = XLColor.FromHtml(fillColor);
        range.Style.Border.OutsideBorder = XLBorderStyleValues.Thin;
        range.Style.Border.OutsideBorderColor = XLColor.FromHtml(BorderGray);
    }

    private static void WriteSimpleHeader(IXLWorksheet worksheet, int row, int startColumn, IReadOnlyList<string> headers)
    {
        for (var index = 0; index < headers.Count; index++)
        {
            worksheet.Cell(row, startColumn + index).Value = headers[index];
        }

        var range = worksheet.Range(row, startColumn, row, startColumn + headers.Count - 1);
        range.Style.Font.Bold = true;
        range.Style.Font.FontColor = XLColor.White;
        range.Style.Fill.BackgroundColor = XLColor.FromHtml(Blue);
        range.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        range.Style.Border.BottomBorder = XLBorderStyleValues.Thin;
    }

    private static void WriteTableHeader(IXLWorksheet worksheet, IReadOnlyList<string> headers)
    {
        for (var column = 0; column < headers.Count; column++)
        {
            worksheet.Cell(1, column + 1).Value = headers[column];
        }

        var headerRange = worksheet.Range(1, 1, 1, headers.Count);
        headerRange.Style.Font.Bold = true;
        headerRange.Style.Font.FontColor = XLColor.White;
        headerRange.Style.Fill.BackgroundColor = XLColor.FromHtml(Navy);
        headerRange.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        headerRange.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        headerRange.Style.Alignment.WrapText = true;
        worksheet.Row(1).Height = 30;
    }

    private static void CreateTableIfPopulated(IXLWorksheet worksheet, string tableName, int columnCount, int lastRow)
    {
        if (lastRow < 2)
        {
            return;
        }

        var table = worksheet.Range(1, 1, lastRow, columnCount).CreateTable(tableName);
        table.Theme = XLTableTheme.TableStyleMedium2;
    }

    private static void ConfigurePrint(IXLWorksheet worksheet, int? repeatHeaderRow, bool landscape)
    {
        worksheet.PageSetup.PageOrientation = landscape
            ? XLPageOrientation.Landscape
            : XLPageOrientation.Portrait;
        worksheet.PageSetup.PaperSize = XLPaperSize.A4Paper;
        worksheet.PageSetup.FitToPages(1, 0);
        worksheet.PageSetup.Margins.Top = 0.5;
        worksheet.PageSetup.Margins.Bottom = 0.5;
        worksheet.PageSetup.Margins.Left = 0.35;
        worksheet.PageSetup.Margins.Right = 0.35;
        worksheet.PageSetup.Footer.Left.AddText("PRISM ERP");
        worksheet.PageSetup.Footer.Center.AddText("Training Tracker");
        worksheet.PageSetup.Footer.Right.AddText("Page ");
        worksheet.PageSetup.Footer.Right.AddText(XLHFPredefinedText.PageNumber);
        worksheet.PageSetup.Footer.Right.AddText(" of ");
        worksheet.PageSetup.Footer.Right.AddText(XLHFPredefinedText.NumberOfPages);

        if (repeatHeaderRow.HasValue)
        {
            worksheet.PageSetup.SetRowsToRepeatAtTop(repeatHeaderRow.Value, repeatHeaderRow.Value);
        }
    }

    private static void WriteDate(IXLCell cell, DateOnly? value)
    {
        if (!value.HasValue)
        {
            return;
        }

        cell.Value = value.Value.ToDateTime(TimeOnly.MinValue);
        cell.Style.DateFormat.Format = "dd-mmm-yyyy";
    }

    private static void StyleSectionHeading(IXLCell cell)
    {
        cell.Style.Font.Bold = true;
        cell.Style.Font.FontColor = XLColor.White;
        cell.Style.Fill.BackgroundColor = XLColor.FromHtml(Blue);
        cell.Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
    }

    private static void StyleMetadataLabel(IXLCell cell)
    {
        cell.Style.Font.Bold = true;
        cell.Style.Font.FontColor = XLColor.FromHtml("#44546A");
    }

    private static void SetWidths(IXLWorksheet worksheet, IReadOnlyDictionary<int, double> widths)
    {
        foreach (var (column, width) in widths)
        {
            worksheet.Column(column).Width = width;
        }
    }

    private static string DisplayOrAll(string? value, string fallback)
        => string.IsNullOrWhiteSpace(value) ? fallback : value.Trim();

    private static string FormatRosterScope(TrainingExcelWorkbookContext context)
    {
        if (!context.IncludeRoster)
        {
            return "Not included";
        }

        if (context.RosterScope == TrainingRosterScope.SelectedTraineeCategoryOnly
            && !string.IsNullOrWhiteSpace(context.CategoryName))
        {
            return $"Selected category only ({context.CategoryName})";
        }

        return "All trainees in matching events";
    }

    private static string FormatSource(TrainingCounterSource source)
        => source == TrainingCounterSource.Legacy ? "Legacy counters" : "Roster";

    private static string FormatRosterCategory(byte category)
        => category switch
        {
            (byte)TrainingCategory.Officer => "Officer",
            (byte)TrainingCategory.JuniorCommissionedOfficer => "Junior Commissioned Officer",
            (byte)TrainingCategory.OtherRank => "Other Rank",
            _ => "Unknown"
        };
}
