namespace ProjectManagement.Models.Notifications;

public enum NotificationKind
{
    RemarkCreated = 1,
    MentionedInRemark = 2,
    PlanSubmitted = 10,
    PlanApproved = 11,
    PlanRejected = 12,
    StageStatusChanged = 20,
    StageAssigned = 21,
    DocumentPublished = 30,
    DocumentReplaced = 31,
    DocumentArchived = 32,
    DocumentRestored = 33,
    DocumentDeleted = 34,
    RoleAssignmentsChanged = 40,
    ProjectAssignmentChanged = 41,
    TrainingDeleteRequested = 90,
    TrainingDeleteApproved = 91,
    TrainingDeleteRejected = 92,
    ActivityDeleteRequested = 93,
    ActivityDeleteApproved = 94,
    ActivityDeleteRejected = 95,
    ActionTaskAssigned = 100,
    ActionTaskProgressUpdated = 101,
    ActionTaskStatusChanged = 102,
    ActionTaskBlocked = 103,
    ActionTaskSubmittedForClosure = 104,
    ActionTaskClosed = 105,
    ActionTaskDueDateChanged = 106,
    ActionTaskMovedToBacklog = 107,
    ActionTaskRemovedFromSprint = 108,
    ActionTaskAddedToSprint = 109,
    NotebookShared = 120,
    NotebookAccessRemoved = 121,
    NotebookCollaborationLeft = 122
}
