using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Validation;
using P = DocumentFormat.OpenXml.Presentation;

namespace ProjectManagement.Services.ProjectBriefings.Presentation;

/// <summary>
/// Raised when a generated briefing deck is not safe to return to PowerPoint.
/// The export is stopped before a corrupt package can be downloaded.
/// </summary>
public sealed class ProjectBriefingPresentationIntegrityException : Exception
{
    public ProjectBriefingPresentationIntegrityException(
        IReadOnlyList<string> issues,
        Exception? innerException = null)
        : base(BuildMessage(issues), innerException)
    {
        Issues = (issues ?? Array.Empty<string>())
            .Where(issue => !string.IsNullOrWhiteSpace(issue))
            .Distinct(StringComparer.Ordinal)
            .ToArray();
    }

    public IReadOnlyList<string> Issues { get; }

    public string GetUserSafeSummary(int maximumIssues = 3)
    {
        var selected = Issues
            .Take(Math.Max(1, maximumIssues))
            .ToArray();

        return selected.Length == 0
            ? "The generated PowerPoint failed its integrity check."
            : string.Join(" | ", selected);
    }

    private static string BuildMessage(IReadOnlyList<string>? issues)
    {
        var reported = (issues ?? Array.Empty<string>())
            .Where(issue => !string.IsNullOrWhiteSpace(issue))
            .Distinct(StringComparer.Ordinal)
            .Take(12)
            .ToArray();
        if (reported.Length == 0)
        {
            return "The generated PowerPoint failed its integrity check and was not returned.";
        }

        return "The generated PowerPoint failed its integrity check and was not returned. "
               + string.Join(" | ", reported);
    }
}

/// <summary>
/// Performs package, relationship, generated-slide and image validation.
///
/// The briefing deck is based on an approved PowerPoint template. The template's
/// master, layout, theme and Office-authored ancillary parts are not regenerated by
/// PRISM and are therefore not revalidated as if they were newly authored content.
/// Validating the complete inherited package can produce false failures for benign
/// Office extension markup. The presentation root and every generated slide remain
/// schema-validated, while package relationships and embedded images are checked
/// separately below.
/// </summary>
internal static class ProjectBriefingPresentationIntegrityValidator
{
    private const int MaximumSchemaErrors = 30;

    public static void Validate(byte[] content, int expectedSlideCount)
    {
        ArgumentNullException.ThrowIfNull(content);
        if (content.Length == 0)
        {
            throw new ProjectBriefingPresentationIntegrityException(
                new[] { "The generated PowerPoint package is empty." });
        }

        try
        {
            using var stream = new MemoryStream(content, writable: false);
            using var document = PresentationDocument.Open(stream, false);
            var issues = new List<string>();
            var presentationPart = document.PresentationPart;
            if (presentationPart is null)
            {
                issues.Add("The package has no presentation part.");
                ThrowIfInvalid(issues);
                return;
            }

            var orderedSlides = ResolveOrderedSlides(presentationPart, issues);
            if (orderedSlides.Count != expectedSlideCount)
            {
                issues.Add(
                    $"Slide count mismatch: expected {expectedSlideCount}, package contains {orderedSlides.Count} ordered slides.");
            }

            var relationshipSlideCount = presentationPart.SlideParts.Count();
            if (relationshipSlideCount != orderedSlides.Count)
            {
                issues.Add(
                    $"The package contains {relationshipSlideCount} slide-part relationships but "
                    + $"only {orderedSlides.Count} slides are present in the ordered slide list.");
            }

            ValidateSlides(orderedSlides, issues);
            ValidateGeneratedSchema(presentationPart, orderedSlides, issues);
            ThrowIfInvalid(issues);
        }
        catch (ProjectBriefingPresentationIntegrityException)
        {
            throw;
        }
        catch (Exception exception)
        {
            throw new ProjectBriefingPresentationIntegrityException(
                new[]
                {
                    $"The generated package could not be reopened for validation ({exception.GetType().Name}: {exception.Message})."
                },
                exception);
        }
    }

    private static IReadOnlyList<SlidePart> ResolveOrderedSlides(
        PresentationPart presentationPart,
        ICollection<string> issues)
    {
        var result = new List<SlidePart>();
        var slideIdList = presentationPart.Presentation?.SlideIdList;
        if (slideIdList is null)
        {
            issues.Add("The presentation has no slide ID list.");
            return result;
        }

        var seenNumericIds = new HashSet<uint>();
        var seenRelationshipIds = new HashSet<string>(StringComparer.Ordinal);
        var position = 0;
        foreach (var slideId in slideIdList.Elements<P.SlideId>())
        {
            position++;
            var numericId = slideId.Id?.Value;
            if (!numericId.HasValue)
            {
                issues.Add($"Slide position {position} has no numeric slide ID.");
            }
            else if (!seenNumericIds.Add(numericId.Value))
            {
                issues.Add($"Duplicate presentation slide ID {numericId.Value}.");
            }

            var relationshipId = slideId.RelationshipId?.Value;
            if (string.IsNullOrWhiteSpace(relationshipId))
            {
                issues.Add($"Slide position {position} has no relationship ID.");
                continue;
            }
            if (!seenRelationshipIds.Add(relationshipId))
            {
                issues.Add($"Duplicate slide relationship ID '{relationshipId}'.");
                continue;
            }

            try
            {
                if (presentationPart.GetPartById(relationshipId) is not SlidePart slidePart)
                {
                    issues.Add($"Relationship '{relationshipId}' at slide position {position} does not resolve to a slide part.");
                    continue;
                }

                result.Add(slidePart);
            }
            catch (Exception exception) when (exception is ArgumentOutOfRangeException or KeyNotFoundException)
            {
                issues.Add(
                    $"Relationship '{relationshipId}' at slide position {position} cannot be resolved ({exception.Message}).");
            }
        }

        return result;
    }

    private static void ValidateSlides(
        IReadOnlyList<SlidePart> slides,
        ICollection<string> issues)
    {
        for (var index = 0; index < slides.Count; index++)
        {
            var slideNumber = index + 1;
            var slidePart = slides[index];
            if (slidePart.SlideLayoutPart is null)
            {
                issues.Add($"Slide {slideNumber} ({slidePart.Uri}) has no slide-layout relationship.");
            }

            var duplicateShapeIds = slidePart.Slide
                .Descendants<P.NonVisualDrawingProperties>()
                .Select(properties => properties.Id?.Value)
                .Where(id => id.HasValue)
                .Select(id => id!.Value)
                .GroupBy(id => id)
                .Where(group => group.Count() > 1)
                .Select(group => group.Key)
                .ToArray();
            if (duplicateShapeIds.Length > 0)
            {
                issues.Add(
                    $"Slide {slideNumber} ({slidePart.Uri}) contains duplicate shape IDs: {string.Join(", ", duplicateShapeIds)}.");
            }

            foreach (var imagePart in slidePart.ImageParts)
            {
                ValidateImagePart(slideNumber, imagePart, issues);
            }
        }
    }

    private static void ValidateImagePart(
        int slideNumber,
        ImagePart imagePart,
        ICollection<string> issues)
    {
        Span<byte> header = stackalloc byte[12];
        int bytesRead;
        using (var stream = imagePart.GetStream(FileMode.Open, FileAccess.Read))
        {
            bytesRead = stream.Read(header);
        }

        try
        {
            using var stream = imagePart.GetStream(FileMode.Open, FileAccess.Read);
            using var image = SixLabors.ImageSharp.Image.Load(stream);
            if (image.Width <= 0 || image.Height <= 0)
            {
                issues.Add($"Slide {slideNumber} image {imagePart.Uri} has invalid pixel dimensions.");
            }
        }
        catch (Exception exception)
        {
            issues.Add(
                $"Slide {slideNumber} image {imagePart.Uri} cannot be decoded "
                + $"({exception.GetType().Name}: {exception.Message}).");
        }

        var detectedContentType = DetectImageContentType(header[..bytesRead]);
        if (detectedContentType is null)
        {
            issues.Add(
                $"Slide {slideNumber} image {imagePart.Uri} is not a supported PNG or JPEG payload.");
            return;
        }

        if (!string.Equals(imagePart.ContentType, detectedContentType, StringComparison.OrdinalIgnoreCase))
        {
            issues.Add(
                $"Slide {slideNumber} image {imagePart.Uri} is declared as '{imagePart.ContentType}' "
                + $"but its binary signature is '{detectedContentType}'.");
        }
    }

    private static string? DetectImageContentType(ReadOnlySpan<byte> header)
    {
        if (header.Length >= 8
            && header[0] == 0x89
            && header[1] == 0x50
            && header[2] == 0x4E
            && header[3] == 0x47
            && header[4] == 0x0D
            && header[5] == 0x0A
            && header[6] == 0x1A
            && header[7] == 0x0A)
        {
            return "image/png";
        }

        if (header.Length >= 3
            && header[0] == 0xFF
            && header[1] == 0xD8
            && header[2] == 0xFF)
        {
            return "image/jpeg";
        }

        return null;
    }

    private static void ValidateGeneratedSchema(
        PresentationPart presentationPart,
        IReadOnlyList<SlidePart> slides,
        ICollection<string> issues)
    {
        var validator = new OpenXmlValidator(FileFormatVersions.Office2021);
        AddSchemaErrors(
            validator.Validate(presentationPart.Presentation),
            presentationPart.Uri.ToString(),
            "presentation",
            issues);

        for (var index = 0; index < slides.Count && issues.Count < MaximumSchemaErrors; index++)
        {
            var slidePart = slides[index];
            AddSchemaErrors(
                validator.Validate(slidePart.Slide),
                slidePart.Uri.ToString(),
                $"slide {index + 1}",
                issues);
        }
    }

    private static void AddSchemaErrors(
        IEnumerable<ValidationErrorInfo> validationErrors,
        string partUri,
        string partLabel,
        ICollection<string> issues)
    {
        var remaining = Math.Max(0, MaximumSchemaErrors - issues.Count);
        if (remaining == 0)
        {
            return;
        }

        var errors = validationErrors
            .Take(remaining + 1)
            .ToArray();

        foreach (var error in errors.Take(remaining))
        {
            var path = error.Path?.XPath;
            issues.Add(string.IsNullOrWhiteSpace(path)
                ? $"Open XML error in {partLabel} ({partUri}): {error.Description}"
                : $"Open XML error in {partLabel} ({partUri}) at {path}: {error.Description}");
        }

        if (errors.Length > remaining && issues.Count < MaximumSchemaErrors)
        {
            issues.Add($"Additional Open XML validation errors were suppressed after the first {MaximumSchemaErrors}.");
        }
    }

    private static void ThrowIfInvalid(IReadOnlyCollection<string> issues)
    {
        if (issues.Count > 0)
        {
            throw new ProjectBriefingPresentationIntegrityException(issues.ToArray());
        }
    }
}
