using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using ProjectManagement.Data;
using ProjectManagement.Models;
using ProjectManagement.Models.ProjectIdeas;
using ProjectManagement.ViewModels.Workspace;

namespace ProjectManagement.Services.Workspace;

public sealed class ProjectOfficerWorkspaceService
{
    private readonly ApplicationDbContext _db;
    private readonly UserManager<ApplicationUser> _users;
    private readonly ProjectRecordHealthService _health;
    private readonly WorkspaceNudgeService _nudges;
    public ProjectOfficerWorkspaceService(ApplicationDbContext db, UserManager<ApplicationUser> users, ProjectRecordHealthService health, WorkspaceNudgeService nudges) { _db = db; _users = users; _health = health; _nudges = nudges; }

    // SECTION: Workspace composition
    public async Task<ProjectOfficerWorkspaceVm> GetProjectOfficerWorkspaceAsync(string userId, ClaimsPrincipal principal, CancellationToken ct)
    {
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var monthStart = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, 1, 0, 0, 0, DateTimeKind.Utc);
        var user = await _users.FindByIdAsync(userId);
        var projects = await _db.Projects.AsNoTracking().Include(p => p.ProjectStages).Include(p => p.Remarks).Include(p => p.Documents).Where(p => p.LeadPoUserId == userId && !p.IsDeleted && p.LifecycleStatus != ProjectLifecycleStatus.Completed).OrderBy(p => p.Name).Take(50).ToListAsync(ct);
        var tasks = await _db.ActionTasks.AsNoTracking().Where(t => !t.IsDeleted && t.AssignedToUserId == userId && t.Status != ActionTaskStatuses.Closed).OrderBy(t => t.DueDate).Take(8).Select(t => new WorkspaceTaskVm { TaskId = t.Id, Title = t.Title, Priority = t.Priority, Status = t.Status, DueDateUtc = DateTime.SpecifyKind(t.DueDate, DateTimeKind.Utc), IsOverdue = t.DueDate.Date < DateTime.UtcNow.Date && t.Status != ActionTaskStatuses.Closed, DaysOverdue = t.DueDate.Date < DateTime.UtcNow.Date ? (DateTime.UtcNow.Date - t.DueDate.Date).Days : null, OpenUrl = $"/ActionTasks?viewMode=MyWork&taskId={t.Id}" }).ToListAsync(ct);
        var ideas = await _db.ProjectIdeas.AsNoTracking().Include(i => i.Comments).Include(i => i.Documents).Where(i => !i.IsDeleted && (i.AssignedProjectOfficerUserId == userId || i.CreatedByUserId == userId) && i.Status != ProjectIdeaStatuses.Archived).OrderByDescending(i => i.UpdatedAt).Take(6).ToListAsync(ct);
        var ideaVms = ideas.Select(i => { var last = new[] { i.UpdatedAt }.Concat(i.Comments.Where(c => !c.IsDeleted).Select(c => c.CreatedAt)).Concat(i.Documents.Where(d => !d.IsDeleted).Select(d => d.UploadedAt)).DefaultIfEmpty(i.UpdatedAt).Max(); return new WorkspaceIdeaVm { IdeaId = i.Id, Title = i.Title, Status = ProjectIdeaStatuses.ToDisplay(i.Status), LastActivityAtUtc = last, NeedsUpdate = (DateTime.UtcNow.Date - last.Date).Days > 15 && (i.Status == ProjectIdeaStatuses.Active || i.Status == ProjectIdeaStatuses.OnHold), CommentCount = i.Comments.Count(c => !c.IsDeleted), DocumentCount = i.Documents.Count(d => !d.IsDeleted), OpenUrl = $"/ProjectIdeas/Details/{i.Id}" }; }).ToList();
        var reminders = await _db.TodoItems.AsNoTracking().Where(t => t.OwnerId == userId && t.Status != TodoStatus.Done && t.DeletedUtc == null).OrderByDescending(t => t.IsPinned).ThenBy(t => t.DueAtUtc).Take(5).Select(t => new WorkspaceReminderVm { ReminderId = t.Id, Title = t.Title, Priority = t.Priority.ToString(), DueAtUtc = t.DueAtUtc, IsPinned = t.IsPinned, OpenUrl = "/Tasks" }).ToListAsync(ct);
        var health = await _health.CalculateForProjectsAsync(projects, userId, ct);
        var pending = _nudges.BuildPendingWithMe(projects, tasks, ideaVms, userId, today);
        var matrix = projects.Take(6).Select(p => BuildMatrixRow(p, health[p.Id], userId, today)).ToList();
        var engagement = await BuildEngagementAsync(userId, user, monthStart, ct);
        var avgHealth = health.Count == 0 ? 100 : (int)Math.Round(health.Values.Average(h => h.HealthPercent));
        var vm = new ProjectOfficerWorkspaceVm { UserDisplayName = string.IsNullOrWhiteSpace(user?.FullName) ? principal.Identity?.Name ?? "Project Officer" : user.FullName, PortfolioHealthPercent = avgHealth, PortfolioHealthLabel = avgHealth >= 80 ? "Good" : avgHealth >= 60 ? "Attention" : "Needs Work", AssignedProjectCount = projects.Count, PendingWithMeCount = pending.Count, OverdueTaskCount = tasks.Count(t => t.IsOverdue), RecordGapCount = health.Values.Sum(h => h.Gaps.Count), AssignedIdeaCount = ideaVms.Count, Engagement = engagement, PendingWithMe = pending.Take(5).ToList(), ProjectMatrix = matrix, OfficialTasks = tasks.Take(5).ToList(), Ideas = ideaVms.Take(4).ToList(), RecordHealth = health.Values.OrderBy(h => h.HealthPercent).Take(5).ToList(), PersonalReminders = reminders, QuickActions = BuildQuickActions() };
        vm.Kpis = BuildKpis(vm);
        return vm;
    }

    private WorkspaceProjectMatrixRowVm BuildMatrixRow(Project p, WorkspaceRecordHealthVm health, string userId, DateOnly today)
    { var stage = WorkspaceNudgeService.GetCurrentStage(p); var action = _nudges.GetNextAction(p, health, userId, today, out var url); var last = WorkspaceNudgeService.LastPoRemark(p, userId); var overdue = _nudges.IsCurrentStageOverdue(stage, today); var issue = _nudges.HasCurrentStageTimelineIssue(stage); return new WorkspaceProjectMatrixRowVm { ProjectId = p.Id, ProjectName = p.Name, CurrentStageCode = stage?.StageCode ?? "—", CurrentStageName = stage?.StageCode ?? "Not started", DaysInCurrentStage = stage?.ActualStart is { } start ? today.DayNumber - start.DayNumber : null, UpdateStatus = _nudges.GetUpdateStatus(last, today), TimelineStatus = p.ProjectStages.Any(s => s.RequiresBackfill) || overdue ? "ActionRequired" : issue ? "Attention" : "Ok", RecordStatus = health.HealthPercent >= 80 ? "Ok" : health.HealthPercent >= 60 ? "Attention" : "ActionRequired", RecordHealthPercent = health.HealthPercent, RecordGapCount = health.Gaps.Count, LastPoRemarkAtUtc = last, HasBackfill = p.ProjectStages.Any(s => s.RequiresBackfill), HasCurrentStageIssue = issue, HasOverdueCurrentStage = overdue, NextActionText = action, NextActionUrl = url, OpenUrl = $"/Projects/Overview/{p.Id}", AddRemarkUrl = $"/Projects/Remarks/Index?projectId={p.Id}", TimelineUrl = $"/Projects/Timeline/EditPlan/{p.Id}" }; }
    private async Task<WorkspaceEngagementVm> BuildEngagementAsync(string userId, ApplicationUser? user, DateTime monthStart, CancellationToken ct) { var auth = await _db.AuthEvents.AsNoTracking().Where(a => a.UserId == userId && a.WhenUtc >= monthStart).Select(a => a.WhenUtc.UtcDateTime.Date).ToListAsync(ct); var audit = await _db.AuditLogs.AsNoTracking().Where(a => a.UserId == userId && a.TimeUtc >= monthStart).Select(a => a.TimeUtc.Date).ToListAsync(ct); var remarks = await _db.Remarks.AsNoTracking().CountAsync(r => r.AuthorUserId == userId && !r.IsDeleted && r.CreatedAtUtc >= monthStart, ct); var taskUpdates = await _db.ActionTaskAuditLogs.AsNoTracking().CountAsync(a => a.PerformedByUserId == userId && a.PerformedAt >= monthStart, ct); return new WorkspaceEngagementVm { LastLoginUtc = user?.LastLoginUtc, LastActivityUtc = audit.Concat(auth).OrderByDescending(d => d).Select(d => (DateTime?)d).FirstOrDefault() ?? user?.LastLoginUtc, LoginsThisMonth = auth.Count, ActiveDaysThisMonth = auth.Concat(audit).Distinct().Count(), ActionsRecordedThisMonth = audit.Count + remarks + taskUpdates, RemarksPostedThisMonth = remarks, TasksUpdatedThisMonth = taskUpdates, EngagementLabel = auth.Concat(audit).Distinct().Count() >= 8 ? "Active" : "Getting Started" }; }
    private static IReadOnlyList<WorkspaceQuickActionVm> BuildQuickActions() => new[] { new WorkspaceQuickActionVm { Text = "Add Project Remark", Url = "/Projects/Ongoing", Icon = "bi-chat-left-text" }, new WorkspaceQuickActionVm { Text = "Update Current Stage", Url = "/Projects/Ongoing", Icon = "bi-calendar-check" }, new WorkspaceQuickActionVm { Text = "Upload Project Document", Url = "/Projects/Ongoing", Icon = "bi-upload" }, new WorkspaceQuickActionVm { Text = "View My Official Tasks", Url = "/ActionTasks?viewMode=MyWork", Icon = "bi-list-task" }, new WorkspaceQuickActionVm { Text = "Open Project Ideas", Url = "/ProjectIdeas", Icon = "bi-lightbulb" }, new WorkspaceQuickActionVm { Text = "Open Personal Reminders", Url = "/Tasks", Icon = "bi-pin-angle" } };
    private static IReadOnlyList<WorkspaceKpiVm> BuildKpis(ProjectOfficerWorkspaceVm vm) => new[] { new WorkspaceKpiVm { Title = "Portfolio Health", Value = $"{vm.PortfolioHealthPercent}%", Caption = vm.PortfolioHealthLabel, Severity = vm.PortfolioHealthPercent >= 80 ? "Good" : vm.PortfolioHealthPercent >= 60 ? "Warning" : "Danger", Icon = "bi-heart-pulse" }, new WorkspaceKpiVm { Title = "Pending With Me", Value = vm.PendingWithMeCount.ToString(), Caption = "Actionable nudges", Severity = vm.PendingWithMeCount == 0 ? "Good" : "Warning", Icon = "bi-inbox" }, new WorkspaceKpiVm { Title = "Overdue Tasks", Value = vm.OverdueTaskCount.ToString(), Caption = "Official tasks", Severity = vm.OverdueTaskCount == 0 ? "Good" : "Danger", Icon = "bi-exclamation-triangle" }, new WorkspaceKpiVm { Title = "Record Gaps", Value = vm.RecordGapCount.ToString(), Caption = "Current-stage focused", Severity = vm.RecordGapCount == 0 ? "Good" : "Warning", Icon = "bi-folder-check" }, new WorkspaceKpiVm { Title = "ERP Engagement", Value = vm.Engagement.ActiveDaysThisMonth.ToString(), Caption = "Active days this month", Severity = "Info", Icon = "bi-activity" } };
}
