using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProjectManagement.Models;
using ProjectManagement.Services.ActionTasks;

namespace ProjectManagement.Pages.ActionTasks;

[Authorize(Policy = "ActionTracker.Access")]
public class IndexModel : PageModel
{
    private static readonly Regex AutoGeneratedSprintNamePattern = new(@"^(?:Sprint|Planning\s+Window)\s+(?<range>\d{1,2}\s+[A-Za-z]{3}(?:\s+\d{4})?\s*-\s*\d{1,2}\s+[A-Za-z]{3}(?:\s+\d{4})?)$", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    private readonly IActionTaskService _service;
    private readonly IActionTaskCollaborationService _collaborationService;
    private readonly ActionTaskPermissionService _permission;
    private readonly ActionSprintService _sprintService;
    private readonly ActionTaskWorkspaceBuilder _workspaceBuilder;
    private readonly ActionTaskWorkflowPolicy _workflowPolicy;
    private readonly ActionTaskRouteStateHelper _routeStateHelper;
    private readonly ActionTaskMyWorkQueueBuilder _myWorkQueueBuilder;
    private readonly ActionTaskCommandCentreSummaryBuilder _commandCentreSummaryBuilder;
    private readonly ActionTaskSprintWorkspaceSummaryBuilder _sprintWorkspaceSummaryBuilder;
    private readonly ActionTaskSprintBoardStateBuilder _sprintBoardStateBuilder;
    private readonly ActionTaskInspectorReadModelBuilder _inspectorBuilder;
    private readonly IActionTrackerClock _clock;
    private readonly ActionTaskUserLookupService _userLookup;
    private readonly UserManager<ApplicationUser> _users;

    public IndexModel(IActionTaskService service, IActionTaskCollaborationService collaborationService, ActionTaskPermissionService permission, ActionSprintService sprintService, ActionTaskWorkspaceBuilder workspaceBuilder, ActionTaskWorkflowPolicy workflowPolicy, ActionTaskRouteStateHelper routeStateHelper, ActionTaskMyWorkQueueBuilder myWorkQueueBuilder, ActionTaskCommandCentreSummaryBuilder commandCentreSummaryBuilder, ActionTaskSprintWorkspaceSummaryBuilder sprintWorkspaceSummaryBuilder, ActionTaskSprintBoardStateBuilder sprintBoardStateBuilder, ActionTaskInspectorReadModelBuilder inspectorBuilder, ActionTaskUserLookupService userLookup, IActionTrackerClock clock, UserManager<ApplicationUser> users)
    {
        _service = service;
        _collaborationService = collaborationService;
        _permission = permission;
        _sprintService = sprintService;
        _workspaceBuilder = workspaceBuilder;
        _workflowPolicy = workflowPolicy;
        _routeStateHelper = routeStateHelper;
        _myWorkQueueBuilder = myWorkQueueBuilder;
        _commandCentreSummaryBuilder = commandCentreSummaryBuilder;
        _sprintWorkspaceSummaryBuilder = sprintWorkspaceSummaryBuilder;
        _sprintBoardStateBuilder = sprintBoardStateBuilder;
        _inspectorBuilder = inspectorBuilder;
        _userLookup = userLookup;
        _clock = clock;
        _users = users;
        DirectTaskInput.DueDate = _clock.IstToday.AddDays(7);
        BacklogItemInput.TargetDate = _clock.IstToday.AddDays(7);
        SprintInput = CreateSprintInput.FromSprint(_clock.IstToday);
    }

    // SECTION: Clock-backed view dates keep Razor defaults aligned with server-side validation.
    public DateTime IstToday => _clock.IstToday;

    public IReadOnlyList<ActionTaskItem> Tasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> CriticalOpenTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> OverdueTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> RecentlySubmittedTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> RecentlyUpdatedTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> DueTodayTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> DueThisWeekTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> DueLaterTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> SprintOverdueTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> BacklogTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> OutsideSprintTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> SelectedSprintTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionTaskItem> SprintBacklogTasks { get; private set; } = Array.Empty<ActionTaskItem>();
    public IReadOnlyList<ActionSprint> Sprints { get; private set; } = Array.Empty<ActionSprint>();
    public ActionSprint? ActiveSprint { get; private set; }
    public ActionSprint? SelectedSprint { get; private set; }
    public ActionTaskQueryService.ActionSprintSummary SprintSummary { get; private set; } = ActionTaskQueryService.ActionSprintSummary.Empty;
    public ActionTaskQueryService.ActionSprintClosureReview SprintClosureReview { get; private set; } = ActionTaskQueryService.ActionSprintClosureReview.Empty;
    public ActionTaskQueryService.ActiveSprintOperationalMetrics ActiveSprintMetrics { get; private set; } = ActionTaskQueryService.ActiveSprintOperationalMetrics.Empty;
    public IReadOnlyList<ActionTaskAuditLog> SelectedTaskLogs { get; private set; } = Array.Empty<ActionTaskAuditLog>();
    public IReadOnlyList<ActionSprintAuditLog> SprintAuditHistory { get; private set; } = Array.Empty<ActionSprintAuditLog>();
    public IReadOnlyList<ActionTaskUpdate> SelectedTaskUpdates { get; private set; } = Array.Empty<ActionTaskUpdate>();
    public DateTime? SelectedTaskLastActivityAtUtc { get; private set; }
    public IReadOnlyDictionary<int, IReadOnlyList<ActionTaskAttachmentMetadata>> UpdateAttachments { get; private set; } = new Dictionary<int, IReadOnlyList<ActionTaskAttachmentMetadata>>();
    public IReadOnlyList<UserOption> AssignableUsers { get; private set; } = Array.Empty<UserOption>();
    public IReadOnlyDictionary<string, string> TaskAssigneeNames { get; private set; } = new Dictionary<string, string>(StringComparer.Ordinal);
    public IReadOnlyDictionary<string, string> TaskActorNames { get; private set; } = new Dictionary<string, string>(StringComparer.Ordinal);
    public IReadOnlyDictionary<string, string> SprintActorNames { get; private set; } = new Dictionary<string, string>(StringComparer.Ordinal);
    public IReadOnlyList<CountSummary> AssigneePendingCounts { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> PriorityCounts { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> StatusCounts { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> OpenAgeingBuckets { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> OverdueAgeingBuckets { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> BacklogAgeingBuckets { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> AssignedTaskAgeingBuckets { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> BucketDistribution { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<ResponsibleWorkloadSummary> ResponsiblePersonWorkloads { get; private set; } = Array.Empty<ResponsibleWorkloadSummary>();
    public IReadOnlyList<CountSummary> OutsideSprintWorkloadCounts { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<SprintPerformanceSummary> SprintPerformanceRows { get; private set; } = Array.Empty<SprintPerformanceSummary>();
    public IReadOnlyList<InvalidTaskStateSummary> InvalidStateRows { get; private set; } = Array.Empty<InvalidTaskStateSummary>();
    public ActionTaskReportSummary WorkloadSummary { get; private set; } = new();
    public IReadOnlyList<CountSummary> CarryForwardBySprint { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<CountSummary> BlockedAgeingBuckets { get; private set; } = Array.Empty<CountSummary>();
    public int ReportFilteredTaskCount { get; private set; }
    public int ReportTotalTaskCount { get; private set; }
    public ActionTaskMyWorkQueueReadModel MyWorkQueue { get; private set; } = EmptyMyWorkQueue;
    public ActionTaskCommandCentreSummary CommandCentreSummary { get; private set; } = ActionTaskCommandCentreSummary.Empty;
    public ActionTaskSprintWorkspaceSummary SprintWorkspaceSummary { get; private set; } = ActionTaskSprintWorkspaceSummary.Empty;


    [BindProperty(SupportsGet = true)]
    public string? ViewMode { get; set; } = "CommandCentre";

    [BindProperty(SupportsGet = true)]
    public int? TaskId { get; set; }

    [BindProperty(SupportsGet = true)]
    public int? SelectedSprintId { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? PlanningView { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? PlanningTab { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? TaskScope { get; set; } = ActionTaskRegisterScopes.Open;

    [BindProperty(SupportsGet = true)]
    public string? FilterStatus { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? FilterBucket { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? FilterPriority { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? FilterAssigneeUserId { get; set; }

    [BindProperty(SupportsGet = true)]
    public DateTime? FilterDueDate { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? FilterSearch { get; set; }
    [BindProperty(SupportsGet = true)]
    public string? SortBy { get; set; }
    [BindProperty(SupportsGet = true)]
    public string? SortDir { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? ReportBucket { get; set; }

    [BindProperty(SupportsGet = true)]
    public int? ReportSprintId { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? ReportAssigneeUserId { get; set; }

    [BindProperty(SupportsGet = true)]
    public DateTime? ReportFromDate { get; set; }

    [BindProperty(SupportsGet = true)]
    public DateTime? ReportToDate { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? ReportStatus { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? ReportPriority { get; set; }

    public string CurrentRole { get; private set; } = string.Empty;
    public string CurrentUserId { get; private set; } = string.Empty;
    public bool ShowCreateModal { get; private set; }

    [BindProperty]
    public string CreateMode { get; set; } = "backlog";

    public bool ShowCreateSprintPanel { get; private set; }
    public bool ShowEditSprintPanel { get; private set; }
    public bool ShowCreateNextSprintPanel { get; private set; }
    public ActionTaskItem? SelectedTask { get; private set; }

    [BindProperty]
    public CreateDirectTaskInput DirectTaskInput { get; set; } = new();

    [BindProperty]
    public CreateBacklogItemInput BacklogItemInput { get; set; } = new();
    [BindProperty]
    public AddTaskUpdateInput UpdateInput { get; set; } = new();

    [BindProperty]
    public ChangeTaskDateInput ChangeDateInput { get; set; } = new();

    [BindProperty]
    public CreateSprintInput SprintInput { get; set; } = new();

    [BindProperty]
    public UpdateSprintInput SprintEditInput { get; set; } = new();

    [BindProperty]
    public CreateNextSprintInput NextSprintInput { get; set; } = new();

    [BindProperty]
    public SprintClosureInput ClosureInput { get; set; } = new();

    // SECTION: UI state projections
    public bool CanCreate => _permission.CanCreate(CurrentRole);
    public bool CanClose => _permission.CanClose(CurrentRole);
    public string ResolvedViewMode => ResolveViewMode();
    public string ResolvedPlanningView => ResolvePlanningView();
    public string ResolvedPlanningTab => ResolvePlanningTab();
    public bool IsCommandCentreView => string.Equals(ResolvedViewMode, "CommandCentre", StringComparison.OrdinalIgnoreCase);
    public bool IsPlanningView => string.Equals(ResolvedViewMode, "Planning", StringComparison.OrdinalIgnoreCase);
    public bool IsMyWorkView => string.Equals(ResolvedViewMode, "MyWork", StringComparison.OrdinalIgnoreCase);
    public bool IsRegisterView => string.Equals(ResolvedViewMode, "Register", StringComparison.OrdinalIgnoreCase);
    public bool IsReportsView => string.Equals(ResolvedViewMode, "Reports", StringComparison.OrdinalIgnoreCase);

    // SECTION: Legacy view-state aliases retained for existing partials, tests and links.
    public bool IsDashboardView => IsCommandCentreView;
    public bool IsMyTasksView => IsMyWorkView;
    public bool IsTaskListView => IsRegisterView;
    public bool IsKanbanView => false;
    public bool IsSprintBoardView => IsPlanningView && string.Equals(ResolvedPlanningView, "DueExceptions", StringComparison.OrdinalIgnoreCase);
    public bool IsPlanningPlanTab => IsPlanningView && string.Equals(ResolvedPlanningTab, "Plan", StringComparison.OrdinalIgnoreCase);
    public bool IsPlanningExecuteTab => IsPlanningView && string.Equals(ResolvedPlanningTab, "Execute", StringComparison.OrdinalIgnoreCase);
    public bool IsPlanningCloseTab => IsPlanningView && string.Equals(ResolvedPlanningTab, "Close", StringComparison.OrdinalIgnoreCase);
    public bool IsBacklogView => IsLegacyViewMode("Backlog") || IsPlanningBacklogFilterContext();
    public bool IsSprintsView => IsPlanningView;
    public string PageHeading => ResolvedViewMode switch
    {
        "Planning" => "Board",
        "MyWork" => "My Tasks",
        "Register" => "All Tasks",
        "Reports" => "Reports",
        _ => "Overview"
    };
    public string PageSubtitle => ResolvedViewMode switch
    {
        "Planning" => "Track work in the current sprint.",
        "MyWork" => "Your assigned work, ordered by what needs attention first.",
        "Register" => "Find any task. Use filters only when you need them.",
        "Reports" => "Review workload, ageing and sprint performance.",
        _ => "What needs attention now."
    };

    public IReadOnlyList<string> AssignmentRoles => ActionTaskRoleResolver.AllowedAssignmentRoles();
    public IReadOnlyList<string> AllowedStatusOptions => _workflowPolicy.AllowedStatusOptions;
    public string ResolvedTaskScope => ActionTaskRegisterScopes.Normalize(TaskScope);
    public bool IsOpenTaskScope => ActionTaskRegisterScopes.IsOpenScope(ResolvedTaskScope);
    public IReadOnlyList<string> RegisterStatusOptions => new[]
    {
        ActionTaskStatuses.Backlog,
        ActionTaskStatuses.Assigned,
        ActionTaskStatuses.InProgress,
        ActionTaskStatuses.Blocked,
        ActionTaskStatuses.Submitted,
        ActionTaskStatuses.Closed
    }.Where(status => !IsOpenTaskScope || !string.Equals(status, ActionTaskStatuses.Closed, StringComparison.OrdinalIgnoreCase)).ToList();
    public IReadOnlyList<(string Value, string Label)> RegisterBucketOptions => new[]
    {
        (Value: "Backlog", Label: "Backlog"),
        (Value: "OutsideSprint", Label: "Outside Sprint"),
        (Value: "Sprint", Label: "Sprint"),
        (Value: "Closed", Label: "Closed"),
        (Value: "Invalid", Label: "Invalid State")
    }.Where(bucket => !IsOpenTaskScope || !string.Equals(bucket.Value, "Closed", StringComparison.OrdinalIgnoreCase)).ToList();
    public IReadOnlyList<string> ReportStatusOptions => new[]
    {
        ActionTaskStatuses.Backlog,
        ActionTaskStatuses.Assigned,
        ActionTaskStatuses.InProgress,
        ActionTaskStatuses.Blocked,
        ActionTaskStatuses.Submitted,
        ActionTaskStatuses.Closed
    };
    public IReadOnlyList<string> PriorityOptions => _workflowPolicy.PriorityOptions;
    public bool CanPlanSprints => _permission.CanManageSprints(CurrentRole);
    public bool CanFilterByAssignee => _permission.CanViewAll(CurrentRole);
    public IReadOnlyList<ActionSprint> AssignableSprints => Sprints.Where(s => s.Status != ActionSprintStatus.Closed).ToList();
    public IReadOnlyList<ActionSprint> ClosureTargetSprints => SprintClosureReview.TargetSprintOptions;
    public bool CanActivateSelectedSprint => CanPlanSprints && SelectedSprint?.Status == ActionSprintStatus.Planned;
    public bool CanEditSelectedSprint => CanPlanSprints && SelectedSprint is not null && SelectedSprint.Status != ActionSprintStatus.Closed;
    public bool CanCloseSelectedSprintDirectly => CanReviewSprintClosure && SprintClosureReview.CanCloseDirectly;
    public bool ShouldShowCreateNextSprint => CanReviewSprintClosure && SprintClosureReview.UnfinishedTasks.Any() && !ClosureTargetSprints.Any();

    // SECTION: Sprint planning visibility helpers for lifecycle-aware UI actions.
    public bool CanAssignTaskToSprint(ActionTaskItem task)
    {
        return _permission.CanAssignTaskToSprint(CurrentRole)
               && IsBacklogTask(task)
               && AssignableSprints.Any();
    }

    public bool IsBacklogTask(ActionTaskItem task)
        => ActionTaskCategorization.IsBacklogTask(task);

    public bool CanAddOutsideSprintTaskToSprint(ActionTaskItem task)
    {
        return _permission.CanAssignTaskToSprint(CurrentRole)
               && ActionTaskCategorization.IsOutsideSprintTask(task)
               && AssignableSprints.Any();
    }

    public string DisplayBucketFilter(string bucket)
        => bucket switch
        {
            "Backlog" => "Backlog",
            "OutsideSprint" => "Outside Sprint",
            "Sprint" => "Sprint",
            "Closed" => "Closed",
            "Invalid" => "Invalid State",
            _ => bucket
        };
    public bool CanMoveTaskToBacklog(ActionTaskItem task)
    {
        if (!_permission.CanMoveTaskToBacklog(CurrentRole)
            || string.Equals(task.Status, ActionTaskStatuses.Closed, StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        if (!task.SprintId.HasValue)
        {
            return ActionTaskCategorization.IsOutsideSprintTask(task);
        }

        var sprint = Sprints.FirstOrDefault(s => s.Id == task.SprintId.Value);
        return sprint is not null && sprint.Status != ActionSprintStatus.Closed;
    }

    public bool CanModifySelectedSprint =>
        CanPlanSprints && SelectedSprint is not null && SelectedSprint.Status != ActionSprintStatus.Closed;

    public bool CanReviewSprintClosure =>
        CanPlanSprints
        && SelectedSprint is not null
        && SelectedSprint.Status == ActionSprintStatus.Active;

    // SECTION: Selected-task projection helper
    public bool IsSelectedTask(ActionTaskItem task)
    {
        return TaskId.HasValue && TaskId.Value == task.Id;
    }

    // SECTION: Per-task action visibility helpers
    public bool CanSubmitTask(ActionTaskItem task)
    {
        return _workflowPolicy.CanSubmitTask(task, CurrentUserId);
    }

    public bool CanCloseTask(ActionTaskItem task)
    {
        return _workflowPolicy.CanCloseTask(task, CurrentRole);
    }

    public bool CanCloseTaskDirectly(ActionTaskItem task)
    {
        return _permission.CanCloseTaskDirectly(task, CurrentRole);
    }

    public bool CanUpdateTaskStatus(ActionTaskItem task)
    {
        return _workflowPolicy.CanUpdateTaskStatus(task, CurrentRole, CurrentUserId);
    }

    public bool CanAddProgressUpdate(ActionTaskItem task)
    {
        return !string.Equals(task.Status, ActionTaskStatuses.Closed, StringComparison.OrdinalIgnoreCase)
            && _permission.CanAddTaskUpdate(CurrentRole, CurrentUserId, task.AssignedToUserId);
    }

    public IReadOnlyList<string> GetAllowedStatusTargets(ActionTaskItem task)
    {
        return _workflowPolicy.GetAllowedStatusTargets(task, CurrentRole, CurrentUserId);
    }

    public DateTime GetSelectedTaskLastActivityUtc()
    {
        return SelectedTaskLastActivityAtUtc ?? SelectedTask?.AssignedOn ?? DateTime.MinValue;
    }

    public bool CanChangeTaskDate(ActionTaskItem task)
    {
        return _workflowPolicy.CanChangeTaskDate(task, CurrentRole);
    }

    public bool CanViewSelectedTaskSystemHistory()
    {
        return _workflowPolicy.CanViewSystemHistory(CurrentRole);
    }

    public string DisplayAuditActionLabel(string actionType)
    {
        if (string.IsNullOrWhiteSpace(actionType))
        {
            return "System Event";
        }

        return actionType switch
        {
            "TaskCreated" => "Task created",
            "BacklogItemCreated" => "Backlog item created",
            "TaskAssignedToSprint" => "Added to sprint",
            "OutsideSprintTaskAssignedToSprint" => "Added to sprint",
            "TaskRemovedFromSprintKeepAssigned" => "Removed from sprint, kept assigned",
            "TaskMovedToBacklogRemoveAssignee" => "Moved to backlog",
            "TaskCarriedForward" => "Carried forward",
            "TaskUpdated" => "Task updated",
            "TaskClosedByCommandAuthority" => "Closed by command authority",
            "Submitted" => "Submitted for closure",
            "TaskSubmitted" => "Submitted for closure",
            "Closed" => "Closed",
            "TaskClosed" => "Closed",
            "StatusUpdated" => "Status changed",
            "TaskStatusChanged" => "Status changed",
            "DueDateChanged" => "Due date changed",
            "TargetDateChanged" => "Target date changed",
            "TaskDueDateChanged" => "Due date changed",
            _ => Regex.Replace(actionType, "(?<!^)([A-Z])", " $1")
        };
    }

    public string DisplayAuditPlainLanguage(ActionTaskAuditLog log)
    {
        // SECTION: Convert common audit values into reader-friendly system history text while leaving raw values collapsed.
        return log.ActionType switch
        {
            "StatusUpdated" or "TaskStatusChanged" => $"Status changed from {log.OldValue ?? "previous status"} to {log.NewValue ?? "new status"}.",
            "Submitted" or "TaskSubmitted" => "Task submitted for closure review.",
            "Closed" or "TaskClosed" => "Task closed after review.",
            "TaskClosedByCommandAuthority" => "Closed by command authority.",
            "DueDateChanged" or "TaskDueDateChanged" => $"Due date changed from {FormatAuditDate(log.OldValue)} to {FormatAuditDate(log.NewValue)}.",
            "TargetDateChanged" => $"Target date changed from {FormatAuditDate(log.OldValue)} to {FormatAuditDate(log.NewValue)}.",
            "TaskAssignedToSprint" or "OutsideSprintTaskAssignedToSprint" => "Task added to sprint. Responsible person retained.",
            "TaskRemovedFromSprintKeepAssigned" => "Task removed from sprint and kept assigned as Outside Sprint work.",
            "TaskMovedToBacklogRemoveAssignee" => "Task moved to backlog and assignee removed.",
            "BacklogItemCreated" => "Backlog item created.",
            "TaskCreated" => "Task created.",
            _ => DisplayAuditActionLabel(log.ActionType)
        };
    }

    private static string FormatAuditDate(string? value)
    {
        return DateTime.TryParse(value, out var parsed)
            ? parsed.ToString("dd MMM yyyy")
            : string.IsNullOrWhiteSpace(value) ? "—" : value;
    }

    public string GetStatusBadgeClass(string status)
    {
        return _workflowPolicy.GetStatusBadgeClass(status);
    }

    public string GetPriorityBadgeClass(string priority)
    {
        return _workflowPolicy.GetPriorityBadgeClass(priority);
    }

    public string ResolveAssigneeName(string assignedToUserId)
    {
        if (string.IsNullOrWhiteSpace(assignedToUserId))
        {
            return "Unassigned";
        }

        return TaskAssigneeNames.TryGetValue(assignedToUserId, out var assigneeName)
            ? assigneeName
            : "User";
    }

    public string ResolveSprintName(int? sprintId)
    {
        if (!sprintId.HasValue)
        {
            return "Backlog";
        }

        var sprint = Sprints.FirstOrDefault(s => s.Id == sprintId.Value);
        return sprint is null ? $"Sprint #{sprintId.Value}" : DisplaySprintName(sprint);
    }

    public string DisplaySprintName(ActionSprint? sprint)
    {
        // SECTION: Normalize known auto-generated sprint labels while preserving user-authored names.
        if (sprint is null)
        {
            return "Sprint";
        }

        var name = sprint.Name?.Trim();
        if (string.IsNullOrWhiteSpace(name))
        {
            return $"Sprint #{sprint.Id}";
        }

        var autoGeneratedMatch = AutoGeneratedSprintNamePattern.Match(name);
        return autoGeneratedMatch.Success
            ? $"Sprint {autoGeneratedMatch.Groups["range"].Value}"
            : name;
    }

    // SECTION: Task scope badges use official Sprint / Backlog / Outside Sprint bucket classification.
    public string GetSprintBadgeText(ActionTaskItem task)
        => ActionTaskCategorization.ResolveCategory(task) switch
        {
            ActionTaskWorkCategory.Sprint => ResolveSprintName(task.SprintId),
            ActionTaskWorkCategory.OutsideSprint => "Outside Sprint",
            ActionTaskWorkCategory.Closed => "Closed",
            ActionTaskWorkCategory.Invalid => "Invalid State",
            _ => "Backlog"
        };

    public string GetSprintBadgeClass(ActionTaskItem task)
        => ActionTaskCategorization.ResolveCategory(task) switch
        {
            ActionTaskWorkCategory.Sprint => "at-scope-badge at-scope-badge-sprint",
            ActionTaskWorkCategory.OutsideSprint => "at-scope-badge at-scope-badge-outside-sprint",
            ActionTaskWorkCategory.Closed => "at-scope-badge at-scope-badge-closed",
            ActionTaskWorkCategory.Invalid => "at-scope-badge at-scope-badge-invalid",
            _ => "at-scope-badge at-scope-badge-backlog"
        };

    public bool IsInvalidTaskState(ActionTaskItem task)
        => ActionTaskCategorization.ResolveCategory(task) == ActionTaskWorkCategory.Invalid;

    public bool MustReturnInvalidTaskToBacklogDuringClosure(ActionTaskItem task)
        => IsInvalidTaskState(task);

    public IReadOnlyList<TaskDisplayItem> GetSprintTasksByStatus(string status)
        => ToDisplayItems(SelectedSprintTasks.Where(t => string.Equals(t.Status, status, StringComparison.OrdinalIgnoreCase)).ToList());

    public string ResolveActorName(string performedByUserId)
    {
        return TaskActorNames.TryGetValue(performedByUserId, out var actorName)
            ? actorName
            : "User";
    }

    public string ResolveClosedByName(ActionTaskItem task)
    {
        return !string.IsNullOrWhiteSpace(task.ClosedByUserId) && TaskActorNames.TryGetValue(task.ClosedByUserId, out var actorName)
            ? actorName
            : "Command authority";
    }

    public string ResolveSprintActorName(string performedByUserId)
    {
        return SprintActorNames.TryGetValue(performedByUserId, out var actorName)
            ? actorName
            : "User";
    }

    public async Task OnGetAsync()
    {
        await LoadDataAsync();
    }

    // SECTION: Backward-compatible direct-task handler preserves existing Create posts.
    public Task<IActionResult> OnPostCreateAsync() => OnPostCreateDirectTaskAsync();

    // SECTION: Create assigned work outside a sprint.
    public async Task<IActionResult> OnPostCreateDirectTaskAsync()
    {
        await ResolveIdentityAsync();

        if (!_permission.CanCreate(CurrentRole))
        {
            return Forbid();
        }

        if (!ValidateCreateDirectTaskInput())
        {
            ShowCreateModal = true;
            await LoadDataAsync();
            return Page();
        }

        var assignedRole = await ResolveAssignableRoleForInputAsync(DirectTaskInput.AssignedToUserId);
        if (assignedRole is null)
        {
            ShowCreateModal = true;
            await LoadDataAsync();
            return Page();
        }

        await _service.CreateTaskAsync(new ActionTaskItem
        {
            Title = DirectTaskInput.Title.Trim(),
            Description = DirectTaskInput.Description.Trim(),
            CreatedByUserId = CurrentUserId,
            AssignedToUserId = DirectTaskInput.AssignedToUserId,
            CreatedByRole = CurrentRole,
            AssignedToRole = assignedRole,
            DueDate = DirectTaskInput.DueDate,
            Priority = DirectTaskInput.Priority
        });

        TempData["ToastMessage"] = "Direct task created outside sprint.";
        return RedirectToPage("/ActionTasks/Index", BuildTaskWorkspaceRouteValues(TaskId, SelectedSprintId));
    }

    // SECTION: Create unassigned backlog work for future planning.
    public async Task<IActionResult> OnPostCreateBacklogItemAsync()
    {
        await ResolveIdentityAsync();

        if (!_permission.CanCreate(CurrentRole))
        {
            return Forbid();
        }

        if (!ValidateCreateBacklogItemInput())
        {
            ShowCreateModal = true;
            await LoadDataAsync();
            return Page();
        }

        await _service.CreateBacklogItemAsync(new ActionTaskItem
        {
            Title = BacklogItemInput.Title.Trim(),
            Description = BacklogItemInput.Description.Trim(),
            CreatedByUserId = CurrentUserId,
            AssignedToUserId = string.Empty,
            CreatedByRole = CurrentRole,
            AssignedToRole = string.Empty,
            DueDate = BacklogItemInput.TargetDate,
            Priority = BacklogItemInput.Priority
        });

        TempData["ToastMessage"] = "Backlog item created.";
        return RedirectToPage("/ActionTasks/Index", BuildTaskWorkspaceRouteValues(TaskId, SelectedSprintId));
    }

    // SECTION: Create-task validation helpers keep backlog and direct-task flows isolated without duplicate form fields.
    private bool ValidateCreateDirectTaskInput()
    {
        ModelState.Clear();
        TryValidateModel(DirectTaskInput, nameof(DirectTaskInput));

        if (string.IsNullOrWhiteSpace(DirectTaskInput.AssignedToUserId))
        {
            ModelState.AddModelError(nameof(DirectTaskInput.AssignedToUserId), "Select an assignee for a direct task.");
        }

        if (DirectTaskInput.DueDate.Date < _clock.IstToday)
        {
            ModelState.AddModelError(nameof(DirectTaskInput.DueDate), "Due date cannot be in the past.");
        }

        return ModelState.IsValid;
    }

    private bool ValidateCreateBacklogItemInput()
    {
        ModelState.Clear();
        TryValidateModel(BacklogItemInput, nameof(BacklogItemInput));

        if (BacklogItemInput.TargetDate.Date < _clock.IstToday)
        {
            ModelState.AddModelError(nameof(BacklogItemInput.TargetDate), "Target date cannot be in the past.");
        }

        return ModelState.IsValid;
    }

    private bool ValidateChangeTaskDateInput()
    {
        // SECTION: Page-level date-change validation gives immediate feedback before service-level enforcement.
        ModelState.Clear();
        TryValidateModel(ChangeDateInput, nameof(ChangeDateInput));

        if (ChangeDateInput.NewDate.Date < _clock.IstToday)
        {
            ModelState.AddModelError(nameof(ChangeDateInput.NewDate), "Task date cannot be in the past.");
        }

        if (string.IsNullOrWhiteSpace(ChangeDateInput.Remarks))
        {
            ModelState.AddModelError(nameof(ChangeDateInput.Remarks), "Enter a short reason for changing the task date.");
        }

        return ModelState.IsValid;
    }

    private async Task<string?> ResolveAssignableRoleForInputAsync(string assignedToUserId)
    {
        var assignedRole = await ResolveAssignableRoleForUserAsync(assignedToUserId);
        if (assignedRole is null)
        {
            ModelState.AddModelError(nameof(DirectTaskInput.AssignedToUserId), "Selected user cannot be assigned this task.");
        }

        return assignedRole;
    }

    private async Task<string?> ResolveAssignableRoleForUserAsync(string assignedToUserId)
    {
        if (string.IsNullOrWhiteSpace(assignedToUserId))
        {
            return null;
        }

        var assignedUser = await _users.FindByIdAsync(assignedToUserId);
        if (assignedUser is null || assignedUser.IsDisabled || assignedUser.PendingDeletion)
        {
            return null;
        }

        if (assignedUser.LockoutEnd.HasValue && assignedUser.LockoutEnd > new DateTimeOffset(_clock.UtcNow, TimeSpan.Zero))
        {
            return null;
        }

        var assignedRoles = await _users.GetRolesAsync(assignedUser);
        var assignedRole = ActionTaskRoleResolver.ResolveAssignableRoleFromRoles(assignedRoles);
        return assignedRole is not null && _permission.CanAssign(CurrentRole, assignedRole)
            ? assignedRole
            : null;
    }




    // SECTION: Create sprint from Sprint Board workspace through sprint service boundary.
    public async Task<IActionResult> OnPostCreateSprintAsync()
    {
        await ResolveIdentityAsync();
        ViewMode = "Planning";
        ModelState.Clear();
        TryValidateModel(SprintInput, nameof(SprintInput));
        ValidateSprintDateRange(SprintInput.StartDate, SprintInput.EndDate, nameof(SprintInput));

        if (!ModelState.IsValid)
        {
            ShowCreateSprintPanel = true;
            await LoadDataAsync();
            return Page();
        }

        try
        {
            var sprint = await _sprintService.CreateSprintAsync(new ActionSprint
            {
                Name = SprintInput.Name.Trim(),
                Goal = SprintInput.Goal?.Trim(),
                StartDate = SprintInput.StartDate,
                EndDate = SprintInput.EndDate
            }, CurrentUserId, CurrentRole);
            TempData["ToastMessage"] = "Sprint created.";
            return RedirectToPage(new { ViewMode = "Planning", SelectedSprintId = sprint.Id });
        }
        catch (InvalidOperationException ex)
        {
            ModelState.AddModelError(string.Empty, ex.Message);
            ShowCreateSprintPanel = true;
            await LoadDataAsync();
            return Page();
        }
    }

    // SECTION: Update selected non-closed sprint through sprint service boundary.
    public async Task<IActionResult> OnPostUpdateSprintAsync()
    {
        await ResolveIdentityAsync();
        ViewMode = "Planning";
        SelectedSprintId = SprintEditInput.SprintId;
        ModelState.Clear();
        TryValidateModel(SprintEditInput, nameof(SprintEditInput));
        ValidateSprintDateRange(SprintEditInput.StartDate, SprintEditInput.EndDate, nameof(SprintEditInput));

        if (!ModelState.IsValid)
        {
            ShowEditSprintPanel = true;
            await LoadDataAsync();
            return Page();
        }

        try
        {
            await _sprintService.UpdateSprintAsync(
                SprintEditInput.SprintId,
                DecodeSprintRowVersion(SprintEditInput.RowVersion),
                SprintEditInput.Name.Trim(),
                SprintEditInput.Goal?.Trim(),
                SprintEditInput.StartDate,
                SprintEditInput.EndDate,
                CurrentUserId,
                CurrentRole);
            TempData["ToastMessage"] = "Sprint updated.";
            return RedirectToPage(new { ViewMode = "Planning", SelectedSprintId = SprintEditInput.SprintId });
        }
        catch (ActionTaskConcurrencyException ex)
        {
            ModelState.AddModelError(string.Empty, ex.Message);
        }
        catch (InvalidOperationException ex)
        {
            ModelState.AddModelError(string.Empty, ex.Message);
        }

        ShowEditSprintPanel = true;
        await LoadDataAsync();
        return Page();
    }

    // SECTION: Activate a planned sprint through sprint service boundary.
    public async Task<IActionResult> OnPostActivateSprintAsync(int sprintId, string rowVersion)
    {
        await ResolveIdentityAsync();
        try
        {
            await _sprintService.ActivateSprintAsync(sprintId, DecodeSprintRowVersion(rowVersion), CurrentUserId, CurrentRole);
            TempData["ToastMessage"] = "Sprint activated.";
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToPage(new { ViewMode = "Planning", SelectedSprintId = sprintId });
    }

    // SECTION: Direct close for active sprints that have no unfinished task disposition requirement.
    public async Task<IActionResult> OnPostCloseSprintAsync(int sprintId, string rowVersion)
    {
        await ResolveIdentityAsync();
        try
        {
            await _sprintService.CloseSprintAsync(sprintId, DecodeSprintRowVersion(rowVersion), CurrentUserId, CurrentRole);
            TempData["ToastMessage"] = "Sprint closed.";
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToPage(new { ViewMode = "Planning", SelectedSprintId = sprintId });
    }

    // SECTION: Create next planned sprint from closure context through sprint service boundary.
    public async Task<IActionResult> OnPostCreateNextSprintAsync()
    {
        await ResolveIdentityAsync();
        ViewMode = "Planning";
        SelectedSprintId = NextSprintInput.SourceSprintId;
        ModelState.Clear();
        TryValidateModel(NextSprintInput, nameof(NextSprintInput));
        ValidateSprintDateRange(NextSprintInput.StartDate, NextSprintInput.EndDate, nameof(NextSprintInput));
        await ValidateNextSprintStartsAfterSourceSprintAsync();

        if (!ModelState.IsValid)
        {
            ShowCreateNextSprintPanel = true;
            await LoadDataAsync();
            return Page();
        }

        try
        {
            await _sprintService.CreateSprintAsync(new ActionSprint
            {
                Name = NextSprintInput.Name.Trim(),
                Goal = NextSprintInput.Goal?.Trim(),
                StartDate = NextSprintInput.StartDate,
                EndDate = NextSprintInput.EndDate
            }, CurrentUserId, CurrentRole);
            TempData["ToastMessage"] = "Next Sprint created and is available for carry-forward.";
            return RedirectToPage(new { ViewMode = "Planning", SelectedSprintId = NextSprintInput.SourceSprintId });
        }
        catch (InvalidOperationException ex)
        {
            ModelState.AddModelError(string.Empty, ex.Message);
            ShowCreateNextSprintPanel = true;
            await LoadDataAsync();
            return Page();
        }
    }

    // SECTION: Submit task for closure review
    public async Task<IActionResult> OnPostSubmitAsync(int id, string rowVersion, string? remarks)
    {
        await ResolveIdentityAsync();
        try
        {
            await _service.SubmitTaskAsync(id, DecodeRowVersion(rowVersion), CurrentUserId, CurrentRole, remarks);
            TempData["ToastMessage"] = "Task submitted for closure.";
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(id, SelectedSprintId);
    }

    // SECTION: Close task by command role
    public async Task<IActionResult> OnPostCloseAsync(int id, string rowVersion, string? remarks)
    {
        await ResolveIdentityAsync();
        try
        {
            await _service.CloseTaskDirectlyAsync(id, DecodeRowVersion(rowVersion), remarks ?? string.Empty, CurrentUserId, CurrentRole);
            TempData["ToastMessage"] = "Task closed successfully.";
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(id, SelectedSprintId);
    }

    // SECTION: Update in-flight status
    public async Task<IActionResult> OnPostUpdateStatusAsync(int id, string rowVersion, string status, string? remarks)
    {
        await ResolveIdentityAsync();
        try
        {
            // SECTION: Prevent no-op status submissions from showing a misleading success message.
            var task = await _service.GetTaskAsync(id);
            if (task is null)
            {
                TempData["ToastError"] = "Task not found.";
                return RedirectToTaskPage(id, SelectedSprintId);
            }

            // SECTION: Preserve permission enforcement even for status no-op submissions.
            if (!_permission.CanUpdateTask(CurrentRole, CurrentUserId, task.AssignedToUserId))
            {
                TempData["ToastError"] = "You are not authorized to update this task.";
                return RedirectToTaskPage(id, SelectedSprintId);
            }

            // SECTION: Keep no-op handling for user-friendly messaging after permission validation.
            var noOpMessage = _workflowPolicy.ValidateStatusUpdate(task, status);
            if (!string.IsNullOrWhiteSpace(noOpMessage))
            {
                TempData["ToastMessage"] = noOpMessage;
                return RedirectToTaskPage(id, SelectedSprintId);
            }

            await _service.UpdateStatusAsync(id, DecodeRowVersion(rowVersion), status, CurrentUserId, CurrentRole, remarks);
            TempData["ToastMessage"] = "Task status updated.";
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(id, SelectedSprintId);
    }

    // SECTION: Change a backlog target date or assigned task due date.
    public async Task<IActionResult> OnPostChangeTaskDateAsync()
    {
        await ResolveIdentityAsync();

        try
        {
            if (!ValidateChangeTaskDateInput())
            {
                TempData["ToastError"] = ModelState.Values
                    .SelectMany(value => value.Errors)
                    .Select(error => error.ErrorMessage)
                    .FirstOrDefault(error => !string.IsNullOrWhiteSpace(error))
                    ?? "Enter a valid task date.";
                return RedirectToTaskPage(ChangeDateInput.TaskId, SelectedSprintId);
            }

            await _service.UpdateTaskDateAsync(
                ChangeDateInput.TaskId,
                DecodeRowVersion(ChangeDateInput.RowVersion),
                ChangeDateInput.NewDate,
                CurrentUserId,
                CurrentRole,
                ChangeDateInput.Remarks);

            TempData["ToastMessage"] = "Task date updated.";
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(ChangeDateInput.TaskId, SelectedSprintId);
    }

    // SECTION: Assign backlog or visible task into an available sprint.
    public async Task<IActionResult> OnPostAssignToSprintAsync(int id, int sprintId, string responsibleUserId)
    {
        await ResolveIdentityAsync();

        try
        {
            var responsibleRole = await ResolveAssignableRoleForUserAsync(responsibleUserId);
            if (responsibleRole is null)
            {
                TempData["ToastError"] = "Select an active responsible person before adding the backlog item to a sprint.";
                return RedirectToTaskPage(id, SelectedSprintId);
            }

            await _sprintService.AssignBacklogItemToSprintAsync(id, sprintId, responsibleUserId, responsibleRole, CurrentUserId, CurrentRole);
            TempData["ToastMessage"] = "Backlog item added to sprint with a responsible person.";
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(id, sprintId);
    }

    // SECTION: Add Outside Sprint work to a sprint while retaining its responsible person.
    public async Task<IActionResult> OnPostAddOutsideSprintTaskToSprintAsync(int id, int sprintId)
    {
        await ResolveIdentityAsync();

        try
        {
            await _sprintService.AssignOutsideSprintTaskToSprintAsync(id, sprintId, CurrentUserId, CurrentRole);
            TempData["ToastMessage"] = "Outside Sprint task added to sprint.";
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(id, sprintId);
    }

    // SECTION: Remove a sprint task from sprint scope while preserving the responsible person.
    public async Task<IActionResult> OnPostRemoveFromSprintKeepAssignedAsync(int id, string? remarks)
    {
        await ResolveIdentityAsync();

        try
        {
            if (string.IsNullOrWhiteSpace(remarks))
            {
                TempData["ToastError"] = "Enter a short reason before removing the task from sprint.";
                return RedirectToTaskPage(id, SelectedSprintId);
            }

            await _sprintService.RemoveTaskFromSprintKeepAssignedAsync(id, CurrentUserId, CurrentRole, remarks);
            TempData["ToastMessage"] = "Task removed from sprint and kept assigned.";
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(id, SelectedSprintId);
    }

    // SECTION: Move a sprint or outside-sprint task to backlog by clearing sprint and assignee.
    public async Task<IActionResult> OnPostMoveToBacklogRemoveAssigneeAsync(int id, string? remarks)
    {
        await ResolveIdentityAsync();

        try
        {
            if (string.IsNullOrWhiteSpace(remarks))
            {
                TempData["ToastError"] = "Enter a short reason before moving the task to backlog.";
                return RedirectToTaskPage(id, SelectedSprintId);
            }

            await _sprintService.MoveTaskToBacklogRemoveAssigneeAsync(id, CurrentUserId, CurrentRole, remarks);
            TempData["ToastMessage"] = "Task moved to backlog and assignee removed.";
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToTaskPage(id, SelectedSprintId);
    }

    // SECTION: Close active sprint after explicit closure review disposition.
    public async Task<IActionResult> OnPostCloseSprintWithDispositionAsync()
    {
        await ResolveIdentityAsync();
        try
        {
            await _sprintService.CloseSprintWithDispositionAsync(
                ClosureInput.SprintId,
                DecodeRowVersion(ClosureInput.RowVersion),
                ResolveClosureTaskIds("carry"),
                ClosureInput.TargetSprintId,
                ResolveClosureTaskIds("outside"),
                ResolveClosureTaskIds("backlog"),
                ClosureInput.Remarks,
                CurrentUserId,
                CurrentRole);
            TempData["ToastMessage"] = "Sprint closed after closure review.";
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = ex.Message;
        }

        return RedirectToPage(new { ViewMode = "Planning", PlanningTab = "Close", SelectedSprintId = ClosureInput.SprintId });
    }

    // SECTION: Unified progress update handler used by the rationalised task details pane.
    public Task<IActionResult> OnPostUpdateProgressAsync()
    {
        return OnPostAddUpdateAsync();
    }

    // SECTION: Post task progress update with optional workflow status change.
    public async Task<IActionResult> OnPostAddUpdateAsync()
    {
        await ResolveIdentityAsync();

        // SECTION: Reset model validation scope for update posting only.
        ModelState.Clear();

        // SECTION: Validate only update form data so create-task fields do not block update posting.
        TryValidateModel(UpdateInput, nameof(UpdateInput));

        if (!ModelState.IsValid)
        {
            TempData["ToastError"] = "Unable to save update. Please check the entered details and try again.";
            return RedirectToTaskPage(UpdateInput.TaskId, SelectedSprintId);
        }

        var requestedStatus = UpdateInput.NewStatus?.Trim();
        var currentTask = await _service.GetTaskAsync(UpdateInput.TaskId);
        var hasStatusChange = !string.IsNullOrWhiteSpace(requestedStatus)
            && (currentTask is null || !string.Equals(currentTask.Status, requestedStatus, StringComparison.OrdinalIgnoreCase));
        var hasProgressNote = !string.IsNullOrWhiteSpace(UpdateInput.Body);
        var hasFiles = UpdateInput.Files?.Any(file => file.Length > 0) == true;

        // SECTION: Important workflow transitions need human context in the progress timeline.
        if (hasStatusChange
            && (string.Equals(requestedStatus, ActionTaskStatuses.Blocked, StringComparison.OrdinalIgnoreCase)
                || string.Equals(requestedStatus, ActionTaskStatuses.Submitted, StringComparison.OrdinalIgnoreCase))
            && !hasProgressNote)
        {
            TempData["ToastError"] = "Enter a progress note when blocking a task or submitting it for closure.";
            return RedirectToTaskPage(UpdateInput.TaskId, SelectedSprintId);
        }

        if (!hasProgressNote && !hasFiles && !hasStatusChange)
        {
            TempData["ToastError"] = "No update was applied.";
            return RedirectToTaskPage(UpdateInput.TaskId, SelectedSprintId);
        }

        try
        {
            await _collaborationService.AddUpdateAndMaybeChangeStatusAsync(
                UpdateInput.TaskId,
                UpdateInput.Body,
                requestedStatus,
                CurrentUserId,
                CurrentRole,
                UpdateInput.Files ?? new List<IFormFile>(),
                DecodeRowVersion(UpdateInput.RowVersion));

            TempData["ToastMessage"] = BuildProgressUpdateToast(hasProgressNote, hasFiles, hasStatusChange);
        }
        catch (ActionTaskConcurrencyException ex)
        {
            TempData["ToastError"] = ex.Message;
        }
        catch (InvalidOperationException ex)
        {
            TempData["ToastError"] = string.Equals(
                ex.Message,
                "Update text is required unless at least one attachment is uploaded.",
                StringComparison.Ordinal)
                ? "Enter an update or attach at least one file."
                : ex.Message;
        }

        return RedirectToTaskPage(UpdateInput.TaskId, SelectedSprintId);
    }


    // SECTION: Progress update toast wording mirrors the actual saved changes.
    private static string BuildProgressUpdateToast(bool hasProgressNote, bool hasFiles, bool hasStatusChange)
    {
        var hasUserProgress = hasProgressNote || hasFiles;
        if (hasUserProgress && hasStatusChange)
        {
            return "Progress update saved and task status updated.";
        }

        if (hasStatusChange)
        {
            return "Task status updated.";
        }

        return "Progress update saved.";
    }

    // SECTION: Shared data loading
    private async Task LoadDataAsync()
    {
        await ResolveIdentityAsync();
        NormalizeRegisterScopeFilters();

        var sourceTasks = await _service.GetTasksAsync(CurrentUserId, CurrentRole);

        // SECTION: Query read-model dependencies
        AssignableUsers = await _userLookup.LoadAssignableUsersAsync(CurrentRole);
        TaskAssigneeNames = await _userLookup.LoadTaskAssigneeNamesAsync(sourceTasks);

        // SECTION: Workspace read-model orchestration boundary
        var workspaceReadModel = await _workspaceBuilder.BuildAsync(BuildWorkspaceRequest(), sourceTasks, TaskAssigneeNames);
        var readModel = workspaceReadModel.ReadModel;

        // SECTION: Read-model projections assignment boundary
        Tasks = readModel.TaskListTasks;
        CriticalOpenTasks = readModel.CriticalOpenTasks;
        OverdueTasks = readModel.OverdueTasks;
        RecentlySubmittedTasks = readModel.RecentlySubmittedTasks;
        RecentlyUpdatedTasks = readModel.RecentlyUpdatedTasks;
        SprintOverdueTasks = readModel.DueBuckets.Overdue;
        BacklogTasks = readModel.BacklogTasks;
        OutsideSprintTasks = readModel.OutsideSprintTasks;
        SelectedSprintTasks = readModel.SprintReadModel.SelectedSprintTasks;
        SprintBacklogTasks = readModel.SprintReadModel.BacklogTasks;
        Sprints = readModel.SprintReadModel.Sprints;
        ActiveSprint = readModel.SprintReadModel.ActiveSprint;
        SelectedSprint = readModel.SprintReadModel.SelectedSprint;
        SelectedSprintId = SelectedSprint?.Id ?? SelectedSprintId;
        SprintSummary = readModel.SprintReadModel.Summary;
        SprintClosureReview = readModel.SprintReadModel.ClosureReview;
        await PrepareSprintBoardStateAsync();
        ActiveSprintMetrics = readModel.ActiveSprintMetrics;
        MyWorkQueue = _myWorkQueueBuilder.Build(Tasks, ActiveSprint);
        CommandCentreSummary = _commandCentreSummaryBuilder.Build(Tasks, CriticalOpenTasks.Count);
        SprintWorkspaceSummary = _sprintWorkspaceSummaryBuilder.Build(new ActionTaskSprintWorkspaceSummaryRequest(Tasks, BacklogTasks, SelectedSprintTasks, SprintClosureReview.UnfinishedTasks, Sprints, ActiveSprint));
        DueTodayTasks = readModel.DueBuckets.Today;
        DueThisWeekTasks = readModel.DueBuckets.ThisWeek;
        DueLaterTasks = readModel.DueBuckets.Later;
        AssigneePendingCounts = readModel.Reports.AssigneePendingCounts.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        PriorityCounts = readModel.Reports.PriorityCounts.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        StatusCounts = readModel.Reports.StatusCounts.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        OpenAgeingBuckets = readModel.Reports.OpenAgeingBuckets.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        OverdueAgeingBuckets = readModel.Reports.OverdueAgeingBuckets.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        SubmittedPendingClosureAgeingBuckets = readModel.Reports.SubmittedPendingClosureAgeingBuckets.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        BacklogAgeingBuckets = readModel.Reports.BacklogAgeingBuckets.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        AssignedTaskAgeingBuckets = readModel.Reports.AssignedTaskAgeingBuckets.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        BucketDistribution = readModel.Reports.BucketDistribution.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        ResponsiblePersonWorkloads = readModel.Reports.ResponsiblePersonWorkloads.Select(x => new ResponsibleWorkloadSummary(x.ResponsiblePerson, x.Open, x.Overdue, x.Blocked, x.InProgress, x.Submitted, x.Critical)).ToList();
        OutsideSprintWorkloadCounts = readModel.Reports.OutsideSprintWorkloadCounts.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        SprintPerformanceRows = readModel.Reports.SprintPerformanceRows.Select(x => new SprintPerformanceSummary(x.Sprint, x.Status, x.Open, x.Closed, x.OverdueNow, x.Unfinished, x.ClosedLate)).ToList();
        InvalidStateRows = readModel.Reports.InvalidStateRows.Select(x => new InvalidTaskStateSummary(x.Task, x.Issue, x.SuggestedCorrection)).ToList();
        WorkloadSummary = new ActionTaskReportSummary(readModel.Reports.WorkloadSummary.OpenTasks, readModel.Reports.WorkloadSummary.Overdue, readModel.Reports.WorkloadSummary.Blocked, readModel.Reports.WorkloadSummary.PendingClosure, readModel.Reports.WorkloadSummary.BacklogItems);
        CarryForwardBySprint = readModel.Reports.CarryForwardBySprint.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        BlockedAgeingBuckets = readModel.Reports.BlockedAgeingBuckets.Select(x => new CountSummary(x.Name, x.Count)).ToList();
        ReportFilteredTaskCount = readModel.Reports.FilteredTaskCount;
        ReportTotalTaskCount = readModel.Reports.TotalTaskCount;

        await PrepareSelectedTaskInspectorAsync(readModel.ScopeTasks);
    }


    // SECTION: Selected task inspector state is composed by a focused builder to preserve drawer/deep-link behaviour.
    private async Task PrepareSelectedTaskInspectorAsync(IReadOnlyList<ActionTaskItem> scopeTasks)
    {
        var inspector = await _inspectorBuilder.BuildAsync(new ActionTaskInspectorReadModelRequest(TaskId, scopeTasks, CurrentUserId, CurrentRole));
        if (inspector.IsUnavailable)
        {
            TaskId = null;
            TempData["ToastError"] = "The selected task is no longer available in the current view.";
        }

        SelectedTask = inspector.SelectedTask;
        SelectedTaskLogs = inspector.Logs;
        SelectedTaskUpdates = inspector.Updates;
        SelectedTaskLastActivityAtUtc = inspector.LastActivityAtUtc;
        UpdateAttachments = inspector.UpdateAttachments;
        TaskActorNames = inspector.ActorNames;
    }

    // SECTION: Register scope normalization prevents contradictory open/closed filter combinations.
    private void NormalizeRegisterScopeFilters()
    {
        TaskScope = ActionTaskRegisterScopes.Normalize(TaskScope);

        if (!IsRegisterView || !IsOpenTaskScope)
        {
            return;
        }

        if (string.Equals(FilterStatus, ActionTaskStatuses.Closed, StringComparison.OrdinalIgnoreCase))
        {
            FilterStatus = null;
        }

        if (string.Equals(FilterBucket, "Closed", StringComparison.OrdinalIgnoreCase))
        {
            FilterBucket = null;
        }
    }

    // SECTION: Workspace request isolates GET filter, report and sprint state before builder orchestration.
    private ActionTaskWorkspaceRequest BuildWorkspaceRequest()
        => new(
            CurrentUserId,
            CurrentRole,
            IsMyTasksView,
            IsTaskListView,
            IsBacklogView,
            SelectedSprintId,
            FilterStatus,
            FilterPriority,
            FilterAssigneeUserId,
            FilterDueDate,
            FilterSearch,
            SortBy,
            SortDir,
            FilterBucket,
            ReportBucket,
            ReportSprintId,
            ReportAssigneeUserId,
            ReportFromDate,
            ReportToDate,
            ReportStatus,
            ReportPriority,
            ResolvedTaskScope);


    // SECTION: Sprint Board panel defaults and audit state are composed by the Sprint Board state builder.
    private async Task PrepareSprintBoardStateAsync()
    {
        var state = await _sprintBoardStateBuilder.BuildAsync(new ActionTaskSprintBoardStateRequest(
            SelectedSprint,
            ShowCreateSprintPanel,
            ShowEditSprintPanel,
            ShowCreateNextSprintPanel));

        if (state.CreateDefaults is not null)
        {
            SprintInput = new CreateSprintInput
            {
                Name = state.CreateDefaults.Name,
                Goal = state.CreateDefaults.Goal,
                StartDate = state.CreateDefaults.StartDate,
                EndDate = state.CreateDefaults.EndDate
            };
        }

        if (state.EditDefaults is not null)
        {
            SprintEditInput = new UpdateSprintInput
            {
                SprintId = state.EditDefaults.SprintId,
                RowVersion = state.EditDefaults.RowVersion,
                Name = state.EditDefaults.Name,
                Goal = state.EditDefaults.Goal,
                StartDate = state.EditDefaults.StartDate,
                EndDate = state.EditDefaults.EndDate
            };
        }

        if (state.NextDefaults is not null)
        {
            NextSprintInput = new CreateNextSprintInput
            {
                SourceSprintId = state.NextDefaults.SourceSprintId,
                Name = state.NextDefaults.Name,
                Goal = state.NextDefaults.Goal,
                StartDate = state.NextDefaults.StartDate,
                EndDate = state.NextDefaults.EndDate
            };
        }

        SprintAuditHistory = state.AuditHistory;
        SprintActorNames = state.ActorNames;
    }

    // SECTION: Task display projections for richer UI cards and mini-lists.
    public IReadOnlyList<TaskDisplayItem> CriticalOpenTaskDisplays =>
        ToDisplayItems(CriticalOpenTasks);

    public IReadOnlyList<TaskDisplayItem> OverdueTaskDisplays =>
        ToDisplayItems(OverdueTasks);

    public IReadOnlyList<TaskDisplayItem> RecentlySubmittedTaskDisplays =>
        ToDisplayItems(RecentlySubmittedTasks);

    public IReadOnlyList<TaskDisplayItem> RecentlyUpdatedTaskDisplays =>
        ToDisplayItems(RecentlyUpdatedTasks);


    public IReadOnlyList<TaskDisplayItem> DueTodayTaskDisplays =>
        ToDisplayItems(DueTodayTasks);

    public IReadOnlyList<TaskDisplayItem> DueThisWeekTaskDisplays =>
        ToDisplayItems(DueThisWeekTasks);

    public IReadOnlyList<TaskDisplayItem> DueLaterTaskDisplays =>
        ToDisplayItems(DueLaterTasks);

    public IReadOnlyList<TaskDisplayItem> SprintOverdueTaskDisplays =>
        ToDisplayItems(SprintOverdueTasks);

    // SECTION: My Work display projections are composed by the dedicated queue builder.
    public IReadOnlyList<TaskDisplayItem> MyOverdueTaskDisplays =>
        ToDisplayItems(MyWorkQueue.OverdueTasks);

    public IReadOnlyList<TaskDisplayItem> MyDueTodayTaskDisplays =>
        ToDisplayItems(MyWorkQueue.DueTodayTasks);

    public IReadOnlyList<TaskDisplayItem> MyInProgressTaskDisplays =>
        ToDisplayItems(MyWorkQueue.InProgressTasks);

    public IReadOnlyList<TaskDisplayItem> MySubmittedTaskDisplays =>
        ToDisplayItems(MyWorkQueue.SubmittedTasks);

    public IReadOnlyList<TaskDisplayItem> MyActiveSprintTaskDisplays =>
        ToDisplayItems(MyWorkQueue.ActiveSprintTasks);

    public IReadOnlyList<TaskDisplayItem> MyRemainingAssignedTaskDisplays =>
        MyWorkAllMyTasksDisplays;

    // SECTION: My Work queue projections de-duplicate tasks by urgency before rendering primary workspace sections.
    public IReadOnlyList<TaskDisplayItem> MyWorkActionRequiredDisplays =>
        ToDisplayItems(MyWorkQueue.ActionRequiredTasks);

    public IReadOnlyList<TaskDisplayItem> MyWorkCurrentWorkDisplays =>
        ToDisplayItems(MyWorkQueue.CurrentWorkTasks);

    public IReadOnlyList<TaskDisplayItem> MyWorkSubmittedAwaitingClosureDisplays =>
        ToDisplayItems(MyWorkQueue.SubmittedAwaitingClosureTasks);

    public IReadOnlyList<TaskDisplayItem> MyWorkAllMyTasksDisplays =>
        ToDisplayItems(MyWorkQueue.AllMyTasks);

    // SECTION: Legacy My Tasks display alias retained for older partial references.
    public IReadOnlyList<TaskDisplayItem> MyWorkOverdueTaskDisplays =>
        MyOverdueTaskDisplays;

    public IReadOnlyList<TaskDisplayItem> BacklogTaskDisplays =>
        ToDisplayItems(BacklogTasks);

    public IReadOnlyList<TaskDisplayItem> OutsideSprintTaskDisplays =>
        ToDisplayItems(OutsideSprintTasks);

    public IReadOnlyList<TaskDisplayItem> SelectedSprintTaskDisplays =>
        ToDisplayItems(SelectedSprintTasks);

    public IReadOnlyList<TaskDisplayItem> SprintBacklogTaskDisplays =>
        ToDisplayItems(SprintBacklogTasks);

    public IReadOnlyList<TaskDisplayItem> ActiveSprintTaskDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.ActiveSprintTasks);

    public IReadOnlyList<TaskDisplayItem> AssignableBacklogTaskDisplays =>
        ToDisplayItems(SprintBacklogTasks
            .Where(t => !string.Equals(t.Status, ActionTaskStatuses.Closed, StringComparison.OrdinalIgnoreCase))
            .ToList());

    // SECTION: Phase 2A layout helper projections for sprint, backlog, and dashboard UX.
    public IReadOnlyList<ActionSprint> PlannedSprints =>
        SprintWorkspaceSummary.PlannedSprints;

    public IReadOnlyList<ActionSprint> ClosedSprints =>
        SprintWorkspaceSummary.ClosedSprints;

    public int SelectedSprintOverdueCount =>
        SprintWorkspaceSummary.SelectedSprintOverdueCount;

    public IReadOnlyList<TaskDisplayItem> SprintAttentionOverdueTaskDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.SprintAttentionOverdueTasks);

    public IReadOnlyList<TaskDisplayItem> SprintAttentionBlockedTaskDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.SprintAttentionBlockedTasks);

    public IReadOnlyList<TaskDisplayItem> SprintAttentionSubmittedTaskDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.SprintAttentionSubmittedTasks);

    public IReadOnlyList<TaskDisplayItem> SprintCarryForwardCandidateDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.SprintCarryForwardCandidateTasks);

    public int BacklogTotalCount => SprintWorkspaceSummary.BacklogTotalCount;

    public int BacklogHighPriorityCount => SprintWorkspaceSummary.BacklogHighPriorityCount;

    public int BacklogOverdueCount => SprintWorkspaceSummary.BacklogOverdueCount;

    public IReadOnlyList<TaskDisplayItem> ActiveSprintOverdueTaskDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.ActiveSprintOverdueTasks);

    public IReadOnlyList<TaskDisplayItem> ActiveSprintBlockedTaskDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.ActiveSprintBlockedTasks);

    public int ActiveSprintSubmittedTaskCount => SprintWorkspaceSummary.ActiveSprintSubmittedTaskCount;

    public IReadOnlyList<TaskDisplayItem> ActiveSprintSubmittedTaskDisplays =>
        ToDisplayItems(SprintWorkspaceSummary.ActiveSprintSubmittedTasks);

    // SECTION: KPI helpers for dashboard and reports.
    public int ActiveCount => CommandCentreSummary.ActiveCount;
    public int OverdueCount => CommandCentreSummary.OverdueCount;
    public int InProgressCount => CommandCentreSummary.InProgressCount;
    public int SubmittedCount => CommandCentreSummary.SubmittedCount;
    public int BlockedCount => CommandCentreSummary.BlockedCount;
    public int ClosedCount => CommandCentreSummary.ClosedCount;
    public int CriticalOpenCount => CommandCentreSummary.ActiveCriticalCount;
    public int OpenTaskCount => Tasks.Count(t => !string.Equals(t.Status, ActionTaskStatuses.Closed, StringComparison.OrdinalIgnoreCase));
    public int StatusCountsMax => StatusCounts.Count == 0 ? 0 : StatusCounts.Max(x => x.Count);
    public int PriorityCountsMax => PriorityCounts.Count == 0 ? 0 : PriorityCounts.Max(x => x.Count);
    public int AssigneePendingCountsMax => AssigneePendingCounts.Count == 0 ? 0 : AssigneePendingCounts.Max(x => x.Count);
    public int OpenAgeingBucketsMax => OpenAgeingBuckets.Count == 0 ? 0 : OpenAgeingBuckets.Max(x => x.Count);
    public int OverdueAgeingBucketsMax => OverdueAgeingBuckets.Count == 0 ? 0 : OverdueAgeingBuckets.Max(x => x.Count);
    public int BacklogAgeingBucketsMax => BacklogAgeingBuckets.Count == 0 ? 0 : BacklogAgeingBuckets.Max(x => x.Count);
    public int AssignedTaskAgeingBucketsMax => AssignedTaskAgeingBuckets.Count == 0 ? 0 : AssignedTaskAgeingBuckets.Max(x => x.Count);
    public int OutsideSprintWorkloadCountsMax => OutsideSprintWorkloadCounts.Count == 0 ? 0 : OutsideSprintWorkloadCounts.Max(x => x.Count);
    public int CarryForwardBySprintMax => CarryForwardBySprint.Count == 0 ? 0 : CarryForwardBySprint.Max(x => x.Count);
    public int BlockedAgeingBucketsMax => BlockedAgeingBuckets.Count == 0 ? 0 : BlockedAgeingBuckets.Max(x => x.Count);
    public int ActiveCriticalCount => CommandCentreSummary.ActiveCriticalCount;

    public int SubmittedPendingClosureCount => CommandCentreSummary.SubmittedCount;

    public bool HasActiveFilters =>
        (IsTaskListView || IsBacklogView) &&
        (!string.IsNullOrWhiteSpace(FilterStatus)
            || !string.Equals(ResolvedTaskScope, ActionTaskRegisterScopes.Open, StringComparison.OrdinalIgnoreCase)
            || !string.IsNullOrWhiteSpace(FilterBucket)
         || !string.IsNullOrWhiteSpace(FilterPriority)
         || !string.IsNullOrWhiteSpace(FilterAssigneeUserId)
         || FilterDueDate.HasValue
         || !string.IsNullOrWhiteSpace(FilterSearch));


    public bool HasReportFilters =>
        IsReportsView && _routeStateHelper.HasReportFilterRouteState(BuildReportFilterRouteState());

    public string ReportFilterSummary =>
        HasReportFilters
            ? $"Showing {ReportFilteredTaskCount} of {ReportTotalTaskCount} tasks matching the selected report filters."
            : $"Showing all {ReportTotalTaskCount} tasks available to the reports workspace.";

    // SECTION: Planning backlog disclosure mirrors every route value that can alter the backlog read model.
    public bool HasBacklogFilterRouteState => HasTaskFilterRouteState();
    public string DashboardCommandFocusSummary => CommandCentreSummary.DashboardCommandFocusSummary;
    public IReadOnlyList<CountSummary> SubmittedPendingClosureAgeingBuckets { get; private set; } = Array.Empty<CountSummary>();
    public IReadOnlyList<TaskDisplayItem> TopAttentionTaskDisplays => ToDisplayItems(CommandCentreSummary.TopAttentionTasks);

    // SECTION: Command Centre attention projections are prioritized and de-duplicated for exception-led rendering.
    public IReadOnlyList<TaskDisplayItem> CommandPendingClosureTaskDisplays =>
        ToDisplayItems(CommandCentreSummary.PendingClosureTasks);

    public IReadOnlyList<TaskDisplayItem> CommandBlockedTaskDisplays =>
        ToDisplayItems(CommandCentreSummary.BlockedTasks);

    public IReadOnlyList<TaskDisplayItem> CommandOverdueTaskDisplays =>
        ToDisplayItems(CommandCentreSummary.OverdueTasks);

    public IReadOnlyList<TaskDisplayItem> CommandCriticalOpenTaskDisplays =>
        ToDisplayItems(CommandCentreSummary.CriticalOpenTasks);

    public bool HasCommandAttentionItems =>
        CommandPendingClosureTaskDisplays.Any()
        || CommandBlockedTaskDisplays.Any()
        || CommandOverdueTaskDisplays.Any()
        || CommandCriticalOpenTaskDisplays.Any();

    public bool HasActiveSprintExceptions =>
        ActiveSprintOverdueTaskDisplays.Any()
        || ActiveSprintBlockedTaskDisplays.Any()
        || ActiveSprintSubmittedTaskDisplays.Any();

    public int ActiveSprintExceptionCount =>
        SprintWorkspaceSummary.ActiveSprintOverdueTasks
            .Concat(SprintWorkspaceSummary.ActiveSprintBlockedTasks)
            .Concat(SprintWorkspaceSummary.ActiveSprintSubmittedTasks)
            .Select(t => t.Id)
            .Distinct()
            .Count();

    public bool HasRecentActivityItems =>
        RecentlySubmittedTaskDisplays.Any()
        || RecentlyUpdatedTaskDisplays.Any();

    public string CommandSummary => CommandCentreSummary.CommandSummary;

    // SECTION: Percentage helper for CSS bar-width calculations.
    public int ToPercent(int value, int max) =>
        max <= 0 ? 0 : (int)Math.Round((double)value / max * 100);


    // SECTION: Closure-review radio choices are converted to service disposition collections without client script.
    private IReadOnlyCollection<int> ResolveClosureTaskIds(string disposition)
    {
        if (ClosureInput.Dispositions.Count > 0)
        {
            return ClosureInput.Dispositions
                .Where(item => string.Equals(item.Value, disposition, StringComparison.OrdinalIgnoreCase))
                .Select(item => item.Key)
                .ToList();
        }

        return disposition switch
        {
            "carry" => ClosureInput.CarryForwardTaskIds,
            "outside" => ClosureInput.OutsideSprintTaskIds,
            "backlog" => ClosureInput.BacklogTaskIds,
            _ => Array.Empty<int>()
        };
    }

    private async Task ResolveIdentityAsync()
    {
        CurrentUserId = _users.GetUserId(User) ?? string.Empty;
        CurrentRole = ActionTaskRoleResolver.Resolve(User) ?? string.Empty;

        await Task.CompletedTask;
    }

    // SECTION: Resolve a safe, standardized view mode value for postback and redirects


    private async Task ValidateNextSprintStartsAfterSourceSprintAsync()
    {
        // SECTION: Closure-review next sprint sequencing validation.
        var sourceSprint = (await _sprintService.GetSprintsAsync()).FirstOrDefault(s => s.Id == NextSprintInput.SourceSprintId);
        if (sourceSprint is null)
        {
            ModelState.AddModelError($"{nameof(NextSprintInput)}.{nameof(CreateNextSprintInput.SourceSprintId)}", "Source sprint was not found. Reload the closure review and try again.");
            return;
        }

        if (NextSprintInput.StartDate.Date <= sourceSprint.EndDate.Date)
        {
            ModelState.AddModelError($"{nameof(NextSprintInput)}.{nameof(CreateNextSprintInput.StartDate)}", $"Next sprint start date must be later than the source sprint end date ({sourceSprint.EndDate:dd MMM yyyy}).");
        }
    }

    private void ValidateSprintDateRange(DateTime startDate, DateTime endDate, string prefix)
    {
        // SECTION: Page-level sprint date validation mirrors workflow policy for clear form errors.
        if (startDate.Date > endDate.Date)
        {
            ModelState.AddModelError($"{prefix}.EndDate", "Sprint start date must be on or before the end date.");
        }
    }

    // SECTION: Decode Base64 row-version tokens posted from forms
    private static byte[] DecodeRowVersion(string rowVersion)
    {
        if (string.IsNullOrWhiteSpace(rowVersion))
        {
            throw new InvalidOperationException("Task version is missing. Please reload and try again.");
        }

        try
        {
            return Convert.FromBase64String(rowVersion);
        }
        catch (FormatException)
        {
            throw new InvalidOperationException("Task version is invalid. Please reload and try again.");
        }
    }

    private static byte[] DecodeSprintRowVersion(string rowVersion)
    {
        if (string.IsNullOrWhiteSpace(rowVersion))
        {
            throw new InvalidOperationException("Sprint version is missing. Please reload and try again.");
        }

        try
        {
            return Convert.FromBase64String(rowVersion);
        }
        catch (FormatException)
        {
            throw new InvalidOperationException("Sprint version is invalid. Please reload and try again.");
        }
    }

    // SECTION: Sprint Board route normalization is delegated to the shared route-state helper.
    private string ResolvePlanningView()
        => BuildRouteState().PlanningView;

    private string ResolvePlanningTab()
        => BuildRouteState().PlanningTab;

    // SECTION: Shared task redirect route preserves workspace, selection, and relevant list state from inspector actions.
    private RedirectToPageResult RedirectToTaskPage(int? taskId, int? selectedSprintId)
    {
        var routeValues = BuildTaskWorkspaceRouteValues(taskId, selectedSprintId);
        return RedirectToPage(routeValues);
    }

    // SECTION: Canonical workspace route values are delegated to the shared route-state helper.
    private object BuildTaskWorkspaceRouteValues(int? taskId, int? selectedSprintId)
        => _routeStateHelper.BuildTaskWorkspaceRouteValues(BuildRouteState(), taskId, selectedSprintId);

    // SECTION: Task-list filter route preservation is centralized in the shared route-state helper.
    private ActionTaskRouteState BuildRouteState()
        => _routeStateHelper.BuildRouteState(new ActionTaskRouteStateRequest(
            ViewMode,
            PlanningTab,
            PlanningView,
            TaskId,
            SelectedSprintId,
            SelectedSprint is not null,
            ActiveSprint is not null,
            BuildFilterRouteState()));

    private ActionTaskFilterRouteState BuildFilterRouteState()
        => new(FilterStatus, FilterPriority, FilterAssigneeUserId, FilterDueDate, FilterSearch, SortBy, SortDir, FilterBucket, ResolvedTaskScope);

    private ActionTaskReportFilterRouteState BuildReportFilterRouteState()
        => new(ReportBucket, ReportSprintId, ReportAssigneeUserId, ReportFromDate, ReportToDate, ReportStatus, ReportPriority);

    // SECTION: Planning backlog filter detection keeps canonical Planning routes compatible with legacy Backlog filtered views.
    private bool IsPlanningBacklogFilterContext()
        => BuildRouteState().ShouldPreserveTaskFilters
            && string.Equals(BuildRouteState().ViewMode, "Planning", StringComparison.OrdinalIgnoreCase);

    // SECTION: Shared filter-state detection is delegated to the shared route-state helper.
    private bool HasTaskFilterRouteState()
        => _routeStateHelper.HasTaskFilterRouteState(BuildFilterRouteState());

    // SECTION: Legacy view-state matching isolates backward-compatible aliases from canonical workspace names.
    private bool IsLegacyViewMode(string legacyViewMode)
        => _routeStateHelper.IsLegacyViewMode(ViewMode, legacyViewMode);

    private string ResolveViewMode()
        => BuildRouteState().ViewMode;


    private static readonly ActionTaskMyWorkQueueReadModel EmptyMyWorkQueue = new(
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        Array.Empty<ActionTaskItem>(),
        0,
        0,
        0,
        0,
        0);

    public sealed class CreateDirectTaskInput
    {
        [Display(Name = "Task Title")]
        [Required, StringLength(200)]
        public string Title { get; set; } = string.Empty;

        [Display(Name = "Description / Instructions")]
        [Required, StringLength(4000)]
        public string Description { get; set; } = string.Empty;

        [Display(Name = "Assignee")]
        public string AssignedToUserId { get; set; } = string.Empty;

        [Display(Name = "Due Date")]
        [Required]
        public DateTime DueDate { get; set; }

        [Required, StringLength(24)]
        public string Priority { get; set; } = "Normal";
    }

    public sealed class CreateBacklogItemInput
    {
        [Display(Name = "Backlog Item Title")]
        [Required, StringLength(200)]
        public string Title { get; set; } = string.Empty;

        [Display(Name = "Description / Planning Notes")]
        [Required, StringLength(4000)]
        public string Description { get; set; } = string.Empty;

        [Display(Name = "Target Date")]
        [Required]
        public DateTime TargetDate { get; set; }

        [Required, StringLength(24)]
        public string Priority { get; set; } = "Normal";
    }

    public class CreateSprintInput
    {
        [Display(Name = "Sprint name")]
        [Required, StringLength(160)]
        public string Name { get; set; } = string.Empty;

        [Display(Name = "Start date")]
        [Required]
        public DateTime StartDate { get; set; }

        [Display(Name = "End date")]
        [Required]
        public DateTime EndDate { get; set; }

        [Display(Name = "Goal / Command Focus")]
        [StringLength(2000)]
        public string? Goal { get; set; }

        public static CreateSprintInput FromSprint(DateTime today)
        {
            // SECTION: Default to editable half-month command sprints.
            var start = today.Day <= 15 ? new DateTime(today.Year, today.Month, 1) : new DateTime(today.Year, today.Month, 16);
            var end = today.Day <= 15 ? new DateTime(today.Year, today.Month, 15) : new DateTime(today.Year, today.Month, DateTime.DaysInMonth(today.Year, today.Month));
            return new CreateSprintInput
            {
                Name = $"Sprint {start:dd MMM} - {end:dd MMM}",
                StartDate = start,
                EndDate = end
            };
        }
    }

    public sealed class UpdateSprintInput : CreateSprintInput
    {
        [Required]
        public int SprintId { get; set; }

        [Required]
        public string RowVersion { get; set; } = string.Empty;

        public static UpdateSprintInput FromSprint(ActionSprint sprint)
            => new()
            {
                SprintId = sprint.Id,
                RowVersion = Convert.ToBase64String(sprint.RowVersion),
                Name = sprint.Name,
                Goal = sprint.Goal,
                StartDate = sprint.StartDate,
                EndDate = sprint.EndDate
            };
    }

    public sealed class CreateNextSprintInput : CreateSprintInput
    {
        [Required]
        public int SourceSprintId { get; set; }

        public static CreateNextSprintInput FromSourceSprint(ActionSprint sprint)
        {
            // SECTION: Closure-review next sprint defaults immediately follow source sprint end.
            var start = sprint.EndDate.Date.AddDays(1);
            var end = start.AddDays(14);
            return new CreateNextSprintInput
            {
                SourceSprintId = sprint.Id,
                Name = $"Sprint {start:dd MMM} - {end:dd MMM}",
                Goal = sprint.Goal,
                StartDate = start,
                EndDate = end
            };
        }
    }

    public sealed class SprintClosureInput
    {
        [Required]
        public int SprintId { get; set; }

        [Required]
        public string RowVersion { get; set; } = string.Empty;

        public int? TargetSprintId { get; set; }

        public List<int> CarryForwardTaskIds { get; set; } = new();

        public List<int> OutsideSprintTaskIds { get; set; } = new();

        public List<int> BacklogTaskIds { get; set; } = new();

        public Dictionary<int, string> Dispositions { get; set; } = new();

        [Required, StringLength(2000)]
        public string Remarks { get; set; } = string.Empty;
    }


    public sealed class ChangeTaskDateInput
    {
        [Required]
        public int TaskId { get; set; }

        [Required]
        public string RowVersion { get; set; } = string.Empty;

        [Display(Name = "New Date")]
        [Required]
        public DateTime NewDate { get; set; }

        [Required, StringLength(1000)]
        public string Remarks { get; set; } = string.Empty;
    }

    public sealed class AddTaskUpdateInput
    {
        [Required]
        public int TaskId { get; set; }

        [Required]
        public string RowVersion { get; set; } = string.Empty;

        [StringLength(4000)]
        public string Body { get; set; } = string.Empty;

        [Display(Name = "Change status")]
        public string? NewStatus { get; set; }

        public List<IFormFile> Files { get; set; } = new();
    }

    public sealed record CountSummary(string Name, int Count);
    public sealed record ActionTaskReportSummary(int OpenTasks = 0, int Overdue = 0, int Blocked = 0, int PendingClosure = 0, int BacklogItems = 0);
    public sealed record ResponsibleWorkloadSummary(string ResponsiblePerson, int Open, int Overdue, int Blocked, int InProgress, int Submitted, int Critical);
    public sealed record SprintPerformanceSummary(string Sprint, string Status, int Open, int Closed, int OverdueNow, int Unfinished, int ClosedLate);
    public sealed record InvalidTaskStateSummary(string Task, string Issue, string SuggestedCorrection);
    public sealed class TaskDisplayItem
    {
        public ActionTaskItem Task { get; init; } = default!;
        public string AssigneeName { get; init; } = string.Empty;
    }

    public bool IsTaskOverdue(ActionTaskItem task) =>
        IsOpenTask(task)
        && !string.Equals(task.Status, ActionTaskStatuses.Submitted, StringComparison.OrdinalIgnoreCase)
        && ActionTaskBucketClassifier.ResolveBucket(task) != ActionTaskBucket.Invalid
        && task.DueDate.Date < _clock.IstToday;

    // SECTION: Shared open-task predicate keeps personal and command projections aligned.
    private static bool IsOpenTask(ActionTaskItem task) =>
        !string.Equals(task.Status, ActionTaskStatuses.Closed, StringComparison.OrdinalIgnoreCase);


    private IReadOnlyList<TaskDisplayItem> ToDisplayItems(IReadOnlyList<ActionTaskItem> tasks) =>
        tasks.Select(task => new TaskDisplayItem
        {
            Task = task,
            AssigneeName = ResolveAssigneeName(task.AssignedToUserId)
        }).ToList();
}
