using Microsoft.EntityFrameworkCore;
using ProjectManagement.Features.MediaLibrary.Data;
using ProjectManagement.Features.MediaLibrary.Domain;
namespace ProjectManagement.Features.MediaLibrary.Services;
public sealed class FaceReviewService : IFaceReviewService
{
    private readonly MediaLibraryDbContext _db; public FaceReviewService(MediaLibraryDbContext db)=>_db=db;
    public async Task<Guid> CreatePersonAndAssignAsync(Guid faceId,string name,string userId,CancellationToken ct){var now=DateTimeOffset.UtcNow;var p=new MediaPerson{Id=Guid.NewGuid(),DisplayName=name.Trim(),NormalizedName=name.Trim().ToUpperInvariant(),Status=MediaPersonStatus.Confirmed,CreatedByUserId=userId,CreatedAtUtc=now,UpdatedAtUtc=now,RepresentativeFaceId=faceId};_db.Persons.Add(p);await AssignCore(faceId,p.Id,userId,null,ct);await _db.SaveChangesAsync(ct);return p.Id;}
    public async Task AssignAsync(Guid faceId,Guid personId,string userId,double? confidence,CancellationToken ct){await AssignCore(faceId,personId,userId,confidence,ct);await _db.SaveChangesAsync(ct);}
    private async Task AssignCore(Guid faceId,Guid personId,string userId,double? confidence,CancellationToken ct){var active=await _db.PersonFaces.Where(x=>x.MediaFaceId==faceId&&x.RemovedAtUtc==null).ToListAsync(ct);foreach(var x in active)x.RemovedAtUtc=DateTimeOffset.UtcNow;_db.PersonFaces.Add(new MediaPersonFace{MediaFaceId=faceId,MediaPersonId=personId,AssignmentType=FaceAssignmentType.HumanConfirmed,AssignmentConfidence=confidence,AssignedByUserId=userId,AssignedAtUtc=DateTimeOffset.UtcNow});_db.IdentityAudits.Add(new MediaIdentityAudit{FaceId=faceId,NewPersonId=personId,Action="Assign",PerformedByUserId=userId,PerformedAtUtc=DateTimeOffset.UtcNow});var pending=await _db.FaceReviewDecisions.Where(x=>x.MediaFaceId==faceId&&x.Decision==FaceReviewDecisionType.Pending).ToListAsync(ct);foreach(var d in pending){d.Decision=d.CandidatePersonId==personId?FaceReviewDecisionType.Confirmed:FaceReviewDecisionType.Rejected;d.DecidedByUserId=userId;d.DecidedAtUtc=DateTimeOffset.UtcNow;}}
    public async Task RejectAsync(Guid faceId,Guid? personId,string userId,CancellationToken ct){var items=await _db.FaceReviewDecisions.Where(x=>x.MediaFaceId==faceId&&x.Decision==FaceReviewDecisionType.Pending&&(personId==null||x.CandidatePersonId==personId)).ToListAsync(ct);foreach(var d in items){d.Decision=FaceReviewDecisionType.Rejected;d.DecidedByUserId=userId;d.DecidedAtUtc=DateTimeOffset.UtcNow;}_db.IdentityAudits.Add(new MediaIdentityAudit{FaceId=faceId,PreviousPersonId=personId,Action="Reject",PerformedByUserId=userId,PerformedAtUtc=DateTimeOffset.UtcNow});await _db.SaveChangesAsync(ct);}
    public async Task SuppressAsync(Guid faceId,string userId,CancellationToken ct){var face=await _db.Faces.SingleAsync(x=>x.Id==faceId,ct);face.IsSuppressed=true;face.QualityStatus=FaceQualityStatus.Suppressed;face.SuppressedAtUtc=DateTimeOffset.UtcNow;face.SuppressedByUserId=userId;face.UpdatedAtUtc=DateTimeOffset.UtcNow;_db.IdentityAudits.Add(new MediaIdentityAudit{FaceId=faceId,Action="Suppress",PerformedByUserId=userId,PerformedAtUtc=DateTimeOffset.UtcNow});await _db.SaveChangesAsync(ct);}
}
