using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using ProjectManagement.Features.MediaLibrary.Data;
using ProjectManagement.Features.MediaLibrary.Domain;
using ProjectManagement.Features.MediaLibrary.Options;

namespace ProjectManagement.Features.MediaLibrary.Services;

/// <summary>
/// Projects existing face-candidate evidence into a person-first workflow:
/// "I know this person; show me other photographs that may contain them." Candidate
/// evidence remains review-only and is generated by the normal background matcher.
/// </summary>
public sealed class PersonPhotoDiscoveryQueryService : IPersonPhotoDiscoveryQueryService
{
    private const int MaximumCandidateRowsRead = 500;

    private readonly MediaLibraryDbContext _db;
    private readonly IMediaAssetVisibilityPolicy _visibility;
    private readonly MediaPeopleOptions _options;

    public PersonPhotoDiscoveryQueryService(
        MediaLibraryDbContext db,
        IMediaAssetVisibilityPolicy visibility,
        IOptions<MediaLibraryOptions> options)
    {
        _db = db ?? throw new ArgumentNullException(nameof(db));
        _visibility = visibility ?? throw new ArgumentNullException(nameof(visibility));
        _options = options?.Value.People ?? throw new ArgumentNullException(nameof(options));
    }

    public async Task<PersonPhotoDiscoverySummary?> GetSummaryAsync(
        Guid personId,
        bool includeDiscoveryState,
        CancellationToken cancellationToken)
    {
        if (personId == Guid.Empty)
        {
            return null;
        }

        var person = await _db.Persons
            .AsNoTracking()
            .Where(item => item.Id == personId
                           && item.Status == MediaPersonStatus.Confirmed
                           && !item.IsHidden)
            .Select(item => new { item.Id, item.DisplayName })
            .SingleOrDefaultAsync(cancellationToken);
        if (person is null)
        {
            return null;
        }

        var visibleAssetIds = BuildVisibleAssetIdsQuery();
        var confirmedRows =
            from assignment in _db.PersonFaces.AsNoTracking()
            join face in _db.Faces.AsNoTracking()
                on assignment.MediaFaceId equals face.Id
            join asset in _db.Assets.AsNoTracking()
                on face.MediaAssetId equals asset.Id
            where assignment.MediaPersonId == personId
                  && assignment.RemovedAtUtc == null
                  && !face.IsSuppressed
                  && asset.Kind == MediaAssetKind.Photo
                  && visibleAssetIds.Contains(asset.Id)
            select new { asset.Id, asset.MediaDateUtc };

        var confirmedPhotoCount = await confirmedRows
            .Select(row => row.Id)
            .Distinct()
            .CountAsync(cancellationToken);
        var latestMediaDateUtc = confirmedPhotoCount == 0
            ? (DateTimeOffset?)null
            : await confirmedRows.MaxAsync(row => (DateTimeOffset?)row.MediaDateUtc, cancellationToken);

        if (!includeDiscoveryState)
        {
            return new PersonPhotoDiscoverySummary(
                person.Id,
                person.DisplayName,
                confirmedPhotoCount,
                latestMediaDateUtc,
                0,
                0,
                0,
                0);
        }

        var trustedReferenceCount = await BuildValidTrustedReferenceFacesQuery(
                _db,
                personId,
                _options.Embedder.Key,
                _options.Embedder.Version,
                _options.Embedder.EmbeddingDimension,
                visibleAssetIds,
                _options.CandidateMinimumTrustedReferenceQuality)
            .CountAsync(cancellationToken);

        var possibleMatchCount = trustedReferenceCount == 0
            ? 0
            : await BuildCandidateRowsQuery(
                    _db,
                    personId,
                    _options.Embedder.Key,
                    _options.Embedder.Version,
                    visibleAssetIds)
                .Select(row => row.AssetId)
                .Distinct()
                .CountAsync(cancellationToken);

        var reviewableFaces = MediaPeopleQueryService.BuildReviewableFacesQuery(_db)
            .Where(face => visibleAssetIds.Contains(face.MediaAssetId));
        var backgroundMatchingCount = await reviewableFaces.CountAsync(face =>
            face.CandidateSearchStatus == FaceCandidateSearchStatus.Pending
            || face.CandidateSearchStatus == FaceCandidateSearchStatus.Processing,
            cancellationToken);
        var matchingFailureCount = await reviewableFaces.CountAsync(face =>
            face.CandidateSearchStatus == FaceCandidateSearchStatus.Failed,
            cancellationToken);

        return new PersonPhotoDiscoverySummary(
            person.Id,
            person.DisplayName,
            confirmedPhotoCount,
            latestMediaDateUtc,
            trustedReferenceCount,
            possibleMatchCount,
            backgroundMatchingCount,
            matchingFailureCount);
    }

    public async Task<PersonPhotoDiscoveryResult?> GetCandidatesAsync(
        Guid personId,
        int limit,
        CancellationToken cancellationToken)
    {
        var summary = await GetSummaryAsync(personId, includeDiscoveryState: true, cancellationToken);
        if (summary is null)
        {
            return null;
        }

        if (!summary.HasTrustedReference || summary.PossibleMatchCount == 0)
        {
            return new PersonPhotoDiscoveryResult(
                summary,
                Array.Empty<PersonPhotoCandidate>(),
                summary.PossibleMatchCount);
        }

        var visibleAssetIds = BuildVisibleAssetIdsQuery();
        var candidateRows = await BuildCandidateRowsQuery(
                _db,
                personId,
                _options.Embedder.Key,
                _options.Embedder.Version,
                visibleAssetIds)
            .OrderByDescending(row => row.Similarity)
            .ThenByDescending(row => row.QualityScore)
            .ThenByDescending(row => row.MediaDateUtc)
            .Take(MaximumCandidateRowsRead)
            .ToListAsync(cancellationToken);

        // Detector overlap can produce more than one candidate face in one photograph.
        // A person profile should show that photograph once, using its strongest valid
        // appearance. Identity assignment still targets the selected face, never the photo.
        var candidates = candidateRows
            .GroupBy(row => row.AssetId)
            .Select(group => group
                .OrderByDescending(row => row.Similarity ?? double.NegativeInfinity)
                .ThenByDescending(row => row.QualityScore)
                .ThenBy(row => row.FaceId)
                .First())
            .OrderByDescending(row => row.Similarity ?? double.NegativeInfinity)
            .ThenByDescending(row => row.MediaDateUtc)
            .Take(Math.Clamp(limit, 1, 48))
            .Select(MapCandidate)
            .ToList();

        return new PersonPhotoDiscoveryResult(summary, candidates, summary.PossibleMatchCount);
    }

    public async Task<IReadOnlyDictionary<Guid, PersonPhotoCandidate>> GetEligibleCandidatesAsync(
        Guid personId,
        IReadOnlyCollection<Guid> faceIds,
        CancellationToken cancellationToken)
    {
        var selected = (faceIds ?? Array.Empty<Guid>())
            .Where(id => id != Guid.Empty)
            .Distinct()
            .Take(Math.Clamp(_options.CandidateBatchConfirmationLimit, 1, 100))
            .ToArray();
        if (personId == Guid.Empty || selected.Length == 0)
        {
            return new Dictionary<Guid, PersonPhotoCandidate>();
        }

        var visibleAssetIds = BuildVisibleAssetIdsQuery();
        var hasTrustedReference = await BuildValidTrustedReferenceFacesQuery(
                _db,
                personId,
                _options.Embedder.Key,
                _options.Embedder.Version,
                _options.Embedder.EmbeddingDimension,
                visibleAssetIds,
                _options.CandidateMinimumTrustedReferenceQuality)
            .AnyAsync(cancellationToken);
        if (!hasTrustedReference)
        {
            return new Dictionary<Guid, PersonPhotoCandidate>();
        }

        var rows = await BuildCandidateRowsQuery(
                _db,
                personId,
                _options.Embedder.Key,
                _options.Embedder.Version,
                visibleAssetIds)
            .Where(row => selected.Contains(row.FaceId))
            .ToListAsync(cancellationToken);

        return rows
            .GroupBy(row => row.FaceId)
            .ToDictionary(
                group => group.Key,
                group => MapCandidate(group
                    .OrderByDescending(row => row.Similarity ?? double.NegativeInfinity)
                    .First()));
    }

    internal static IQueryable<PersonPhotoDiscoveryDatabaseRow> BuildCandidateRowsQuery(
        MediaLibraryDbContext db,
        Guid personId,
        string modelKey,
        string modelVersion,
        IQueryable<long>? visibleAssetIds = null)
    {
        ArgumentNullException.ThrowIfNull(db);

        var rows =
            from decision in db.FaceReviewDecisions.AsNoTracking()
            join face in db.Faces.AsNoTracking()
                on decision.MediaFaceId equals face.Id
            join asset in db.Assets.AsNoTracking()
                on face.MediaAssetId equals asset.Id
            join person in db.Persons.AsNoTracking()
                on decision.CandidatePersonId equals (Guid?)person.Id
            where decision.CandidatePersonId == personId
                  && decision.Decision == FaceReviewDecisionType.Pending
                  && decision.ModelKey == modelKey
                  && decision.ModelVersion == modelVersion
                  && decision.Similarity.HasValue
                  && face.CandidateSearchStatus == FaceCandidateSearchStatus.Ready
                  && asset.Kind == MediaAssetKind.Photo
                  && !face.IsSuppressed
                  && face.QualityStatus != FaceQualityStatus.ProcessingFailed
                  && person.Status == MediaPersonStatus.Confirmed
                  && !person.IsHidden
                  && !db.PersonFaces.Any(assignment =>
                      assignment.MediaFaceId == face.Id
                      && assignment.RemovedAtUtc == null)
                  && !db.PersonFaces.Any(assignment =>
                      assignment.MediaPersonId == personId
                      && assignment.RemovedAtUtc == null
                      && assignment.MediaFace.MediaAssetId == asset.Id)
                  && !db.FaceReviewDecisions.Any(review =>
                      review.MediaFaceId == face.Id
                      && !review.CandidatePersonId.HasValue
                      && review.Decision == FaceReviewDecisionType.Ignored)
            select new PersonPhotoDiscoveryDatabaseRow
            {
                DecisionId = decision.Id,
                FaceId = face.Id,
                AssetId = asset.Id,
                ContextTitle = asset.ContextTitle,
                ContextSubtitle = asset.ContextSubtitle,
                MediaDateUtc = asset.MediaDateUtc,
                QualityScore = face.QualityScore,
                Similarity = decision.Similarity,
                BestReferenceSimilarity = decision.BestReferenceSimilarity,
                MeanTopSimilarity = decision.MeanTopSimilarity,
                ReferenceCount = decision.ReferenceCount,
                MarginToNext = decision.MarginToNext,
                MarginAvailable = decision.MarginAvailable,
                ConfidenceLevel = decision.ConfidenceLevel,
                DecisionConcurrencyToken = decision.ConcurrencyToken
            };

        if (visibleAssetIds is not null)
        {
            rows = rows.Where(row => visibleAssetIds.Contains(row.AssetId));
        }

        return rows;
    }

    internal static IQueryable<Guid> BuildValidTrustedReferenceFacesQuery(
        MediaLibraryDbContext db,
        Guid personId,
        string modelKey,
        string modelVersion,
        int dimension,
        IQueryable<long>? visibleAssetIds = null,
        double minimumReferenceQuality = 0d)
    {
        ArgumentNullException.ThrowIfNull(db);

        var query =
            from assignment in db.PersonFaces.AsNoTracking()
            join face in db.Faces.AsNoTracking()
                on assignment.MediaFaceId equals face.Id
            where assignment.MediaPersonId == personId
                  && assignment.RemovedAtUtc == null
                  && assignment.ReferenceStatus == FaceReferenceStatus.TrustedReference
                  && !face.IsSuppressed
                  && (face.QualityStatus == FaceQualityStatus.EmbeddingEligible
                      || face.QualityStatus == FaceQualityStatus.Detected
                      || face.QualityStatus == FaceQualityStatus.CropIncomplete
                      || face.QualityStatus == FaceQualityStatus.Occluded)
                  && face.QualityScore >= minimumReferenceQuality
                  && face.Embeddings.Any(embedding =>
                      embedding.InvalidatedAtUtc == null
                      && embedding.ModelKey == modelKey
                      && embedding.ModelVersion == modelVersion
                      && embedding.Dimension == dimension)
            select new { face.Id, face.MediaAssetId };

        if (visibleAssetIds is not null)
        {
            query = query.Where(row => visibleAssetIds.Contains(row.MediaAssetId));
        }

        return query.Select(row => row.Id).Distinct();
    }

    private IQueryable<long> BuildVisibleAssetIdsQuery()
        => _visibility
            .Apply(_db.Assets.AsNoTracking())
            .Select(asset => asset.Id);

    private static PersonPhotoCandidate MapCandidate(PersonPhotoDiscoveryDatabaseRow row)
        => new(
            row.DecisionId,
            row.FaceId,
            row.AssetId,
            row.ContextTitle,
            row.ContextSubtitle,
            row.MediaDateUtc,
            row.QualityScore,
            row.Similarity ?? 0d,
            row.BestReferenceSimilarity ?? row.Similarity ?? 0d,
            row.MeanTopSimilarity ?? row.Similarity ?? 0d,
            row.ReferenceCount,
            row.MarginToNext,
            row.MarginAvailable,
            row.ConfidenceLevel,
            row.DecisionConcurrencyToken);
}
